Repository lammps/lammps, pull requests merged in 2018-12, with the labels that each got.

#1247 Changes to manual related to including PLUMED in LAMMPS
  doc/src/Build_extras.txt
  doc/src/fix_plumed.txt
Labels: documentation

#1248 cmake: USER-PLUMED does not LAPACK anymore
  cmake/CMakeLists.txt
Labels: cmake

#1253 Final cosmetic changes for stable release
  cmake/CMakeLists.txt
  doc/src/Build_extras.txt
  doc/src/Manual.txt
  doc/src/Tools.txt
  doc/src/fix_rigid_meso.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/drude/butane/log.27Nov18.butane.lang.g++.1
  examples/USER/drude/butane/log.27Nov18.butane.lang.g++.4
  examples/USER/drude/butane/log.27Nov18.butane.nh.g++.1
  examples/USER/drude/butane/log.27Nov18.butane.nh.g++.4
  examples/USER/drude/butane/log.butane.lang.18Jul15.linux.1
  examples/USER/drude/butane/log.butane.lang.18Jul15.linux.4
  examples/USER/drude/butane/log.butane.nh.18Jul15.linux.3
  examples/USER/drude/butane/log.butane.nh.18Jul15.linux.4
  examples/USER/drude/ethanol/log.27Nov18.ethanol.lang.g++.1
  examples/USER/drude/ethanol/log.27Nov18.ethanol.lang.g++.4
  examples/USER/drude/ethanol/log.27Nov18.ethanol.nh.g++.1
  examples/USER/drude/ethanol/log.27Nov18.ethanol.nh.g++.4
  examples/USER/drude/ethanol/log.ethanol.lang.8Jul15.linux.1
  examples/USER/drude/ethanol/log.ethanol.lang.8Jul15.linux.4
  examples/USER/drude/ethanol/log.ethanol.nh.8Jul15.linux.1
  examples/USER/drude/ethanol/log.ethanol.nh.8Jul15.linux.4
  examples/USER/drude/swm4-ndp/log.27Nov18.swm4-ndp.lang.g++.1
  examples/USER/drude/swm4-ndp/log.27Nov18.swm4-ndp.lang.g++.4
  examples/USER/drude/swm4-ndp/log.27Nov18.swm4-ndp.nh.g++.1
  examples/USER/drude/swm4-ndp/log.27Nov18.swm4-ndp.nh.g++.4
  examples/USER/drude/swm4-ndp/log.swm4-ndp.lang.8Jul15.linux.1
  examples/USER/drude/swm4-ndp/log.swm4-ndp.lang.8Jul15.linux.4
  examples/USER/drude/swm4-ndp/log.swm4-ndp.nh.8Jul15.linux.1
  examples/USER/drude/swm4-ndp/log.swm4-ndp.nh.8Jul15.linux.4
  examples/USER/drude/toluene/log.27Nov18.toluene.lang.g++.1
  examples/USER/drude/toluene/log.27Nov18.toluene.lang.g++.4
  examples/USER/drude/toluene/log.27Nov18.toluene.nh.g++.1
  examples/USER/drude/toluene/log.27Nov18.toluene.nh.g++.4
  examples/USER/drude/toluene/log.toluene.lang.11Aug17.linux.1
  examples/USER/drude/toluene/log.toluene.lang.11Aug17.linux.4
  examples/USER/drude/toluene/log.toluene.nh.11Aug17.linux.1
  examples/USER/drude/toluene/log.toluene.nh.11Aug17.linux.4
  lib/mscg/.gitignore
  src/.gitignore
  src/MAKE/MACHINES/Makefile.cori2
  src/version.h
Labels: documentation, work_in_progress

#1266 doc: add CMAKE_VERBOSE_MAKEFILE and CXX_COMPILER_LAUNCHER
  cmake/README.md
Labels: cmake

#1265 Update linux linux doc
  doc/src/Install_linux.txt
Labels: documentation

#1239 Bond/react delete atoms
  doc/src/fix_bond_react.txt
  doc/utils/sphinx-config/false_positives.txt
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: enhancement, user_misc_package

#1243 Removed redundant element list from pair_coeff snap syntax
  doc/src/pair_snap.txt
  examples/snap/Mo_Chen_PRM2017.snap
  examples/snap/Mo_Chen_PRM2017.snapcoeff
  examples/snap/Mo_Chen_PRM2017.snapparam
  examples/snap/Ta06A.snap
  examples/snap/Ta06A.snapcoeff
  examples/snap/Ta06A.snapparam
  examples/snap/W_2940_2017_2.snap
  examples/snap/W_2940_2017_2.snapcoeff
  examples/snap/W_2940_2017_2.snapparam
  examples/snap/W_2940_2017_2_He_JW2013.snap
  potentials/Mo_Chen_PRM2017.snap
  potentials/Ta06A.snap
  potentials/Ta06A.snapparam
  potentials/W_2940_2017_2.snap
  potentials/W_2940_2017_2.snapparam
  potentials/W_2940_2017_2_He_JW2013.snap
  src/SNAP/pair_snap.cpp
  src/SNAP/pair_snap.h
Labels: enhancement

#1255 Change fix nvt/sllod to allow suffix styles of fix deform
  src/USER-EFF/fix_nvt_sllod_eff.cpp
  src/USER-INTEL/fix_nvt_sllod_intel.cpp
  src/USER-OMP/fix_nvt_sllod_omp.cpp
  src/fix_nvt_sllod.cpp
Labels: bugfix

#1259 Fix two problems with NPT: volume fluctuations (with iso, previously with aniso/tri) and energy conservation (with aniso/tri)
  src/KOKKOS/fix_nh_kokkos.cpp
  src/fix_nh.cpp
Labels: bugfix, fix_feature

#1262 Addition of extract() method for class2 pair potentials
  src/CLASS2/pair_lj_class2.cpp
  src/CLASS2/pair_lj_class2.h
  src/CLASS2/pair_lj_class2_coul_cut.cpp
  src/CLASS2/pair_lj_class2_coul_cut.h
  src/CLASS2/pair_lj_class2_coul_long.cpp
Labels: enhancement
