Repository lammps/lammps, pull requests merged in 2018-06, with the labels that each got.

#937 Fix issues in Kokkos topology files
  src/CLASS2/angle_class2.h
  src/CLASS2/bond_class2.h
  src/CLASS2/dihedral_class2.h
  src/CLASS2/improper_class2.h
  src/KOKKOS/angle_charmm_kokkos.cpp
  src/KOKKOS/angle_charmm_kokkos.h
  src/KOKKOS/angle_class2_kokkos.cpp
  src/KOKKOS/angle_class2_kokkos.h
  src/KOKKOS/angle_harmonic_kokkos.cpp
  src/KOKKOS/angle_harmonic_kokkos.h
  src/KOKKOS/bond_class2_kokkos.cpp
  src/KOKKOS/bond_class2_kokkos.h
  src/KOKKOS/bond_fene_kokkos.cpp
  src/KOKKOS/bond_fene_kokkos.h
  src/KOKKOS/bond_harmonic_kokkos.cpp
  src/KOKKOS/bond_harmonic_kokkos.h
  src/KOKKOS/dihedral_charmm_kokkos.cpp
  src/KOKKOS/dihedral_charmm_kokkos.h
  src/KOKKOS/dihedral_class2_kokkos.cpp
  src/KOKKOS/dihedral_class2_kokkos.h
  src/KOKKOS/dihedral_opls_kokkos.cpp
  src/KOKKOS/dihedral_opls_kokkos.h
  src/KOKKOS/improper_class2_kokkos.cpp
  src/KOKKOS/improper_class2_kokkos.h
  src/KOKKOS/improper_harmonic_kokkos.cpp
  src/KOKKOS/improper_harmonic_kokkos.h
  src/MOLECULE/angle_charmm.h
  src/MOLECULE/angle_harmonic.h
  src/MOLECULE/bond_fene.h
  src/MOLECULE/bond_harmonic.h
  src/MOLECULE/dihedral_charmm.h
  src/MOLECULE/dihedral_opls.h
  src/MOLECULE/improper_harmonic.h
  src/atom_map.cpp
Labels: bugfix, kokkos_package

#924 miscellaneous CMake Fixes
  cmake/CMakeLists.txt
Labels: cmake

#938 Collected bugfixes and updates
  .github/CODEOWNERS
  doc/Makefile
  doc/src/Section_errors.txt
  doc/src/create_bonds.txt
  doc/src/fix_adapt.txt
  doc/src/molecule.txt
  src/USER-QUIP/pair_quip.cpp
  src/error.cpp
  src/fix_adapt.cpp
  src/molecule.cpp
  src/pair.cpp
  src/pair.h
Labels: bugfix, enhancement

#949 Fix the tail correction with pair_nm
  src/MISC/pair_nm_cut.cpp
  src/MISC/pair_nm_cut_coul_cut.cpp
  src/MISC/pair_nm_cut_coul_long.cpp
Labels: bugfix

#953 Bond/react update
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: enhancement

#952 Add code coverage target to CMake
  cmake/CMakeLists.txt
Labels: build_system, cmake

#943 Improve fix manifoldforce warning
  src/USER-MANIFOLD/fix_manifoldforce.cpp
  src/USER-MANIFOLD/fix_manifoldforce.h
Labels: enhancement

#948 Variable style 'string' substitutes variables in definition
  doc/src/variable.txt
  src/variable.cpp
  src/variable.h
Labels: enhancement

#950 Add support for inline format strings to immediate variable substitution
  doc/src/Section_commands.txt
  src/input.cpp
Labels: enhancement

#933 Limit atom energy change in fix dt/reset
  doc/src/fix_dt_reset.txt
  src/fix_dt_reset.cpp
  src/fix_dt_reset.h
Labels: enhancement

#955 cmake: implicit fortran libs need to linked last
  cmake/CMakeLists.txt
Labels: build_system, cmake

#957 Collected small changes and bugfixes for next patch release
  potentials/ffield.reax.lg
  src/USER-MISC/fix_smd.cpp
  src/USER-REAXC/reaxc_ffield.cpp
Labels: bugfix

#959 Expand cmake documentation
  cmake/README.md
Labels: cmake, documentation, needs_work

#960 made latte.in compatible with v1.1.1 and updated log files
  doc/src/Section_commands.txt
  doc/src/fix_dt_reset.txt
  doc/src/variable.txt
  examples/latte/in.latte.water.min
  examples/latte/latte.in
  examples/latte/log.19Sep17.latte.sucrose.g++.1
  examples/latte/log.19Sep17.latte.water.g++.1
  examples/latte/log.19Sep17.latte.water.min.g++.1
  examples/latte/log.21Jun18.latte.graphene.boxrelax.g++.1
  examples/latte/log.21Jun18.latte.sucrose.g++.1
  examples/latte/log.21Jun18.latte.water.g++.1
  examples/latte/log.21Jun18.latte.water.min.g++.1
  src/input.cpp
Labels: documentation, enhancement

#968 New paramteters for potential #839
  doc/src/pair_ilp_graphene_hbn.txt
  doc/src/pair_kolmogorov_crespi_full.txt
  potentials/BNCH.ILP
  potentials/CH.KC
Labels: documentation, enhancement

#925 Pair entropy fingerprint
  doc/src/Eqs/pair_entropy.jpg
  doc/src/Eqs/pair_entropy.tex
  doc/src/Eqs/pair_entropy2.jpg
  doc/src/Eqs/pair_entropy2.tex
  doc/src/Eqs/pair_entropy3.jpg
  doc/src/Eqs/pair_entropy3.tex
  doc/src/Section_commands.txt
  doc/src/compute_entropy_atom.txt
  doc/src/computes.txt
  doc/src/lammps.book
  examples/USER/misc/entropy/Na_MendelevM_2014.eam.fs
  examples/USER/misc/entropy/data.interface
  examples/USER/misc/entropy/in.entropy
  examples/USER/misc/entropy/log.entropy
  src/USER-MISC/README
  src/USER-MISC/compute_entropy_atom.cpp
  src/USER-MISC/compute_entropy_atom.h
Labels: enhancement, user_misc_package

#966 Intel Package: Bug fix when using LRT with minimize and for virial calculation with GNU...
  src/USER-INTEL/fix_intel.h
  src/USER-INTEL/intel_preprocess.h
  src/USER-INTEL/npair_full_bin_ghost_intel.cpp
  src/USER-INTEL/npair_intel.cpp
  src/USER-INTEL/pair_buck_coul_cut_intel.cpp
  src/USER-INTEL/pair_buck_coul_long_intel.cpp
  src/USER-INTEL/pair_buck_intel.cpp
  src/USER-INTEL/pair_dpd_intel.cpp
  src/USER-INTEL/pair_eam_intel.cpp
  src/USER-INTEL/pair_gayberne_intel.cpp
  src/USER-INTEL/pair_lj_charmm_coul_charmm_intel.cpp
  src/USER-INTEL/pair_lj_charmm_coul_long_intel.cpp
  src/USER-INTEL/pair_lj_cut_coul_long_intel.cpp
  src/USER-INTEL/pair_lj_cut_intel.cpp
  src/USER-INTEL/pair_sw_intel.cpp
  src/USER-INTEL/pair_tersoff_intel.cpp
  src/USER-INTEL/verlet_lrt_intel.cpp
  src/USER-INTEL/verlet_lrt_intel.h
Labels: bugfix, enhancement, user_intel_package

#970 Bond/react: edge IDs optional
  src/USER-MISC/fix_bond_react.cpp
Labels: enhancement

#976 Collected cmake changes
  README
  cmake/CMakeLists.txt
  cmake/Modules/StyleHeaderUtils.cmake
  cmake/README.md
  cmake/pkgconfig/liblammps.pc.in
  cmake/presets/all_off.cmake
  cmake/presets/all_on.cmake
  cmake/presets/manual_selection.cmake
  cmake/presets/nolib.cmake
  cmake/presets/std.cmake
  cmake/presets/std_nolib.cmake
  cmake/presets/user.cmake
  python/lammps.py
  src/.gitignore
  src/Makefile
  src/Purge.list
  src/info.cpp
  src/info.h
  src/lammps.cpp
  src/lammps.h
  src/library.cpp
  src/library.h
Labels: build_system, cmake, enhancement

#978 new ARM makefiles, also some doc tweaks
  doc/src/Section_howto.txt
  doc/src/atom_style.txt
  doc/src/fix_rigid.txt
  src/MAKE/MACHINES/Makefile.aarch64_arm_openmpi_armpl
  src/MAKE/MACHINES/Makefile.aarch64_arm_serial_armpl
  src/MAKE/MACHINES/Makefile.aarch64_g++_openmpi_armpl
  src/MAKE/MACHINES/Makefile.aarch64_g++_serial_armpl
  src/dump_custom.cpp
Labels: build_system, documentation

#977 Collected small changes for the next patch release
  cmake/CMakeLists.txt
  doc/src/dump_modify.txt
  src/LATTE/fix_latte.cpp
  src/USER-MISC/compute_entropy_atom.cpp
  src/USER-MISC/compute_entropy_atom.h
Labels: documentation, user_misc_package

#979 Fixes issue #975
  src/PYTHON/python_impl.cpp
Labels: bugfix, python_module
