Repository lammps/lammps, pull requests merged in 2018-05, with the labels that each got.

#883 Fixes to Colvars library (version 2018-04-29)
  doc/src/PDF/colvars-refman-lammps.pdf
  lib/colvars/colvar.cpp
  lib/colvars/colvar.h
  lib/colvars/colvaratoms.cpp
  lib/colvars/colvaratoms.h
  lib/colvars/colvarbias_abf.cpp
  lib/colvars/colvarcomp.cpp
  lib/colvars/colvarcomp.h
  lib/colvars/colvarcomp_distances.cpp
  lib/colvars/colvarcomp_rotations.cpp
  lib/colvars/colvardeps.cpp
  lib/colvars/colvargrid.cpp
  lib/colvars/colvarmodule.cpp
  lib/colvars/colvarmodule.h
  lib/colvars/colvarproxy.cpp
  lib/colvars/colvarproxy.h
  lib/colvars/colvars_version.h
  lib/colvars/colvartypes.h
  src/USER-COLVARS/colvarproxy_lammps.cpp
  src/USER-COLVARS/colvarproxy_lammps.h
  src/USER-COLVARS/colvarproxy_lammps_version.h
Labels: user_colvars_package

#875 Collected small changes and bug fixes for the next patch release
  doc/src/compute_displace_atom.txt
  doc/src/fix_reax_bonds.txt
  python/lammps.py
  src/MOLECULE/angle_cosine_squared.cpp
  src/MOLECULE/angle_harmonic.cpp
  src/MOLECULE/dihedral_helix.cpp
  src/MOLECULE/dihedral_helix.h
  src/MOLECULE/dihedral_multi_harmonic.cpp
  src/MOLECULE/dihedral_multi_harmonic.h
  src/USER-MISC/angle_cosine_shift.cpp
  src/USER-MISC/angle_cosine_shift_exp.cpp
  src/USER-MISC/angle_dipole.cpp
  src/USER-MISC/angle_fourier.cpp
  src/USER-MISC/angle_fourier_simple.cpp
  src/USER-MISC/dihedral_cosine_shift_exp.cpp
  src/USER-MISC/dihedral_cosine_shift_exp.h
  src/USER-MISC/dihedral_quadratic.cpp
  src/USER-MISC/dihedral_quadratic.h
  src/USER-MISC/improper_cossq.cpp
  src/USER-MISC/improper_cossq.h
  src/USER-MISC/improper_distance.cpp
  src/USER-MISC/improper_distance.h
  src/USER-MISC/improper_fourier.cpp
  src/USER-MISC/improper_fourier.h
  src/USER-MISC/improper_ring.cpp
  src/USER-MISC/improper_ring.h
  src/USER-MISC/pair_coul_shield.cpp
  src/USER-MISC/pair_ilp_graphene_hbn.cpp
  src/USER-MISC/pair_kolmogorov_crespi_full.cpp
  src/fix_restrain.cpp
  src/library.cpp
Labels: bugfix, enhancement, user_misc_package

#879 USER-BOCS
  cmake/CMakeLists.txt
  doc/src/Section_packages.txt
  doc/src/fix_bocs.txt
  doc/src/fixes.txt
  doc/src/lammps.book
  examples/USER/bocs/README
  examples/USER/bocs/in.methanol
  examples/USER/bocs/lammps_nb_MET-MET.table
  examples/USER/bocs/log.20Apr18.methanol.g++.1
  examples/USER/bocs/log.20Apr18.methanol.g++.4
  examples/USER/bocs/methanol.data
  src/Makefile
  src/USER-BOCS/README
  src/USER-BOCS/compute_pressure_bocs.cpp
  src/USER-BOCS/compute_pressure_bocs.h
  src/USER-BOCS/fix_bocs.cpp
  src/USER-BOCS/fix_bocs.h
Labels: enhancement

#887 Fix bug in create_bonds single/bond
  src/create_bonds.cpp
Labels: bugfix

#890 bond/react final touches
  doc/src/fix_bond_react.txt
  examples/USER/misc/bond_react/nylon,6-6_melt/in.large_nylon_melt
  examples/USER/misc/bond_react/nylon,6-6_melt/log.20Apr18.large_nylon_melt.g++.1
  examples/USER/misc/bond_react/nylon,6-6_melt/log.20Apr18.large_nylon_melt.g++.4
  examples/USER/misc/bond_react/tiny_nylon/in.tiny_nylon
  examples/USER/misc/bond_react/tiny_nylon/log.20Apr18.tiny_nylon.g++.1
  examples/USER/misc/bond_react/tiny_nylon/log.20Apr18.tiny_nylon.g++.4
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: bugfix, enhancement

#889 Collected changes to restore C++ standard compliance
  src/GPU/gpu_extra.h
  src/KIM/pair_kim.cpp
  src/KSPACE/msm.cpp
  src/MANYBODY/pair_comb3.cpp
  src/MC/fix_gcmc.cpp
  src/PYTHON/fix_python_move.cpp
  src/REPLICA/neb.cpp
  src/RIGID/fix_rigid.cpp
  src/USER-DPD/fix_rx.cpp
  src/USER-DRUDE/fix_drude_transform.cpp
  src/USER-LB/fix_lb_momentum.cpp
  src/USER-MEAMC/meam.h
  src/USER-MESO/pair_edpd.cpp
  src/USER-MESO/pair_tdpd.cpp
  src/USER-MISC/compute_basal_atom.cpp
  src/USER-MISC/fix_filter_corotate.cpp
  src/USER-MISC/fix_gle.cpp
  src/USER-MISC/fix_ipi.cpp
  src/USER-MISC/pair_lj_sf_dipole_sf.cpp
  src/USER-PHONON/fix_phonon.cpp
  src/USER-SMD/fix_smd_integrate_ulsph.h
  src/USER-UEF/fix_nh_uef.h
  src/image.cpp
  src/library.cpp
  src/molecule.cpp
Labels: bugfix

#891 Collected small changes, fixes and updates
  .github/CODEOWNERS
  doc/src/compute_ackland_atom.txt
  doc/src/fix_langevin_drude.txt
  doc/src/fix_restrain.txt
  doc/src/pair_kolmogorov_crespi_z.txt
  lib/colvars/Makefile.deps
  lib/colvars/colvarcomp.cpp
  lib/latte/.gitignore
  lib/vtk/Makefile.lammps.fedora28_vtk7
  src/.gitignore
  src/Depend.sh
  src/MSCG/fix_mscg.cpp
  src/Makefile
  src/USER-CGDNA/bond_oxdna_fene.cpp
  src/USER-CGDNA/pair_oxdna2_coaxstk.cpp
  src/USER-CGDNA/pair_oxdna2_dh.cpp
  src/USER-CGDNA/pair_oxdna_coaxstk.cpp
  src/USER-CGDNA/pair_oxdna_excv.cpp
  src/USER-CGDNA/pair_oxdna_hbond.cpp
  src/USER-CGDNA/pair_oxdna_xstk.cpp
  src/USER-INTEL/Install.sh
  src/USER-INTEL/dihedral_opls_intel.cpp
  src/USER-MISC/compute_ackland_atom.cpp
  src/USER-MISC/compute_ackland_atom.h
  src/USER-PHONON/Install.sh
  src/USER-QUIP/pair_quip.cpp
  src/fix_restrain.cpp
  src/fix_restrain.h
Labels: documentation, enhancement

#634 Computation of forces/torques on rigid bodies moved to post_force
  doc/src/fix_modify.txt
  doc/src/fix_poems.txt
  doc/src/fix_rigid.txt
  examples/rigid/in.rigid.atomfile
  examples/rigid/in.rigid.atomvar
  examples/rigid/in.rigid.early
  examples/rigid/in.rigid.nve
  examples/rigid/in.rigid.nve.early
  examples/rigid/in.rigid.property
  examples/rigid/log.20Apr18.rigid.atomfile.g++.1
  examples/rigid/log.20Apr18.rigid.atomfile.g++.4
  examples/rigid/log.20Apr18.rigid.atomvar.g++.1
  examples/rigid/log.20Apr18.rigid.atomvar.g++.4
  examples/rigid/log.20Apr18.rigid.early.g++.1
  examples/rigid/log.20Apr18.rigid.early.g++.4
  examples/rigid/log.20Apr18.rigid.g++.1
  examples/rigid/log.20Apr18.rigid.g++.4
  examples/rigid/log.20Apr18.rigid.nve.early.g++.1
  examples/rigid/log.20Apr18.rigid.nve.early.g++.4
  examples/rigid/log.20Apr18.rigid.nve.g++.1
  examples/rigid/log.20Apr18.rigid.nve.g++.4
  examples/rigid/log.20Apr18.rigid.poems.g++.1
  examples/rigid/log.20Apr18.rigid.poems.g++.4
  examples/rigid/log.20Apr18.rigid.poems2.g++.1
  examples/rigid/log.20Apr18.rigid.poems2.g++.4
  examples/rigid/log.20Apr18.rigid.property.g++.1
  examples/rigid/log.20Apr18.rigid.property.g++.4
  examples/rigid/log.20Apr18.rigid.tnr.g++.1
  examples/rigid/log.20Apr18.rigid.tnr.g++.4
  examples/rigid/log.5Oct16.rigid.poems.g++.1
  examples/rigid/log.5Oct16.rigid.poems.g++.4
  examples/rigid/log.5Oct16.rigid.poems2.g++.1
  examples/rigid/log.5Oct16.rigid.poems2.g++.4
  examples/rigid/log.5Oct16.rigid.tnr.g++.1
  examples/rigid/log.5Oct16.rigid.tnr.g++.4
  src/POEMS/fix_poems.cpp
  src/POEMS/fix_poems.h
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid.h
  src/RIGID/fix_rigid_nh.cpp
  src/RIGID/fix_rigid_nh_small.cpp
  src/RIGID/fix_rigid_small.cpp
  src/RIGID/fix_rigid_small.h
  src/USER-OMP/fix_rigid_nh_omp.cpp
  src/USER-OMP/fix_rigid_nh_omp.h
  src/USER-OMP/fix_rigid_omp.cpp
  src/USER-OMP/fix_rigid_omp.h
  src/USER-OMP/fix_rigid_small_omp.cpp
  src/USER-OMP/fix_rigid_small_omp.h
Labels: enhancement, rigid_package

#894 More fixes to conform with C++ standards as indicated by Clang
  src/USER-INTEL/intel_buffers.cpp
  src/USER-MESO/fix_edpd_source.cpp
  src/USER-MESO/fix_tdpd_source.cpp
Labels: bugfix

#880 Remove Kokkos deprecated code
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/pair_dpd_fdt_energy_kokkos.cpp
  src/KOKKOS/pair_exp6_rx_kokkos.cpp
  src/KOKKOS/rand_pool_wrap_kokkos.h
Labels: enhancement, kokkos_package

#898 Output individual energies in fix restrain
  doc/src/fix_restrain.txt
  src/fix_restrain.cpp
  src/fix_restrain.h
Labels: enhancement

#904 Retyping parameters bugfix
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix, user_misc_package

#908 Correct small bugs found by static code analysis
  src/POEMS/fix_poems.cpp
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid_small.cpp
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix

#909 new dihedral table/cut command
  doc/src/Eqs/dihedral_table_cut.jpg
  doc/src/Eqs/dihedral_table_cut.tex
  doc/src/Section_commands.txt
  doc/src/dihedral_table_cut.txt
  doc/src/dihedrals.txt
  doc/src/lammps.book
  src/.gitignore
  src/USER-MISC/README
  src/USER-MISC/dihedral_table_cut.cpp
  src/USER-MISC/dihedral_table_cut.h
Labels: enhancement, user_misc_package

#907 Implement 'dump_modify maxfiles' feature
  doc/src/dump_modify.txt
  lib/atc/Function.cpp
  src/COMPRESS/dump_atom_gz.cpp
  src/COMPRESS/dump_cfg_gz.cpp
  src/COMPRESS/dump_custom_gz.cpp
  src/COMPRESS/dump_xyz_gz.cpp
  src/MPIIO/dump_atom_mpiio.cpp
  src/MPIIO/dump_cfg_mpiio.cpp
  src/MPIIO/dump_custom_mpiio.cpp
  src/MPIIO/dump_xyz_mpiio.cpp
  src/dump.cpp
  src/dump.h
  src/dump_custom.cpp
Labels: dump_feature, enhancement

#910 USER-INTEL: enforce icc and add icc flags
  cmake/CMakeLists.txt
Labels: cmake

#913 Bond/react doc reformat
  doc/src/fix_bond_react.txt
Labels: documentation

#914 smooth restarts with bond/react
  src/USER-MISC/fix_bond_react.cpp
Labels: enhancement, user_misc_package

#901 USER-DPD: bugfix for AtomVecDPD::unpack_restart() and the Kokkos version
  src/KOKKOS/atom_vec_dpd_kokkos.cpp
  src/USER-DPD/atom_vec_dpd.cpp
Labels: bugfix, kokkos_package, user_dpd_package

#918 Fix performance regression in KOKKOS package
  lib/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
Labels: bugfix, kokkos_package

#921 tweaks to doc pages
  doc/src/pair_gw.txt
  doc/src/pair_reaxc.txt
  doc/src/pair_sw.txt
Labels: documentation

#911 Collected small changes and bugfixes
  examples/COUPLE/lammps_quest/lmpqst.cpp
  examples/COUPLE/lammps_spparks/lmpspk.cpp
  examples/COUPLE/library/error.cpp
  examples/COUPLE/library/files.cpp
  examples/COUPLE/library/irregular.cpp
  examples/COUPLE/library/lammps_data_write.cpp
  examples/COUPLE/library/lammps_data_write.h
  examples/COUPLE/library/many2many.cpp
  examples/COUPLE/library/many2one.cpp
  examples/COUPLE/library/memory.cpp
  examples/COUPLE/library/one2many.cpp
  examples/COUPLE/library/send2one.cpp
  examples/COUPLE/multiple/multiple.cpp
  examples/COUPLE/simple/simple.cpp
  lib/atc/Function.cpp
  src/compute_rdf.cpp
Labels: bugfix

#929 Small bugfixes for Pair Snap
  src/SNAP/pair_snap.cpp
  src/SNAP/pair_snap.h
Labels: bugfix, kokkos_package
