Repository lammps/lammps, pull requests merged in 2018-08, with the labels that each got.

#1030 Collected small fixes for the next patch release
  doc/src/Section_howto.txt
  doc/src/fixes.txt
  doc/src/pairs.txt
  examples/USER/diffraction/BulkNi.in
  src/MANYBODY/pair_eam_cd.h
  src/Purge.list
Labels: bugfix, build_system, work_in_progress

#942 Fix discrepancies between fix_nh and papers
  src/KOKKOS/fix_nh_kokkos.cpp
  src/USER-BOCS/fix_bocs.cpp
  src/fix_nh.cpp
Labels: enhancement

#1031 Allow cross-compiling from linux to windows with cmake
  cmake/CMakeLists.txt
Labels: cmake

#994 USER-UEF support for image flags
  src/USER-UEF/fix_nh_uef.cpp
  src/USER-UEF/uef_utils.cpp
  src/USER-UEF/uef_utils.h
Labels: bugfix, enhancement

#1040 enable more correct natoms computation when atoms are lost
  src/fix_group.cpp
  src/group.cpp
  src/group.h
  src/thermo.cpp
Labels: bugfix, enhancement

#1041 Add extra check for OpenCL timers
  lib/gpu/geryon/ocl_timer.h
Labels: bugfix, gpu_package

#1038 KOKKOS Package bugfix: Workaround for issue #1037
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_View.hpp
Labels: bugfix, kokkos_package

#1043 bug fix for compute cluster/atom when computing values used to update…
  src/compute_cluster_atom.cpp
  src/fix_group.cpp
  src/update.cpp
  src/update.h
Labels: bugfix, enhancement

#1042 Kokkos vs gpu direct
  doc/src/Speed_kokkos.txt
  doc/src/package.txt
  src/KOKKOS/comm_kokkos.cpp
  src/KOKKOS/gridcomm_kokkos.cpp
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
Labels: kokkos_package

#928 Fix rcb balance issue
  doc/src/compute_property_local.txt
  src/balance.cpp
  src/rcb.cpp
Labels: bugfix

#1046 Replace deprecated CUDA functions calls in GPU package
  lib/gpu/geryon/nvd_device.h
  lib/gpu/lal_preprocessor.h
Labels: gpu_package

#1050 Generate Position Independent Code in ExternalProject Voro when necessary
  cmake/CMakeLists.txt
Labels: bugfix, cmake

#1055 favor qsort over mergesort for stable release
  src/lmptype.h
Labels: bugfix

#1057 cmake: convert FFT and INTEL_ARCH
  cmake/CMakeLists.txt
Labels: cmake

#1056 tweaks to Manual formatting
  doc/src/Build.txt
  doc/src/Build_extras.txt
  doc/src/Build_package.txt
  doc/src/Intro_authors.txt
  doc/src/Manual.txt
  doc/src/Speed.txt
Labels: documentation

#1059 Add missing source file for KOKKOS with KSPACE
  cmake/CMakeLists.txt
Labels: bugfix, cmake

#1060 Rename Run.txt to Run_head.txt to avoid file name clash on OSX
  doc/src/Build.txt
  doc/src/Commands.txt
  doc/src/Manual.txt
  doc/src/Run_basics.txt
  doc/src/Run_head.txt
  doc/src/Run_options.txt
  doc/src/Run_output.txt
  doc/src/Run_windows.txt
  doc/src/lammps.book
Labels: documentation

#1061 doc typos and push author details back to website
  README
  doc/src/Build_cmake.txt
  doc/src/Build_extras.txt
  doc/src/Build_package.txt
  doc/src/Howto_diffusion.txt
  doc/src/Howto_dispersion.txt
  doc/src/Howto_temperature.txt
  doc/src/Intro_authors.txt
Labels: documentation

#1063 Fix some documentation issues
  doc/src/Manual_build.txt
  doc/src/Packages_details.txt
  doc/src/Packages_standard.txt
  doc/src/Packages_user.txt
  doc/src/Speed_compare.txt
  src/USER-COLVARS/fix_colvars.h
Labels: bugfix, documentation, enhancement

#1064 cmake: required v3.7 for some DOWNLOAD options
  cmake/CMakeLists.txt
Labels: cmake

#1065 add a needed ifort flag for LAMMPS/LATTE link
  lib/latte/Makefile.lammps.ifort
Labels: build_system

#1062 change format of Howto and Tools doc pages
  doc/src/Howto.txt
  doc/src/Manual.txt
  doc/src/Tools.txt
Labels: documentation

#1066 minor tweak to docs
  doc/src/Speed_gpu.txt
Labels: documentation

#1070 Fixes issue #1069
  python/lammps.py
Labels: bugfix, python_module

#1067 Bond/react: better template validity checks
  doc/src/fix_bond_react.txt
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix

#1071 Doc updates for release
  doc/src/Build.txt
  doc/src/Build_windows.txt
  doc/src/compute_pair.txt
  doc/src/lammps.book
Labels: documentation

#1081 cmake: sort package in header
  cmake/CMakeLists.txt
  cmake/Modules/StyleHeaderUtils.cmake
Labels: cmake

#1083 cmake: fix install of potential files
  cmake/CMakeLists.txt
Labels: cmake

#987 Added Axilrod-Teller manybody potential
  doc/src/Commands_pair.txt
  doc/src/Eqs/pair_atm.jpg
  doc/src/Eqs/pair_atm.tex
  doc/src/JPG/pair_atm_dia.jpg
  doc/src/lammps.book
  doc/src/pair_atm.txt
  doc/src/pair_style.txt
  doc/src/pairs.txt
  examples/README
  examples/atm/in.atm
  examples/atm/log.27Aug18.g++.1
  examples/atm/log.27Aug18.g++.4
  src/MANYBODY/pair_atm.cpp
  src/MANYBODY/pair_atm.h
Labels: enhancement, manybody_package

#1078 added manpage from debian package
  cmake/CMakeLists.txt
  doc/lammps.1
Labels: cmake, documentation

#1082 Bond/react: treatment of simultaneous competing reactions
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix

#1085 Silence USER-CGSD warnings
  src/USER-CGSDK/lj_sdk_common.h
  src/USER-CGSDK/pair_lj_sdk.cpp
  src/USER-CGSDK/pair_lj_sdk_coul_long.cpp
Labels: enhancement

#1086 cmake: add FindLAMMPS.cmake.in
  cmake/CMakeLists.txt
  cmake/FindLAMMPS.cmake.in
  cmake/pkgconfig/liblammps.pc.in
Labels: cmake
