Repository lammps/lammps, pull requests merged in 2018-09, with the labels that each got.

#1088 liblammps.pc: add lammps version
  cmake/pkgconfig/liblammps.pc.in
Labels: cmake

#1091 Collected diverse small changes
  examples/USER/diffraction/BulkNi.in
  examples/USER/diffraction/Output/BulkNi.in
  src/domain.cpp
  src/domain.h
  src/fix_tmd.cpp
  src/library.cpp
Labels: enhancement

#1095 Add core tests to CMake
  cmake/CMakeLists.txt
Labels: cmake, enhancement

#1098 cmake: only add tests if exe is build
  cmake/CMakeLists.txt
Labels: build_system, cmake

#1093 Collection of CMake fixes
  cmake/CMakeLists.txt
Labels: bugfix, cmake

#1051 Add data duplication option to the KOKKOS package
  doc/src/Speed_kokkos.txt
  src/KOKKOS/fix_qeq_reax_kokkos.cpp
  src/KOKKOS/fix_qeq_reax_kokkos.h
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/kokkos_type.h
  src/KOKKOS/neigh_list_kokkos.h
  src/KOKKOS/pair_eam_alloy_kokkos.cpp
  src/KOKKOS/pair_eam_alloy_kokkos.h
  src/KOKKOS/pair_eam_fs_kokkos.cpp
  src/KOKKOS/pair_eam_fs_kokkos.h
  src/KOKKOS/pair_eam_kokkos.cpp
  src/KOKKOS/pair_eam_kokkos.h
  src/KOKKOS/pair_kokkos.h
  src/KOKKOS/pair_reaxc_kokkos.cpp
  src/KOKKOS/pair_reaxc_kokkos.h
  src/KOKKOS/pair_snap_kokkos.h
  src/KOKKOS/pair_snap_kokkos_impl.h
  src/KOKKOS/pair_sw_kokkos.cpp
  src/KOKKOS/pair_sw_kokkos.h
  src/KOKKOS/pair_table_kokkos.cpp
  src/KOKKOS/pair_tersoff_kokkos.cpp
  src/KOKKOS/pair_tersoff_kokkos.h
  src/KOKKOS/pair_tersoff_mod_kokkos.cpp
  src/KOKKOS/pair_tersoff_mod_kokkos.h
  src/KOKKOS/pair_tersoff_zbl_kokkos.cpp
  src/KOKKOS/pair_tersoff_zbl_kokkos.h
Labels: enhancement, kokkos_package

#1103 cmake: add missing fix_omp.h and fix_omp.cpp to compilation
  cmake/CMakeLists.txt
  cmake/Modules/StyleHeaderUtils.cmake
Labels: bugfix, cmake, test-for-regression

#1113 Expand the list of code owners for more automated review requests
  .github/CODEOWNERS
Labels: enhancement

#1100 Avoid unnecessary sorting in print_columns
  src/info.cpp
Labels: enhancement

#1101 Bugfix pair morse smooth linear
  src/USER-MISC/pair_morse_smooth_linear.cpp
Labels: bugfix, user_misc_package

#1105 Avoid buffer overflow during errors with long filenames
  src/error.cpp
Labels: bugfix

#1115 cmake: fix globbing of emacs files
  cmake/CMakeLists.txt
  cmake/Modules/StyleHeaderUtils.cmake
Labels: build_system, cmake

#1114 cmake: fix Eigen3 detection
  cmake/CMakeLists.txt
Labels: build_system, cmake

#1112 Rename files for pair style eam/cd/omp in USER-OMP
  src/Purge.list
  src/USER-OMP/pair_eam_cd_omp.cpp
  src/USER-OMP/pair_eam_cd_omp.h
Labels: bugfix, user_omp_package

#1097 add variable option to compute bond/angle/dihedral local
  doc/src/compute_angle_local.txt
  doc/src/compute_bond_local.txt
  doc/src/compute_dihedral_local.txt
  src/compute_angle_local.cpp
  src/compute_angle_local.h
  src/compute_bond_local.cpp
  src/compute_bond_local.h
  src/compute_dihedral_local.cpp
  src/compute_dihedral_local.h
Labels: enhancement

#1099 bond/react: efficient competing reactions
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
  src/comm.h
  src/comm_brick.cpp
  src/comm_brick.h
Labels: enhancement

#1092 new stress/mop and stress/mop/profile computes for USER-MISC
  doc/src/compute_stress_mop.txt
  doc/src/computes.txt
  doc/src/lammps.book
  examples/USER/misc/mop/data.mop
  examples/USER/misc/mop/in.compute_stress_mop
  examples/USER/misc/mop/log.5Sep18.compute_stress_mop.g++.1
  examples/USER/misc/mop/log.5Sep18.compute_stress_mop.g++.4
  examples/USER/misc/mop/moppz.time.reference
  examples/USER/misc/mop/mopz0.time.reference
  src/.gitignore
  src/USER-MISC/README
  src/USER-MISC/compute_stress_mop.cpp
  src/USER-MISC/compute_stress_mop.h
  src/USER-MISC/compute_stress_mop_profile.cpp
  src/USER-MISC/compute_stress_mop_profile.h
Labels: enhancement

#1119 doc page clarifications
  doc/src/Howto_nemd.txt
  doc/src/Howto_thermostat.txt
  doc/src/Howto_viscosity.txt
  doc/src/fix_box_relax.txt
  doc/src/fix_nvt_sllod.txt
  doc/src/fix_shake.txt
  doc/src/minimize.txt
Labels: documentation, enhancement

#1125 The sna*/atom computes were not destroying SNA objects. Fixed.
  src/SNAP/compute_sna_atom.cpp
  src/SNAP/compute_sna_atom.h
  src/SNAP/compute_snad_atom.cpp
  src/SNAP/compute_snad_atom.h
  src/SNAP/compute_snav_atom.cpp
  src/SNAP/compute_snav_atom.h
Labels: bugfix

#1127 fix typo in gzip support for fix reax/bonds
  src/REAX/fix_reax_bonds.cpp
Labels: bugfix

#1128 Warn more loudly about REAX and MEAM going away soon
  src/MEAM/pair_meam.cpp
  src/REAX/pair_reax.cpp
Labels: enhancement

#1132 Small fixes to MEAM/C
  src/USER-MEAMC/meam_dens_init.cpp
  src/USER-MEAMC/meam_funcs.cpp
  src/USER-MEAMC/meam_impl.cpp
  src/USER-MEAMC/pair_meamc.cpp
Labels: enhancement
