Repository lammps/lammps, pull requests merged in 2019-11, with the labels that each got.

#1756 Correct warning issue in min_cg.cpp
  src/SPIN/min_spin.cpp
  src/SPIN/min_spin_cg.cpp
  src/SPIN/min_spin_lbfgs.cpp
  src/min_cg.cpp
  src/min_fire.cpp
  src/min_quickmin.cpp
  src/min_sd.cpp
Labels: bugfix, maintenance

#1758 wrong cmake option for QUIP
  doc/rst/Build_extras.rst
Labels: bugfix, cmake

#1759 Consistent exclusion settings with multiple kspace-like sub-styles in pair hybrid
  src/neighbor.cpp
  src/pair_hybrid.h
Labels: bugfix

#1762 Add LAMMPSLexer for LAMMPS code-blocks in docs
  doc/src/Commands_input.rst
  doc/src/Commands_parse.rst
  doc/src/Howto_pylammps.rst
  doc/src/Manual_build.rst
  doc/txt/Commands_input.txt
  doc/txt/Commands_parse.txt
  doc/txt/Howto_pylammps.txt
  doc/txt/Manual_build.txt
  doc/utils/sphinx-config/LAMMPSLexer.py
  doc/utils/sphinx-config/conf.py
Labels: documentation, enhancement

#1765 Doc Fixes
  doc/Makefile
  doc/txt/computes.txt
  doc/txt/impropers.txt
Labels: documentation

#1763 add documention to FixPour::outside(), simplify logic a bit
  src/GRANULAR/fix_pour.cpp
Labels: maintenance

#1766 Compute hma doc
  doc/src/Commands_compute.rst
  doc/txt/Commands_compute.txt
Labels: documentation

#1764 Add a max and min option to fix_gcmc
  doc/src/fix_gcmc.rst
  doc/txt/fix_gcmc.txt
  src/MC/fix_gcmc.cpp
  src/MC/fix_gcmc.h
Labels: documentation, enhancement, mc_package

#1767 Patch of class2 dihedral
  src/CLASS2/dihedral_class2.cpp
Labels: class2_package, maintenance

#1768 Add Install_conda doc
  doc/src/Install.rst
  doc/src/Install_conda.rst
  doc/src/Install_mac.rst
  doc/txt/Install.txt
  doc/txt/Install_mac.txt
  doc/utils/sphinx-config/false_positives.txt
Labels: documentation

#1740 Fix print patch to allow print on rerun
  src/fix_print.cpp
  src/fix_print.h
Labels: bugfix

#1782 Last minute bugfix for the upcoming patch release
  src/USER-OMP/pair_lj_cut_tip4p_long_omp.cpp
  src/pair.cpp
Labels: bugfix

#1777 Step version strings for next patch release
  doc/lammps.1
  src/version.h
Labels: maintenance

#1789 Patch 2
  doc/src/Howto_pylammps.rst
  doc/src/pair_agni.rst
  doc/txt/compute_heat_flux.txt
  doc/txt/pair_agni.txt
  src/USER-INTEL/intel_intrinsics.h
  src/USER-MISC/pair_agni.cpp
Labels: documentation, ready_for_merge
