Repository lammps/lammps, pull requests merged in 2019-10, with the labels that each got.

#1697 Bond/react: angle constraints
  doc/src/fix_bond_react.txt
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: enhancement, user_misc_package

#1692 Bug correction in the SPIN package, and fix nve/spin option modification
  doc/src/fix_langevin_spin.txt
  doc/src/fix_nve_spin.txt
  examples/SPIN/bfo/in.spin.bfo
  examples/SPIN/cobalt_fcc/in.spin.cobalt_fcc
  examples/SPIN/cobalt_hcp/in.spin.cobalt_hcp
  examples/SPIN/dipole_spin/in.spin.iron_dipole_cut
  examples/SPIN/dipole_spin/in.spin.iron_dipole_ewald
  examples/SPIN/dipole_spin/in.spin.iron_dipole_pppm
  examples/SPIN/iron/in.spin.iron
  examples/SPIN/iron/in.spin.iron_cubic
  examples/SPIN/nickel/in.spin.nickel
  examples/SPIN/nickel/in.spin.nickel_cubic
  examples/SPIN/read_restart/in.spin.read_data
  examples/SPIN/read_restart/in.spin.restart
  examples/SPIN/read_restart/in.spin.write_restart
  examples/SPIN/setforce_spin/in.spinmin.setforce
  src/SPIN/fix_nve_spin.cpp
  src/SPIN/pair_spin_exchange.cpp
  src/SPIN/pair_spin_neel.cpp
Labels: bugfix, documentation, spin_package

#1673 Lammps gjf
  doc/src/Errors_messages.txt
  doc/src/Errors_warnings.txt
  doc/src/fix_langevin.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/gjf/README.md
  examples/gjf/argon.lmp
  examples/gjf/ff-argon.lmp
  examples/gjf/in.gjf.vfull
  examples/gjf/in.gjf.vhalf
  src/KOKKOS/fix_langevin_kokkos.cpp
  src/KOKKOS/fix_langevin_kokkos.h
  src/fix_langevin.cpp
  src/fix_langevin.h
Labels: enhancement

#1701 Fixed error in neighbor distance check for box dimensions
  src/neighbor.cpp
Labels: bugfix, neighborlist_feature

#1598 Adding the conjugate gradient algorithm and L-BFGS to the SPIN package
  doc/src/Eqs/norm_inf.jpg
  doc/src/Eqs/norm_inf.tex
  doc/src/Eqs/norm_max.jpg
  doc/src/Eqs/norm_max.tex
  doc/src/Eqs/norm_two.jpg
  doc/src/Eqs/norm_two.tex
  doc/src/min_modify.txt
  doc/src/min_spin.txt
  doc/src/min_style.txt
  doc/src/minimize.txt
  doc/src/neb_spin.txt
  doc/src/pair_spin_dipole.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/SPIN/spinmin/in.spinmin_cg.bfo
  examples/SPIN/spinmin/in.spinmin_lbfgs.bfo
  src/.gitignore
  src/SPIN/fix_nve_spin.h
  src/SPIN/min_spin.cpp
  src/SPIN/min_spin.h
  src/SPIN/min_spin_cg.cpp
  src/SPIN/min_spin_cg.h
  src/SPIN/min_spin_lbfgs.cpp
  src/SPIN/min_spin_lbfgs.h
  src/SPIN/neb_spin.cpp
  src/SPIN/pair_spin_dipole_cut.cpp
  src/SPIN/pair_spin_dipole_long.cpp
  src/SPIN/pair_spin_dmi.cpp
  src/SPIN/pair_spin_exchange.cpp
  src/min.cpp
  src/min.h
  src/min_cg.cpp
  src/min_fire.cpp
  src/min_hftn.cpp
  src/min_quickmin.cpp
  src/min_sd.cpp
Labels: spin_package

#1688 cmake: allow to build against an external libkokkos
  cmake/Modules/Packages/KOKKOS.cmake
Labels: cmake, kokkos_package

#1693 Port more SNAP optimizations to the KOKKOS Package
  src/KOKKOS/pair_snap_kokkos.h
  src/KOKKOS/pair_snap_kokkos_impl.h
  src/KOKKOS/sna_kokkos.h
  src/KOKKOS/sna_kokkos_impl.h
Labels: enhancement, kokkos_package

#1699 Collected small changes for next patch release
  .github/CONTRIBUTING.md
  cmake/Modules/Packages/KOKKOS.cmake
  doc/Makefile
  doc/src/Howto_viscosity.txt
  doc/src/dump_modify.txt
  doc/src/fix.txt
  examples/gcmc/CO2.txt
  examples/gcmc/H2O.txt
  src/COMPRESS/dump_atom_gz.cpp
  src/COMPRESS/dump_custom_gz.cpp
  src/COMPRESS/dump_local_gz.cpp
  src/MANYBODY/pair_bop.cpp
  src/domain.cpp
  src/dump.cpp
  src/dump.h
  src/dump_atom.cpp
  src/dump_custom.cpp
  src/dump_local.cpp
  src/info.cpp
  src/info.h
  src/lammps.cpp
Labels: documentation, dump_feature, maintenance

#1690 Added third order, added documentation, took out extraneous lines, ad…
  doc/src/Commands_all.txt
  doc/src/JPG/dynamical_matrix_dynmat.jpg
  doc/src/JPG/dynamical_matrix_force_constant.jpg
  doc/src/JPG/dynamical_matrix_phonons.jpg
  doc/src/JPG/third_order_force_constant.png
  doc/src/Packages_details.txt
  doc/src/commands_list.txt
  doc/src/dynamical_matrix.txt
  doc/src/lammps.book
  doc/src/third_order.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/phonon/dynamical_matrix_command/python/README.md
  examples/USER/phonon/dynamical_matrix_command/python/dynmat.py
  src/USER-PHONON/Install.sh
  src/USER-PHONON/README
  src/USER-PHONON/dynamical_matrix.cpp
  src/USER-PHONON/third_order.cpp
  src/USER-PHONON/third_order.h
Labels: enhancement

#1707 Lammps gjf small updates
  doc/src/fix_langevin.txt
  src/fix_langevin.cpp
Labels: update

#1709 New example/UNITS dir
  doc/src/Examples.txt
  examples/README
  examples/UNITS/README
  examples/UNITS/in.ar.lj
  examples/UNITS/in.ar.metal
  examples/UNITS/in.ar.real
  examples/UNITS/log.ar.lj.8Oct19.g++.1
  examples/UNITS/log.ar.lj.8Oct19.g++.4
  examples/UNITS/log.ar.metal.8Oct19.g++.1
  examples/UNITS/log.ar.metal.8Oct19.g++.4
  examples/UNITS/log.ar.real.8Oct19.g++.1
  examples/UNITS/log.ar.real.8Oct19.g++.4
Labels: enhancement

#1631 Bug fixes for pair style granular
  doc/src/pair_granular.txt
  src/GRANULAR/pair_granular.cpp
Labels: bugfix

#1713 Bond/react: angle constraints bugfix
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix, user_misc_package

#1714 Added invisible helper function to check values of Clebsch-Gordan coeffs
  src/SNAP/sna.cpp
  src/SNAP/sna.h
Labels: maintenance

#1716 Add topology interaction check to Force::init()
  doc/src/Errors_warnings.txt
  doc/src/min_spin.txt
  src/force.cpp
  src/force.h
Labels: documentation, update

#1719 Correct pppm/tip4p styles for triclinic boxes
  cmake/presets/most.cmake
  src/KSPACE/pppm_tip4p.cpp
  src/STUBS/mpi.c
  src/USER-OMP/pppm_omp.cpp
  src/USER-OMP/pppm_tip4p_omp.cpp
  src/force.cpp
Labels: bugfix, kspace_package, user_omp_package

#1725 Fix gjf bugs
  examples/gjf/in.gjf.vfull
  examples/gjf/in.gjf.vhalf
  examples/gjf/log.15Oct19.gjf.vfull.g++.1
  examples/gjf/log.15Oct19.gjf.vfull.g++.4
  examples/gjf/log.15Oct19.gjf.vhalf.g++.1
  examples/gjf/log.15Oct19.gjf.vhalf.g++.4
  src/KOKKOS/fix_langevin_kokkos.cpp
  src/fix_langevin.cpp
Labels: bugfix

#1727 Set KIM pointer appropriately for Energy
  src/KIM/pair_kim.cpp
Labels: kim_package

#1728 Update compute_gyration_shape.cpp
  doc/src/compute_gyration_shape.txt
  doc/utils/sphinx-config/false_positives.txt
  src/USER-MISC/compute_gyration_shape.cpp
Labels: bugfix, user_misc_package

#1724 Upgrade Lepton library, handle its C++11 requirement
  cmake/CMakeLists.txt
  cmake/Modules/Packages/USER-COLVARS.cmake
  lib/colvars/Makefile.common
  lib/colvars/Makefile.g++
  lib/colvars/README
  lib/colvars/lepton/include/lepton/CompiledExpression.h
  lib/colvars/lepton/include/lepton/CustomFunction.h
  lib/colvars/lepton/include/lepton/ExpressionProgram.h
  lib/colvars/lepton/include/lepton/Operation.h
  lib/colvars/lepton/src/CompiledExpression.cpp
  lib/colvars/lepton/src/ExpressionProgram.cpp
  lib/colvars/lepton/src/MSVC_erfc.h
  lib/colvars/lepton/src/Operation.cpp
  lib/colvars/lepton/src/ParsedExpression.cpp
  lib/colvars/lepton/src/Parser.cpp
Labels: build_system, cmake

#1726 Add Singularity definition files suitable for compiling and debugging LAMMPS
  doc/src/Tools.txt
  tools/singularity/README.md
  tools/singularity/centos7.def
  tools/singularity/ubuntu18.04.def
Labels: tools

#1738 Update singularity definition files in tools folder
  tools/singularity/README.md
  tools/singularity/centos7.def
  tools/singularity/centos8.def
  tools/singularity/ubuntu16.04.def
  tools/singularity/ubuntu18.04.def
Labels: maintenance, tools

#1734 Bond/react: Arrhenius constraint
  doc/src/Eqs/fix_bond_react.jpg
  doc/src/Eqs/fix_bond_react.tex
  doc/src/fix_bond_react.txt
  doc/utils/sphinx-config/false_positives.txt
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: enhancement, user_misc_package

#1733 Adding -std=c++11 specifier to Intel Makefiles
  cmake/CMakeLists.txt
  src/MAKE/OPTIONS/Makefile.intel_coprocessor
  src/MAKE/OPTIONS/Makefile.intel_cpu
  src/MAKE/OPTIONS/Makefile.intel_cpu_intelmpi
  src/MAKE/OPTIONS/Makefile.intel_cpu_mpich
  src/MAKE/OPTIONS/Makefile.intel_cpu_openmpi
  src/MAKE/OPTIONS/Makefile.knl
Labels: build_system

#1732 Fixing Gay-Berne "extra" documentation to define epsilon parameters c…
  doc/src/PDF/pair_gayberne_extra.pdf
  doc/src/PDF/pair_gayberne_extra.tex
Labels: documentation

#1730 USER-CGDNA quasi-unique base pairing
  doc/src/pair_oxdna.txt
  doc/src/pair_oxdna2.txt
  examples/USER/cgdna/examples/oxDNA/duplex1/in.duplex1
  examples/USER/cgdna/examples/oxDNA/duplex1/log.07Aug19.duplex1.g++.1
  examples/USER/cgdna/examples/oxDNA/duplex1/log.07Aug19.duplex1.g++.4
  examples/USER/cgdna/examples/oxDNA/duplex1/log.18Jun19.duplex1.g++.1
  examples/USER/cgdna/examples/oxDNA/duplex1/log.18Jun19.duplex1.g++.4
  examples/USER/cgdna/examples/oxDNA/duplex2/in.duplex2
  examples/USER/cgdna/examples/oxDNA/duplex2/log.07Aug19.duplex2.g++.1
  examples/USER/cgdna/examples/oxDNA/duplex2/log.07Aug19.duplex2.g++.4
  examples/USER/cgdna/examples/oxDNA/duplex2/log.18Jun19.duplex2.g++.1
  examples/USER/cgdna/examples/oxDNA/duplex2/log.18Jun19.duplex2.g++.4
  examples/USER/cgdna/examples/oxDNA2/duplex1/in.duplex1
  examples/USER/cgdna/examples/oxDNA2/duplex1/log.07Aug19.duplex1.g++.1
  examples/USER/cgdna/examples/oxDNA2/duplex1/log.07Aug19.duplex1.g++.4
  examples/USER/cgdna/examples/oxDNA2/duplex2/in.duplex2
  examples/USER/cgdna/examples/oxDNA2/duplex2/log.07Aug19.duplex2.g++.1
  examples/USER/cgdna/examples/oxDNA2/duplex2/log.07Aug19.duplex2.g++.4
  examples/USER/cgdna/examples/oxDNA2/duplex3/in.duplex3
  examples/USER/cgdna/examples/oxDNA2/duplex3/log.07Aug19.duplex3.g++.1
  examples/USER/cgdna/examples/oxDNA2/duplex3/log.07Aug19.duplex3.g++.4
  src/USER-CGDNA/pair_oxdna_hbond.cpp
  src/USER-CGDNA/pair_oxdna_hbond.h
  src/USER-CGDNA/pair_oxdna_stk.cpp
  src/USER-CGDNA/pair_oxdna_stk.h
Labels: enhancement

#1742 Fixes bug in extract_compute() python method
  python/lammps.py
Labels: bugfix, library_interface, python_module

#1735 Gpu mem leak with init invoked multiple times
  lib/gpu/lal_base_atomic.cpp
  lib/gpu/lal_base_charge.cpp
  lib/gpu/lal_base_dipole.cpp
  lib/gpu/lal_base_dpd.cpp
  lib/gpu/lal_base_ellipsoid.cpp
  lib/gpu/lal_base_three.cpp
  lib/gpu/lal_pppm.cpp
Labels: bugfix, gpu_package

#1744 Collected small fixes for next patch release
  doc/src/Errors_warnings.txt
  python/lammps.py
  src/GPU/gpu_extra.h
  src/GPU/pair_sw_gpu.cpp
  src/GPU/pair_tersoff_gpu.cpp
  src/GPU/pair_tersoff_mod_gpu.cpp
  src/GPU/pair_tersoff_zbl_gpu.cpp
  src/GPU/pair_vashishta_gpu.cpp
  src/KSPACE/ewald_dipole.cpp
  src/KSPACE/ewald_dipole_spin.cpp
  src/KSPACE/pppm_dipole.cpp
  src/KSPACE/pppm_dipole_spin.cpp
Labels: bugfix, enhancement, maintenance

#1750 Bugfix for fix pour and PBC
  src/GRANULAR/fix_pour.cpp
  src/GRANULAR/fix_pour.h
Labels: bugfix

#1746 Bug fix for gay-berne potential when mu != 1.0.
  doc/src/PDF/pair_gayberne_extra.pdf
  doc/src/PDF/pair_gayberne_extra.tex
  lib/gpu/lal_gayberne.cu
  src/ASPHERE/pair_gayberne.cpp
  src/USER-INTEL/pair_gayberne_intel.cpp
Labels: bugfix

#1751 USER-VTK bug fix
  src/GRANULAR/pair_granular.cpp
  src/USER-VTK/dump_vtk.cpp
  src/dump_custom.cpp
Labels: bugfix

#1569 throw away random numbers to avoid unexpected correlations
  src/GRANULAR/fix_pour.cpp
  src/MISC/fix_deposit.cpp
  src/MISC/fix_evaporate.cpp
  src/create_atoms.cpp
Labels: enhancement

#1737 Step version string for next patch release
  doc/lammps.1
  doc/src/Manual.txt
  src/lmptype.h
  src/version.h
Labels: documentation, maintenance
