Repository lammps/lammps, pull requests merged in 2019-09, with the labels that each got.

#1634 cmake: add version check for kim-api
  cmake/Modules/FindKIM-API.cmake
  cmake/Modules/Packages/KIM.cmake
Labels: cmake, kim_package

#1654 Add support for Astra/Arm system to LAMMPS build files
  src/MAKE/MACHINES/Makefile.astra_arm
  src/MAKE/MACHINES/Makefile.astra_gcc
Labels: build_system

#1661 USER-INTEL: Adding explicit include path for MKL and updating benchma…
  src/MAKE/OPTIONS/Makefile.intel_cpu
  src/MAKE/OPTIONS/Makefile.intel_cpu_intelmpi
  src/MAKE/OPTIONS/Makefile.intel_cpu_mpich
  src/MAKE/OPTIONS/Makefile.intel_cpu_openmpi
  src/MAKE/OPTIONS/Makefile.knl
  src/USER-INTEL/TEST/run_benchmarks.sh
Labels: build_system

#1653 Cleaning Theta Makefile
  src/MAKE/MACHINES/Makefile.theta
Labels: build_system

#1664 Comm modify docs tweak
  doc/src/comm_modify.txt
Labels: documentation

#1668 Add support for HPE MPI to Kokkos package
  doc/src/Run_options.txt
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
Labels: enhancement, kokkos_package

#1667 Adjusted compute_bond_local to allow components of force to be obtained.
  doc/src/compute_bond_local.txt
  src/compute_bond_local.cpp
Labels: enhancement

#1648 Add w l orientorder
  doc/src/compute_orientorder_atom.txt
  examples/steinhardt/in.bcc
  examples/steinhardt/in.fcc
  examples/steinhardt/in.icos
  src/compute_orientorder_atom.cpp
  src/compute_orientorder_atom.h
Labels: compute_feature, enhancement

#1670 Consolidate constants and enumerators across rigid fix styles
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid.h
  src/RIGID/fix_rigid_nh.cpp
  src/RIGID/fix_rigid_nh_small.cpp
  src/RIGID/fix_rigid_small.cpp
  src/RIGID/fix_rigid_small.h
  src/RIGID/rigid_const.h
  src/USER-OMP/fix_rigid_nh_omp.cpp
  src/USER-OMP/fix_rigid_omp.cpp
  src/USER-OMP/fix_rigid_small_omp.cpp
Labels: maintenance

#1669 Port misc files to Kokkos
  cmake/Modules/Packages/KOKKOS.cmake
  doc/src/Commands_bond.txt
  doc/src/dihedral_harmonic.txt
  src/KOKKOS/Install.sh
  src/KOKKOS/dihedral_harmonic_kokkos.cpp
  src/KOKKOS/dihedral_harmonic_kokkos.h
  src/MOLECULE/dihedral_harmonic.cpp
  src/MOLECULE/dihedral_harmonic.h
  src/compute_pe.cpp
Labels: enhancement, kokkos_package

#1677 Added log files and updated README
  examples/README
  examples/steinhardt/log.13Sept18.bcc.g++.1
  examples/steinhardt/log.13Sept18.bcc.g++.4
  examples/steinhardt/log.13Sept18.fcc.g++.1
  examples/steinhardt/log.13Sept18.fcc.g++.4
  examples/steinhardt/log.13Sept18.icos.g++.1
  examples/steinhardt/log.13Sept18.icos.g++.4
Labels: maintenance

#1662 Fix bugs in handling of local pair property computes with hybrid pair styles
  bench/POTENTIALS/CH.airebo
  bench/POTENTIALS/CdTe.bop.table
  bench/POTENTIALS/Cu_u3.eam
  bench/POTENTIALS/Ni.adp
  doc/src/Build_basics.txt
  doc/src/Build_extras.txt
  doc/src/compute_pair_local.txt
  doc/utils/sphinx-config/false_positives.txt
  src/COLLOID/pair_lubricate.cpp
  src/fix_langevin.cpp
  src/memory.cpp
  src/pair_hybrid.cpp
  src/pair_hybrid.h
  src/pair_hybrid_overlay.cpp
  src/pair_hybrid_overlay.h
Labels: maintenance

#1660 python tool to reorder replica traj
  doc/src/Tools.txt
  doc/src/temper.txt
  doc/utils/sphinx-config/false_positives.txt
  tools/README
  tools/replica/README.md
  tools/replica/example/data.peptide
  tools/replica/example/in.peptide
  tools/replica/example/parse_ene.py
  tools/replica/example/run.sh
  tools/replica/example/runlog.05Sep19
  tools/replica/example/temps.txt
  tools/replica/reorder_remd_traj.py
Labels: tools

#1681 Collected small changes for next patch release
  doc/src/Build_development.txt
  doc/src/Howto_spins.txt
  doc/src/Speed_kokkos.txt
  doc/src/Tools.txt
  doc/src/compute.txt
  doc/src/compute_coord_atom.txt
  doc/src/compute_hma.txt
  doc/src/compute_orientorder_atom.txt
  doc/src/compute_sna_atom.txt
  doc/src/compute_spin.txt
  doc/src/dynamical_matrix.txt
  doc/src/fix.txt
  doc/src/fix_controller.txt
  doc/src/fix_neb_spin.txt
  doc/src/fix_precession_spin.txt
  doc/src/fix_rigid_meso.txt
  doc/src/fix_setforce.txt
  doc/src/improper_fourier.txt
  doc/src/kspace_style.txt
  doc/src/min_modify.txt
  doc/src/min_spin.txt
  doc/src/min_style.txt
  doc/src/minimize.txt
  doc/src/neb_spin.txt
  doc/src/package.txt
  doc/src/pair_e3b.txt
  doc/src/pair_granular.txt
  doc/src/pair_kolmogorov_crespi_full.txt
  doc/src/pair_mm3_switch3_coulgauss.txt
  doc/src/pair_oxdna2.txt
  doc/src/pair_snap.txt
  doc/src/pair_spin_dipole.txt
  doc/src/pair_spin_dmi.txt
  doc/src/pair_spin_neel.txt
  examples/USER/drude/toluene/data.toluene
  examples/USER/drude/toluene/in.toluene.lang
  examples/USER/drude/toluene/in.toluene.nh
  examples/USER/drude/toluene/log.27Nov18.toluene.lang.g++.1
  examples/USER/drude/toluene/log.27Nov18.toluene.lang.g++.4
  examples/USER/drude/toluene/log.27Nov18.toluene.nh.g++.1
  examples/USER/drude/toluene/log.27Nov18.toluene.nh.g++.4
  examples/USER/drude/toluene/log.7Aug19.toluene.lang.g++.1
  examples/USER/drude/toluene/log.7Aug19.toluene.lang.g++.4
  examples/USER/drude/toluene/log.7Aug19.toluene.nh.g++.1
  examples/USER/drude/toluene/log.7Aug19.toluene.nh.g++.4
  src/KOKKOS/npair_kokkos.h
  src/KOKKOS/pair_gran_hooke_history_kokkos.h
  src/KSPACE/ewald_dipole.h
  src/USER-DIFFRACTION/compute_saed.cpp
  src/USER-DIFFRACTION/compute_xrd.cpp
  src/USER-MISC/pair_ilp_graphene_hbn.h
  src/USER-MISC/pair_kolmogorov_crespi_full.h
  src/kspace.h
  src/read_restart.cpp
  tools/python/pizza/cfg.py
  tools/python/pizza/dump.py
  tools/python/pizza/gnu.py
  tools/python/pizza/log.py
  tools/python/pizza/pdbfile.py
  tools/python/pizza/xyz.py
Labels: documentation, maintenance

#1666 added LD potential and wrote html-style doc
  doc/src/Commands_pair.txt
  doc/src/Eqs/pair_local_density_energy.jpg
  doc/src/Eqs/pair_local_density_energy.tex
  doc/src/Eqs/pair_local_density_energy_implement.jpg
  doc/src/Eqs/pair_local_density_energy_implement.tex
  doc/src/Eqs/pair_local_density_energy_multi.jpg
  doc/src/Eqs/pair_local_density_energy_multi.tex
  doc/src/Eqs/pair_local_density_indicator_func.jpg
  doc/src/Eqs/pair_local_density_indicator_func.tex
  doc/src/Eqs/pair_local_density_ld.jpg
  doc/src/Eqs/pair_local_density_ld.tex
  doc/src/Eqs/pair_local_density_ld_implement.jpg
  doc/src/Eqs/pair_local_density_ld_implement.tex
  doc/src/Eqs/pair_local_density_ld_multi.jpg
  doc/src/Eqs/pair_local_density_ld_multi.tex
  doc/src/lammps.book
  doc/src/pair_local_density.txt
  doc/src/pair_style.txt
  doc/src/pairs.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/misc/local_density/benzene_water/benzene_water.data
  examples/USER/misc/local_density/benzene_water/benzene_water.in
  examples/USER/misc/local_density/benzene_water/benzene_water.localdensity.table
  examples/USER/misc/local_density/benzene_water/benzene_water.pair.table
  examples/USER/misc/local_density/benzene_water/log.04Sep19.g++.1
  examples/USER/misc/local_density/methanol_implicit_water/log.04Sep19.g++.1
  examples/USER/misc/local_density/methanol_implicit_water/methanol_implicit_water.data
  examples/USER/misc/local_density/methanol_implicit_water/methanol_implicit_water.in
  examples/USER/misc/local_density/methanol_implicit_water/methanol_implicit_water.localdensity.table
  examples/USER/misc/local_density/methanol_implicit_water/methanol_implicit_water.pair.table
  src/USER-MISC/README
  src/USER-MISC/pair_local_density.cpp
  src/USER-MISC/pair_local_density.h
Labels: user_misc_package

#1684 Implement test for C++11 and document it
  cmake/CMakeLists.txt
  doc/src/Build_settings.txt
  src/MAKE/Makefile.mpi
  src/MAKE/Makefile.serial
  src/lammps.cpp
  src/lmptype.h
Labels: maintenance

#1683 USER-INTEL: Explictly disabling G2S opts to improve lj/cut, eam, and …
  src/MAKE/OPTIONS/Makefile.intel_cpu
  src/MAKE/OPTIONS/Makefile.intel_cpu_intelmpi
  src/MAKE/OPTIONS/Makefile.intel_cpu_mpich
  src/MAKE/OPTIONS/Makefile.intel_cpu_openmpi
  src/MAKE/OPTIONS/Makefile.knl
  src/USER-INTEL/npair_full_bin_ghost_intel.cpp
  src/USER-INTEL/npair_intel.cpp
  src/USER-INTEL/pair_dpd_intel.cpp
  src/USER-INTEL/pair_eam_intel.cpp
  src/USER-INTEL/pair_lj_cut_intel.cpp
Labels: maintenance, user_intel_package

#1687 Step version string for next patch release
  doc/lammps.1
  doc/src/Manual.txt
  src/version.h
Labels: maintenance
