Repository lammps/lammps, pull requests merged in 2019-06, with the labels that each got.

#1486 Fix error in E3B documentation
  doc/src/pair_e3b.txt
Labels: documentation

#1488 Document removed features
  doc/src/Commands.txt
  doc/src/Commands_removed.txt
  doc/src/variable.txt
Labels: documentation

#1477 Bond/react reaction topology overflow
  doc/src/Errors_messages.txt
  doc/src/Errors_warnings.txt
  doc/src/fix_bond_react.txt
  doc/utils/sphinx-config/false_positives.txt
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: bugfix, documentation, update, user_misc_package

#1489 Change test for OpenMP default setting to be compatible with CMake 2.8.x
  cmake/CMakeLists.txt
Labels: cmake, maintenance

#1490 Step version number for stable release
  doc/lammps.1
  doc/src/Manual.txt
  src/version.h
Labels: maintenance

#1497 cmake: check for immintrin.h
  cmake/CMakeLists.txt
Labels: cmake, maintenance

#1492 Collected small changes for the next patch
  doc/src/Commands_bond.txt
  doc/src/Commands_pair.txt
  doc/src/Errors_messages.txt
  src/Makefile
  src/USER-FEP/pair_lj_class2_coul_long_soft.cpp
  src/USER-PLUMED/fix_plumed.cpp
  src/USER-QTB/fix_qbmsst.cpp
  src/fix_adapt.cpp
  src/fix_nve_limit.cpp
  src/force.cpp
  src/force.h
  src/kspace.cpp
  src/kspace.h
  src/lammps.cpp
  src/lmptype.h
  src/modify.cpp
  src/modify.h
  src/neighbor.cpp
  src/pair_coul_streitz.cpp
  src/velocity.cpp
Labels: documentation, kspace_package, maintenance

#1422 Optimize KOKKOS package for small systems
  doc/src/Speed_kokkos.txt
  doc/src/package.txt
  src/KOKKOS/atom_kokkos.cpp
  src/KOKKOS/atom_vec_angle_kokkos.cpp
  src/KOKKOS/atom_vec_atomic_kokkos.cpp
  src/KOKKOS/atom_vec_bond_kokkos.cpp
  src/KOKKOS/atom_vec_charge_kokkos.cpp
  src/KOKKOS/atom_vec_dpd_kokkos.cpp
  src/KOKKOS/atom_vec_full_kokkos.cpp
  src/KOKKOS/atom_vec_hybrid_kokkos.cpp
  src/KOKKOS/atom_vec_kokkos.cpp
  src/KOKKOS/atom_vec_kokkos.h
  src/KOKKOS/atom_vec_molecular_kokkos.cpp
  src/KOKKOS/atom_vec_sphere_kokkos.cpp
  src/KOKKOS/comm_kokkos.cpp
  src/KOKKOS/comm_kokkos.h
  src/KOKKOS/domain_kokkos.cpp
  src/KOKKOS/fix_nve_kokkos.cpp
  src/KOKKOS/fix_property_atom_kokkos.cpp
  src/KOKKOS/fix_qeq_reax_kokkos.cpp
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/kokkos_type.h
  src/KOKKOS/npair_kokkos.cpp
  src/KOKKOS/npair_kokkos.h
  src/KOKKOS/pair_kokkos.h
  src/KOKKOS/verlet_kokkos.cpp
  src/neighbor.h
Labels: enhancement, kokkos_package

#1494 Fix for extep when NULL or only some elements from potential file are used.
  src/USER-MISC/pair_extep.cpp
Labels: bugfix, user_misc_package

#1496 reaxc/qeq optimization - using kokkos hierarchical parallelism
  src/KOKKOS/fix_qeq_reax_kokkos.cpp
  src/KOKKOS/fix_qeq_reax_kokkos.h
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/neighbor_kokkos.cpp
  src/KOKKOS/pair_exp6_rx_kokkos.cpp
  src/KOKKOS/pair_exp6_rx_kokkos.h
  src/KOKKOS/pppm_kokkos.cpp
  src/KOKKOS/rand_pool_wrap_kokkos.cpp
  src/accelerator_kokkos.h
  src/comm.cpp
  src/finish.cpp
Labels: enhancement, kokkos_package, update

#1502 Refactor CMake configuration
  cmake/CMakeLists.txt
  cmake/Modules/CodeCoverage.cmake
  cmake/Modules/Documentation.cmake
  cmake/Modules/LAMMPSUtils.cmake
  cmake/Modules/Packages/COMPRESS.cmake
  cmake/Modules/Packages/CORESHELL.cmake
  cmake/Modules/Packages/GPU.cmake
  cmake/Modules/Packages/KIM.cmake
  cmake/Modules/Packages/KOKKOS.cmake
  cmake/Modules/Packages/KSPACE.cmake
  cmake/Modules/Packages/LATTE.cmake
  cmake/Modules/Packages/MESSAGE.cmake
  cmake/Modules/Packages/MSCG.cmake
  cmake/Modules/Packages/OPT.cmake
  cmake/Modules/Packages/PYTHON.cmake
  cmake/Modules/Packages/QEQ.cmake
  cmake/Modules/Packages/USER-H5MD.cmake
  cmake/Modules/Packages/USER-INTEL.cmake
  cmake/Modules/Packages/USER-MOLFILE.cmake
  cmake/Modules/Packages/USER-NETCDF.cmake
  cmake/Modules/Packages/USER-OMP.cmake
  cmake/Modules/Packages/USER-PLUMED.cmake
  cmake/Modules/Packages/USER-QMMM.cmake
  cmake/Modules/Packages/USER-QUIP.cmake
  cmake/Modules/Packages/USER-SCAFACOS.cmake
  cmake/Modules/Packages/USER-SDPD.cmake
  cmake/Modules/Packages/USER-SMD.cmake
  cmake/Modules/Packages/USER-VTK.cmake
  cmake/Modules/Packages/VORONOI.cmake
  cmake/Modules/Testing.cmake
Labels: cmake, maintenance

#1501 Simplify and update vim syntax highlighting files
  tools/vim/README.txt
  tools/vim/filetype.vim
  tools/vim/lammps.vim
Labels: maintenance, tools

#1485 memcpy2memmove
  src/math_extra.cpp
  src/rcb.cpp
Labels: maintenance

#1506 Bugfix for bond_style table with MPI
  src/MOLECULE/bond_table.cpp
Labels: bugfix

#1504 Collected small bugfixes and changes
  cmake/CMakeLists.txt
  cmake/Modules/Packages/USER-INTEL.cmake
  src/info.cpp
  src/variable.cpp
Labels: bugfix, maintenance

#1430 Enable neighbor build on the device for pair hybrid substyles
  doc/src/Errors_messages.txt
  doc/src/Speed_compare.txt
  doc/src/package.txt
  lib/gpu/lal_base_atomic.cpp
  lib/gpu/lal_base_charge.cpp
  lib/gpu/lal_base_dipole.cpp
  lib/gpu/lal_base_dpd.cpp
  lib/gpu/lal_base_ellipsoid.cpp
  lib/gpu/lal_base_three.cpp
  lib/gpu/lal_device.cpp
  lib/gpu/lal_device.h
  src/GPU/README
  src/GPU/fix_gpu.cpp
  src/GPU/fix_gpu.h
Labels: enhancement, gpu_package, update

#1507 Back-porting of Zombie SNAP improvements
  doc/src/compute_sna_atom.txt
  doc/src/pair_snap.txt
  potentials/Ta06A.snapparam
  potentials/W_2940_2017_2.snapparam
  src/KOKKOS/pair_snap_kokkos_impl.h
  src/KOKKOS/sna_kokkos.h
  src/KOKKOS/sna_kokkos_impl.h
  src/SNAP/compute_sna_atom.cpp
  src/SNAP/compute_sna_atom.h
  src/SNAP/compute_snad_atom.cpp
  src/SNAP/compute_snad_atom.h
  src/SNAP/compute_snav_atom.cpp
  src/SNAP/compute_snav_atom.h
  src/SNAP/openmp_snap.h
  src/SNAP/pair_snap.cpp
  src/SNAP/pair_snap.h
  src/SNAP/sna.cpp
  src/SNAP/sna.h
Labels: enhancement, update

#1510 Implementation of inner/middle/outer compute methods for lj/class2
  doc/src/pair_class2.txt
  src/CLASS2/pair_lj_class2.cpp
  src/CLASS2/pair_lj_class2.h
Labels: enhancement, update

#1513 Make USER-TALLY compute styles compatible with hybrid pair styles
  src/USER-TALLY/README
  src/USER-TALLY/compute_force_tally.cpp
  src/USER-TALLY/compute_heat_flux_tally.cpp
  src/USER-TALLY/compute_pe_mol_tally.cpp
  src/USER-TALLY/compute_pe_tally.cpp
  src/USER-TALLY/compute_stress_tally.cpp
Labels: bugfix, update

#1516 Using PLUMED to compute committor with LAMMPS
  src/USER-PLUMED/fix_plumed.cpp
Labels: update

#1517 Bond/react: clarify reaction-template warning messages
  doc/src/Errors_messages.txt
  doc/src/Errors_warnings.txt
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
Labels: enhancement, update, user_misc_package

#1518 Collected small changes and fixes for the next patch release
  cmake/CMakeLists.txt
  cmake/Modules/Packages/KIM.cmake
  cmake/Modules/Packages/LATTE.cmake
  cmake/Modules/Packages/MSCG.cmake
  cmake/Modules/Packages/USER-PLUMED.cmake
  cmake/Modules/Packages/USER-SCAFACOS.cmake
  cmake/Modules/Packages/VORONOI.cmake
  doc/src/Build_cmake.txt
  doc/src/compute_tally.txt
  examples/USER/misc/kolmogorov_crespi_full/CH.rebo
  examples/USER/misc/kolmogorov_crespi_full/in.bilayer-graphene
  examples/USER/misc/kolmogorov_crespi_full/log.5Jun19.bilayer-graphene.g++.1
  examples/USER/misc/kolmogorov_crespi_full/log.5Jun19.bilayer-graphene.g++.4
  src/USER-LB/fix_lb_fluid.cpp
  src/USER-TALLY/compute_force_tally.cpp
  src/USER-TALLY/compute_heat_flux_tally.cpp
  src/USER-TALLY/compute_pe_mol_tally.cpp
  src/USER-TALLY/compute_pe_tally.cpp
  src/USER-TALLY/compute_stress_tally.cpp
  src/lmptype.h
  src/thermo.cpp
Labels: bugfix, maintenance, update

#1522 Step version string for next patch release
  doc/lammps.1
  doc/src/Manual.txt
  src/version.h
Labels: maintenance

#1530 Minor cleanup for doc/src
  doc/src/JPG/dreiding_hbond.jpg
  doc/src/JPG/umbrella.jpg
  doc/src/improper_fourier.txt
  doc/src/improper_inversion_harmonic.txt
  doc/src/improper_umbrella.txt
  doc/src/pair_hbond_dreiding.txt
  doc/src/pair_spin_dipole.txt
Labels: bugfix, documentation, maintenance

#1531 Added NULL initialization for snaptr
  src/SNAP/pair_snap.cpp
Labels: bugfix, update

#1534 Archlinux install documentation
  doc/src/Install_linux.txt
  doc/utils/sphinx-config/false_positives.txt
Labels: documentation, enhancement

#1525 Collected small changes and fixes for the next patch
  cmake/CMakeLists.txt
  doc/src/Commands_all.txt
  doc/src/Commands_pair.txt
  doc/src/Eqs/angle_class2_p6.tex
  doc/src/Eqs/angle_cosine_buck6d.tex
  doc/src/Eqs/improper_inversion_harmonic.tex
  doc/src/Eqs/pair_agni.tex
  doc/src/Eqs/pair_buck6d.tex
  doc/src/Eqs/pair_coul_gauss.tex
  doc/src/Packages_details.txt
  doc/src/lammps.book
  doc/src/pair_modify.txt
  doc/src/pair_style.txt
  doc/src/pairs.txt
  src/CLASS2/pair_lj_class2_coul_cut.cpp
  src/MISC/fix_orient_bcc.cpp
  src/MISC/fix_orient_fcc.cpp
  src/MISC/pair_nm_cut_coul_cut.cpp
  src/REPLICA/neb.cpp
  src/REPLICA/neb.h
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid.h
  src/RIGID/fix_rigid_small.cpp
  src/RIGID/fix_rigid_small.h
  src/SPIN/neb_spin.cpp
  src/SPIN/neb_spin.h
  src/atom.cpp
  src/domain.cpp
  src/force.cpp
  src/input.cpp
  src/pair.cpp
  src/pair_coul_cut.cpp
  src/pair_hybrid.cpp
  src/pair_lj_cut_coul_cut.cpp
  src/read_restart.cpp
  src/update.cpp
Labels: bugfix, cmake, maintenance

#1535 Implementation of inner/middle/outer compute methods for lj/class2/coul/long
  doc/src/pair_class2.txt
  src/CLASS2/pair_lj_class2_coul_long.cpp
  src/CLASS2/pair_lj_class2_coul_long.h
Labels: enhancement, update

#1539 add missing include needed on ppc64le
  lib/gpu/lal_device.cpp
Labels: bugfix, gpu_package

#1547 Workaround to make formatting of code blocks consistent
  doc/utils/sphinx-config/_themes/lammps_theme/static/css/theme.css
Labels: bugfix, documentation
