Repository lammps/lammps, pull requests merged in 2019-07, with the labels that each got.

#1540 Port Recent SNAP changes to Kokkos
  src/KOKKOS/pair_snap_kokkos.h
  src/KOKKOS/pair_snap_kokkos_impl.h
  src/KOKKOS/sna_kokkos.h
  src/KOKKOS/sna_kokkos_impl.h
  src/SNAP/compute_snad_atom.cpp
  src/SNAP/compute_snav_atom.cpp
  src/SNAP/pair_snap.cpp
  src/SNAP/sna.cpp
  src/SNAP/sna.h
Labels: enhancement, kokkos_package

#1538 Bug fixes to pair granular
  src/GRANULAR/pair_granular.cpp
Labels: bugfix, update

#1537 Refactor input file processing flow of control
  src/input.cpp
Labels: enhancement, library_interface, maintenance

#1550 Fixed a bug in lj96/cut/gpu involving missing the special_lj factor
  lib/gpu/lal_lj96.cu
  lib/gpu/lal_tersoff.cu
  lib/gpu/lal_tersoff_mod.cu
  lib/gpu/lal_tersoff_zbl.cu
  lib/gpu/lal_yukawa_colloid.cu
  lib/gpu/lal_zbl.cu
Labels: bugfix, gpu_package

#1544 Collected small changes and bugfixes for the next patch release
  doc/src/if.txt
  src/ASPHERE/compute_temp_asphere.cpp
  src/BODY/compute_temp_body.cpp
  src/CORESHELL/compute_temp_cs.cpp
  src/QEQ/fix_qeq_shielded.cpp
  src/SPIN/compute_spin.cpp
  src/USER-BOCS/compute_pressure_bocs.cpp
  src/USER-DRUDE/compute_temp_drude.cpp
  src/USER-EFF/compute_temp_deform_eff.cpp
  src/USER-EFF/compute_temp_region_eff.cpp
  src/USER-FEP/compute_fep.cpp
  src/USER-MISC/compute_temp_rotate.cpp
  src/USER-REAXC/fix_qeq_reax.cpp
  src/compute_com.cpp
  src/compute_group_group.cpp
  src/compute_gyration.cpp
  src/compute_heat_flux.cpp
  src/compute_msd.cpp
  src/compute_pressure.cpp
  src/compute_temp.cpp
  src/compute_temp_chunk.cpp
  src/compute_temp_com.cpp
  src/compute_temp_deform.cpp
  src/compute_temp_partial.cpp
  src/compute_temp_ramp.cpp
  src/compute_temp_region.cpp
  src/compute_temp_sphere.cpp
  src/compute_vacf.cpp
  src/input.cpp
  src/input.h
  src/thermo.cpp
Labels: bugfix, user_reaxc_package

#1555 Fix issue in Kokkos neighbor binning when using non-Kokkos lists on GPUs
  src/KOKKOS/nbin_kokkos.cpp
  src/KOKKOS/neighbor_kokkos.cpp
  src/nbin.cpp
  src/nbin.h
Labels: bugfix, kokkos_package

#1553 Fixed a few problems with read_dump xyz
  src/USER-MOLFILE/reader_molfile.cpp
  src/USER-MOLFILE/reader_molfile.h
  src/read_dump.cpp
  src/reader.cpp
  src/reader.h
  src/reader_native.cpp
  src/reader_native.h
  src/reader_xyz.cpp
  src/reader_xyz.h
Labels: bugfix, enhancement

#1552 Validate more numbers read from data files
  src/DIPOLE/atom_vec_dipole.cpp
  src/KOKKOS/atom_vec_angle_kokkos.cpp
  src/KOKKOS/atom_vec_atomic_kokkos.cpp
  src/KOKKOS/atom_vec_bond_kokkos.cpp
  src/KOKKOS/atom_vec_charge_kokkos.cpp
  src/KOKKOS/atom_vec_dpd_kokkos.cpp
  src/KOKKOS/atom_vec_full_kokkos.cpp
  src/KOKKOS/atom_vec_hybrid_kokkos.cpp
  src/KOKKOS/atom_vec_molecular_kokkos.cpp
  src/KOKKOS/atom_vec_sphere_kokkos.cpp
  src/MOLECULE/atom_vec_angle.cpp
  src/MOLECULE/atom_vec_bond.cpp
  src/MOLECULE/atom_vec_full.cpp
  src/MOLECULE/atom_vec_molecular.cpp
  src/MOLECULE/atom_vec_template.cpp
  src/PERI/atom_vec_peri.cpp
  src/SPIN/atom_vec_spin.cpp
  src/USER-AWPMD/atom_vec_wavepacket.cpp
  src/USER-DPD/atom_vec_dpd.cpp
  src/USER-EFF/atom_vec_electron.cpp
  src/USER-MESO/atom_vec_edpd.cpp
  src/USER-MESO/atom_vec_mdpd.cpp
  src/USER-MESO/atom_vec_tdpd.cpp
  src/USER-SMD/atom_vec_smd.cpp
  src/USER-SPH/atom_vec_meso.cpp
  src/atom_vec.cpp
  src/atom_vec_atomic.cpp
  src/atom_vec_body.cpp
  src/atom_vec_charge.cpp
  src/atom_vec_ellipsoid.cpp
  src/atom_vec_hybrid.cpp
  src/atom_vec_line.cpp
  src/atom_vec_sphere.cpp
  src/atom_vec_tri.cpp
  src/utils.cpp
  src/utils.h
Labels: enhancement

#1551 MEAM/C: embedding-function related refactoring
  doc/src/pair_meamc.txt
  src/USER-MEAMC/meam.h
  src/USER-MEAMC/meam_dens_final.cpp
  src/USER-MEAMC/meam_dens_init.cpp
  src/USER-MEAMC/meam_funcs.cpp
  src/USER-MEAMC/meam_setup_done.cpp
  src/USER-MEAMC/pair_meamc.cpp
Labels: enhancement

#1559 Complete data file read validation
  src/DIPOLE/atom_vec_dipole.cpp
  src/KOKKOS/atom_vec_dpd_kokkos.cpp
  src/KOKKOS/atom_vec_hybrid_kokkos.cpp
  src/KOKKOS/atom_vec_sphere_kokkos.cpp
  src/MOLECULE/atom_vec_angle.cpp
  src/MOLECULE/atom_vec_bond.cpp
  src/MOLECULE/atom_vec_full.cpp
  src/MOLECULE/atom_vec_molecular.cpp
  src/MOLECULE/atom_vec_template.cpp
  src/PERI/atom_vec_peri.cpp
  src/SPIN/atom_vec_spin.cpp
  src/USER-AWPMD/atom_vec_wavepacket.cpp
  src/USER-DPD/atom_vec_dpd.cpp
  src/USER-EFF/atom_vec_electron.cpp
  src/USER-MESO/atom_vec_edpd.cpp
  src/USER-MESO/atom_vec_mdpd.cpp
  src/USER-MESO/atom_vec_tdpd.cpp
  src/USER-SMD/atom_vec_smd.cpp
  src/USER-SPH/atom_vec_meso.cpp
  src/atom_vec_atomic.cpp
  src/atom_vec_body.cpp
  src/atom_vec_charge.cpp
  src/atom_vec_ellipsoid.cpp
  src/atom_vec_hybrid.cpp
  src/atom_vec_line.cpp
  src/atom_vec_sphere.cpp
  src/atom_vec_tri.cpp
Labels: enhancement, maintenance

#1560 Fix memory issue in Kokkos neigh list when using half-from-full
  src/KOKKOS/neigh_list_kokkos.cpp
Labels: bugfix, kokkos_package

#1562 Removed TEMPLATED_FIX_LANGEVIN ifdef and untemplated version of fix langevin
  src/fix_langevin.cpp
  src/fix_langevin.h
Labels: maintenance

#1561 Fix bug in fix nve/intel
  src/USER-INTEL/fix_nh_intel.cpp
  src/USER-INTEL/fix_nve_intel.cpp
Labels: bugfix, user_intel_package

#1563 Fix segfault in fix_setforce_kokkos
  src/KOKKOS/fix_setforce_kokkos.cpp
Labels: bugfix, kokkos_package

#1570 Minor bug corrections in the SPIN package
  doc/src/read_data.txt
  doc/utils/sphinx-config/false_positives.txt
  src/SPIN/atom_vec_spin.cpp
  src/SPIN/fix_nve_spin.cpp
  src/SPIN/min_spin.cpp
Labels: bug, maintenance, spin_package

#1575 Better error checking on parsing files
  doc/src/Errors_messages.txt
  src/REPLICA/neb.cpp
  src/USER-REAXC/fix_qeq_reax.cpp
  src/atom.cpp
  src/atom.h
  src/fix_tmd.cpp
  src/procmap.cpp
  src/read_data.cpp
  src/reader_native.cpp
  src/reader_xyz.cpp
  src/universe.cpp
  src/utils.cpp
  src/variable.cpp
Labels: enhancement, maintenance

#1567 Collected small fixes and update for the next patch
  cmake/CMakeLists.txt
  cmake/Modules/Packages/KSPACE.cmake
  doc/src/compute.txt
  src/KOKKOS/pppm_kokkos.cpp
  src/KSPACE/pppm.cpp
  src/KSPACE/pppm.h
  src/KSPACE/pppm_disp.cpp
  src/KSPACE/pppm_disp.h
  src/PERI/atom_vec_peri.cpp
  src/atom_vec_ellipsoid.cpp
  src/utils.cpp
Labels: bugfix, cmake, communication_feature, kspace_package, rigid_package

#1574 Step version string for next patch release
  doc/lammps.1
  doc/src/Manual.txt
  src/version.h
Labels: maintenance

#1584 Correct restarting of bonded hybrid styles for table styles
  doc/src/angle_table.txt
  doc/src/bond_table.txt
  doc/src/dihedral_table.txt
  doc/src/dihedral_table_cut.txt
  src/MOLECULE/angle_table.cpp
  src/MOLECULE/angle_table.h
  src/MOLECULE/bond_table.cpp
  src/MOLECULE/bond_table.h
  src/USER-MISC/dihedral_table.cpp
  src/USER-MISC/dihedral_table.h
  src/USER-MISC/dihedral_table_cut.cpp
  src/USER-MISC/dihedral_table_cut.h
  src/angle.h
  src/angle_hybrid.cpp
  src/bond.h
  src/bond_hybrid.cpp
  src/dihedral.h
  src/dihedral_hybrid.cpp
  src/improper.h
  src/improper_hybrid.cpp
  src/pair.h
Labels: bugfix, maintenance

#1587 Fixing bug in nve/kk when using rmass.
  src/KOKKOS/fix_nve_kokkos.cpp
Labels: bugfix, kokkos_package

#1580 Fix CUDA-aware MPI issues with KOKKOS package
  doc/src/Speed_kokkos.txt
  doc/src/package.txt
  src/KOKKOS/comm_kokkos.cpp
  src/KOKKOS/gridcomm_kokkos.cpp
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/MAKE/MACHINES/Makefile.lassen_kokkos
  src/STUBS/mpi.c
  src/STUBS/mpi.h
Labels: enhancement, kokkos_package

#1588 Fix bugs with CMake potentials and frc folder installation
  cmake/CMakeLists.txt
  cmake/etc/profile.d/lammps.csh.in
  cmake/etc/profile.d/lammps.sh.in
  doc/src/Build_cmake.txt
  doc/utils/sphinx-config/false_positives.txt
Labels: cmake

#1581 Include bonds in communication cutoff estimate
  doc/src/Errors_warnings.txt
  doc/src/comm_modify.txt
  src/comm.cpp
  src/comm.h
  src/comm_brick.cpp
  src/comm_tiled.cpp
  src/info.cpp
Labels: communication_feature, enhancement, maintenance

#1548 Bond/react clarify how stabilization works
  doc/src/fix_bond_react.txt
  examples/USER/misc/bond_react/tiny_nylon/in.tiny_nylon.stabilized
  examples/USER/misc/bond_react/tiny_nylon/in.tiny_nylon.unstabilized
  examples/USER/misc/bond_react/tiny_nylon/log.20Apr18.tiny_nylon.g++.1
  examples/USER/misc/bond_react/tiny_nylon/log.20Apr18.tiny_nylon.g++.4
  examples/USER/misc/bond_react/tiny_nylon/log.5Jun19.tiny_nylon.stabilized.g++.1
  examples/USER/misc/bond_react/tiny_nylon/log.5Jun19.tiny_nylon.stabilized.g++.4
  examples/USER/misc/bond_react/tiny_nylon/log.5Jun19.tiny_nylon.unstabilized.g++.1
  examples/USER/misc/bond_react/tiny_nylon/log.5Jun19.tiny_nylon.unstabilized.g++.4
  src/USER-MISC/fix_bond_react.cpp
Labels: documentation, user_misc_package

#1557 new versions of jacobi() method
  src/math_extra.cpp
  src/math_extra.h
Labels: maintenance, rigid_package

#1511 Add keyword hybridpair for compute_pressure
  doc/src/compute_pressure.txt
  src/compute_pressure.cpp
  src/compute_pressure.h
Labels: enhancement

#1583 computing the eigenvalues of gyration tensor & shape parameters
  doc/src/Commands_compute.txt
  doc/src/Eqs/compute_shape_parameters.jpg
  doc/src/Eqs/compute_shape_parameters.tex
  doc/src/Errors_messages.txt
  doc/src/compute.txt
  doc/src/compute_gyration.txt
  doc/src/compute_gyration_shape.txt
  doc/src/computes.txt
  doc/src/lammps.book
  doc/utils/sphinx-config/false_positives.txt
  src/USER-MISC/README
  src/USER-MISC/compute_gyration_shape.cpp
  src/USER-MISC/compute_gyration_shape.h
Labels: enhancement, user_misc_package

#1529 Compute momentum
  doc/src/Commands_compute.txt
  doc/src/compute.txt
  doc/src/compute_momentum.txt
  doc/src/computes.txt
  doc/src/lammps.book
  examples/USER/misc/momentum/in.momentum
  src/USER-MISC/README
  src/USER-MISC/compute_momentum.cpp
  src/USER-MISC/compute_momentum.h
Labels: enhancement

#1512 Extend support of "rotate" keyword to all styles of "create_atoms"
  doc/src/create_atoms.txt
  src/create_atoms.cpp
Labels: enhancement

#1592 Collected small changes for next patch release
  cmake/CMakeLists.txt
  cmake/Modules/Packages/USER-PLUMED.cmake
  doc/include-file-conventions.md
  doc/src/compute_hexorder_atom.txt
  doc/src/fix_plumed.txt
  lib/plumed/Install.py
  lib/plumed/Makefile.lammps.runtime.macosx
  lib/plumed/README
  lib/vtk/Makefile.lammps.ubuntu18.04_vtk7
  src/GRANULAR/fix_pour.cpp
  src/Makefile
  src/STUBS/Makefile
  src/STUBS/mpi.c
  src/USER-MEAMC/meam.h
  src/USER-MEAMC/meam_setup_global.cpp
  src/USER-PLUMED/fix_plumed.cpp
  src/compute_chunk_spread_atom.cpp
  src/info.cpp
  src/lmptype.h
Labels: bugfix, maintenance

#1597 Fix failing regression test /examples/USER/eff/Be-solid/in.Be-solid.spe
  examples/USER/eff/Be-solid/data.Be-solid
Labels: bugfix, maintenance

#1556 more robust version of atom exchange size
  src/BODY/body_nparticle.cpp
  src/BODY/body_rounded_polygon.cpp
  src/BODY/body_rounded_polyhedron.cpp
  src/KOKKOS/fix_neigh_history_kokkos.cpp
  src/USER-OMP/fix_neigh_history_omp.cpp
  src/atom_vec.cpp
  src/atom_vec.h
  src/atom_vec_hybrid.cpp
  src/body.h
  src/comm.cpp
  src/comm.h
  src/comm_brick.cpp
  src/comm_brick.h
  src/comm_tiled.cpp
  src/comm_tiled.h
  src/fix.cpp
  src/fix.h
  src/fix_neigh_history.cpp
  src/fix_store.cpp
  src/irregular.cpp
  src/irregular.h
Labels: communication_feature, enhancement, full-regression-test, test-for-regression

#1593 Step version string for next patch release
  doc/lammps.1
  doc/src/Manual.txt
  src/version.h
Labels: maintenance

#1601 Improve compatibility to older CMake versions when building/installing LAMMPS library and headers
  cmake/CMakeLists.txt
Labels: cmake, maintenance

#1599 Collected small changes
  src/USER-PHONON/Install.sh
  src/USER-PTM/ptm_initialize_data.h
Labels: el7, full-regression-test, test-for-regression
