Repository lammps/lammps, pull requests merged in 2019-02, with the labels that each got.

#1290 Use argparse module in for Install.py scripts in lib
  cmake/CMakeLists.txt
  doc/src/Build_extras.txt
  lib/Install.py
  lib/colvars/Install.py
  lib/gpu/Install.py
  lib/gpu/README
  lib/install_helpers.py
  lib/kim/Install.py
  lib/latte/Install.py
  lib/message/Install.py
  lib/mscg/Install.py
  lib/plumed/Install.py
  lib/pylint.rc
  lib/scafacos/.gitignore
  lib/scafacos/Install.py
  lib/smd/Install.py
  lib/voronoi/Install.py
Labels: build_system, cmake

#1311 Correct calls to atom->delete_callback()
  src/REPLICA/fix_hyper_local.cpp
  src/USER-MISC/fix_ffl.cpp
  src/USER-MISC/fix_filter_corotate.cpp
Labels: bugfix

#1319 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement, github

#1316 Rename python.h to lmppython.h
  src/PYTHON/fix_python_invoke.cpp
  src/PYTHON/fix_python_move.cpp
  src/PYTHON/pair_python.cpp
  src/PYTHON/python_impl.cpp
  src/lammps.cpp
  src/lmppython.cpp
  src/lmppython.h
  src/variable.cpp
Labels: enhancement

#1322 Add a code of conduct to lammps github project
  .github/CODE_OF_CONDUCT.md
Labels: github

#1318 Updates for GitHub PR template
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE/bug_fix.md
  .github/PULL_REQUEST_TEMPLATE/maintenance_refactoring.md
  .github/PULL_REQUEST_TEMPLATE/new_feature.md
  .github/PULL_REQUEST_TEMPLATE/update_enhancement.md
  doc/github-development-workflow.md
Labels: enhancement, github

#1321 Collected small fixes for the next patch release
  doc/.gitignore
  doc/src/Install_windows.txt
  doc/src/Manual.txt
  doc/utils/sphinx-config/conf.py
  src/BODY/fix_wall_body_polygon.cpp
  src/BODY/fix_wall_body_polyhedron.cpp
  src/GPU/pair_born_coul_long_cs_gpu.cpp
  src/GPU/pair_born_coul_long_gpu.cpp
  src/GPU/pair_born_coul_wolf_cs_gpu.cpp
  src/GPU/pair_buck_coul_long_gpu.cpp
  src/GPU/pair_colloid_gpu.cpp
  src/GPU/pair_coul_long_cs_gpu.cpp
  src/GPU/pair_coul_long_gpu.cpp
  src/GPU/pair_eam_alloy_gpu.cpp
  src/GPU/pair_eam_fs_gpu.cpp
  src/GPU/pair_eam_gpu.cpp
  src/GPU/pair_gayberne_gpu.cpp
  src/GPU/pair_lj_charmm_coul_long_gpu.cpp
  src/GPU/pair_lj_class2_coul_long_gpu.cpp
  src/GPU/pair_lj_cut_coul_long_gpu.cpp
  src/GPU/pair_lj_cut_coul_msm_gpu.cpp
  src/GPU/pair_lj_cut_dipole_long_gpu.cpp
  src/GPU/pair_lj_expand_coul_long_gpu.cpp
  src/GPU/pair_mie_cut_gpu.cpp
  src/GPU/pair_morse_gpu.cpp
  src/GPU/pair_resquared_gpu.cpp
  src/GPU/pair_soft_gpu.cpp
  src/GPU/pair_table_gpu.cpp
  src/GPU/pair_ufm_gpu.cpp
  src/GPU/pair_vashishta_gpu.cpp
  src/GPU/pair_yukawa_colloid_gpu.cpp
  src/GPU/pair_yukawa_gpu.cpp
  src/GPU/pair_zbl_gpu.cpp
  src/MANYBODY/pair_bop.cpp
  src/PYTHON/pair_python.cpp
  src/USER-PTM/README
  src/USER-REAXC/fix_qeq_reax.cpp
  src/atom.cpp
  src/compute_reduce_region.cpp
  src/create_atoms.cpp
  src/lmpwindows.h
  src/pair.cpp
  src/read_data.cpp
  src/read_restart.cpp
Labels: bugfix, documentation

#1312 Update Kokkos library to v2.8.00
  lib/kokkos/CHANGELOG.md
  lib/kokkos/Makefile.kokkos
  lib/kokkos/README
  lib/kokkos/bin/nvcc_wrapper
  lib/kokkos/cmake/kokkos_options.cmake
  lib/kokkos/containers/src/Kokkos_DualView.hpp
  lib/kokkos/containers/src/Kokkos_DynRankView.hpp
  lib/kokkos/containers/unit_tests/TestDualView.hpp
  lib/kokkos/core/src/Cuda/Kokkos_CudaSpace.cpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_Impl.cpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_Parallel.hpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_ReduceScan.hpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_Team.hpp
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_Version_9_8_Compatibility.hpp
  lib/kokkos/core/src/Kokkos_CopyViews.hpp
  lib/kokkos/core/src/Kokkos_Crs.hpp
  lib/kokkos/core/src/Kokkos_Macros.hpp
  lib/kokkos/core/src/Kokkos_Parallel_Reduce.hpp
  lib/kokkos/core/src/Kokkos_View.hpp
  lib/kokkos/core/src/Threads/Kokkos_Threads_Parallel.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Compare_Exchange_Strong.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Exchange.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Add.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Fetch_And.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Or.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Fetch_Sub.hpp
  lib/kokkos/core/src/impl/Kokkos_Atomic_Generic.hpp
  lib/kokkos/core/src/impl/Kokkos_Core.cpp
  lib/kokkos/core/src/impl/Kokkos_Utilities.hpp
  lib/kokkos/core/src/impl/Kokkos_ViewArray.hpp
  lib/kokkos/core/src/impl/Kokkos_ViewMapping.hpp
  lib/kokkos/core/unit_test/TestCrs.hpp
  lib/kokkos/core/unit_test/TestMDRange.hpp
  lib/kokkos/core/unit_test/TestMDRange_d.hpp
  lib/kokkos/core/unit_test/TestRange.hpp
  lib/kokkos/core/unit_test/TestTeamVector.hpp
  lib/kokkos/core/unit_test/TestViewCopy.hpp
  lib/kokkos/core/unit_test/TestViewMapping_a.hpp
  lib/kokkos/core/unit_test/cuda/TestCuda_Spaces.cpp
  lib/kokkos/core/unit_test/openmp/TestOpenMP_ViewAPI_e.cpp
  lib/kokkos/core/unit_test/serial/TestSerial_ViewAPI_e.cpp
  lib/kokkos/core/unit_test/threads/TestThreads_ViewAPI_e.cpp
  lib/kokkos/generate_makefile.bash
  lib/kokkos/master_history.txt
  lib/kokkos/scripts/testing_scripts/test_all_sandia
Labels: bugfix, kokkos_package

#1306 Add Kokkos version of angle/cosine
  doc/src/Commands_bond.txt
  doc/src/angle_cosine.txt
  src/KOKKOS/Install.sh
  src/KOKKOS/angle_cosine_kokkos.cpp
  src/KOKKOS/angle_cosine_kokkos.h
  src/MOLECULE/angle_cosine.cpp
  src/MOLECULE/angle_cosine.h
Labels: enhancement, kokkos_package

#1323 Patch release 8 February 2019
  .github/PULL_REQUEST_TEMPLATE.md
  doc/src/Manual.txt
  src/version.h
Labels: update

#1325 allowing shrink wrap with comm tiled
  src/read_data.cpp
Labels: communication_feature, enhancement

#1272 Add library of utility functions to make LAMMPS code simpler and more consistent
  src/GPU/fix_gpu.cpp
  src/GPU/pair_eam_alloy_gpu.cpp
  src/MANYBODY/fix_qeq_comb.cpp
  src/MANYBODY/pair_adp.cpp
  src/MANYBODY/pair_adp.h
  src/MANYBODY/pair_airebo.cpp
  src/MC/fix_gcmc.cpp
  src/MOLECULE/angle_table.cpp
  src/MOLECULE/bond_table.cpp
  src/REPLICA/verlet_split.cpp
  src/USER-INTEL/verlet_lrt_intel.cpp
  src/USER-MISC/dihedral_table.cpp
  src/USER-MISC/dihedral_table_cut.cpp
  src/compute_group_group.cpp
  src/compute_reduce.cpp
  src/finish.cpp
  src/force.cpp
  src/pair.cpp
  src/pair_table.cpp
  src/utils.cpp
  src/utils.h
  src/write_coeff.cpp
Labels: enhancement

#1331 Collected small changes
  cmake/CMakeLists.txt
  doc/src/Build_basics.txt
  doc/src/Build_extras.txt
  doc/src/fix_wall_gran_region.txt
  doc/utils/sphinx-config/false_positives.txt
  lib/voronoi/Install.py
  src/GPU/fix_gpu.cpp
  src/GPU/pair_beck_gpu.cpp
  src/GPU/pair_born_coul_wolf_gpu.cpp
  src/GPU/pair_born_gpu.cpp
  src/GPU/pair_buck_coul_cut_gpu.cpp
  src/GPU/pair_buck_gpu.cpp
  src/GPU/pair_coul_cut_gpu.cpp
  src/GPU/pair_coul_debye_gpu.cpp
  src/GPU/pair_coul_dsf_gpu.cpp
  src/GPU/pair_dpd_gpu.cpp
  src/GPU/pair_dpd_tstat_gpu.cpp
  src/GPU/pair_gauss_gpu.cpp
  src/GPU/pair_lj96_cut_gpu.cpp
  src/GPU/pair_lj_class2_gpu.cpp
  src/GPU/pair_lj_cubic_gpu.cpp
  src/GPU/pair_lj_cut_coul_cut_gpu.cpp
  src/GPU/pair_lj_cut_coul_debye_gpu.cpp
  src/GPU/pair_lj_cut_coul_dsf_gpu.cpp
  src/GPU/pair_lj_cut_gpu.cpp
  src/GPU/pair_lj_expand_gpu.cpp
  src/GPU/pair_lj_gromacs_gpu.cpp
  src/MANYBODY/pair_airebo.cpp
  src/USER-MISC/fix_ave_correlate_long.cpp
  src/USER-MISC/fix_ave_correlate_long.h
  src/USER-MISC/pair_extep.cpp
  src/USER-MISC/pair_lebedeva_z.cpp
  src/USER-MOLFILE/reader_molfile.cpp
  src/USER-OMP/fix_gravity_omp.cpp
  src/USER-OMP/fix_nve_omp.cpp
  src/USER-OMP/fix_nve_sphere_omp.cpp
  src/USER-OMP/fix_qeq_comb_omp.cpp
  src/USER-OMP/fix_qeq_reax_omp.cpp
  src/USER-OMP/fix_wall_gran_omp.cpp
  src/USER-OMP/hack_openmp_for_pgi.sh
  src/USER-OMP/hack_openmp_for_pgi_gcc9.sh
  src/USER-OMP/pair_airebo_omp.cpp
  src/USER-OMP/pair_rebo_omp.cpp
  src/USER-UEF/uef_utils.h
  src/USER-YAFF/angle_cross.cpp
  src/USER-YAFF/angle_mm3.cpp
  src/USER-YAFF/bond_mm3.cpp
  src/USER-YAFF/pair_lj_switch3_coulgauss_long.cpp
  src/USER-YAFF/pair_mm3_switch3_coulgauss_long.cpp
  src/info.cpp
  src/info.h
  src/lammps.cpp
Labels: enhancement, maintenance

#1332 Bond/react c++11 compliance
  src/USER-MISC/fix_bond_react.cpp
Labels: bugfix, user_misc_package

#1333 Bond/react: revert bond-forming reaction behavior
  doc/src/fix_bond_react.txt
  src/USER-MISC/fix_bond_react.cpp
Labels: enhancement, user_misc_package

#1338 revert broken changes to compute reduce
  src/compute_reduce.cpp
Labels: bugfix, full-regression-test, test-for-regression

#1341 Fixes part of issue #1278
  cmake/Modules/StyleHeaderUtils.cmake
Labels: build_system, cmake

#1339 USER-PTM package update
  doc/src/compute_ptm_atom.txt
  examples/USER/ptm/ptm_example.in
  src/USER-PTM/README
  src/USER-PTM/compute_ptm_atom.cpp
  src/USER-PTM/ptm_alloy_types.cpp
  src/USER-PTM/ptm_alloy_types.h
  src/USER-PTM/ptm_alt_templates.h
  src/USER-PTM/ptm_canonical_coloured.cpp
  src/USER-PTM/ptm_canonical_coloured.h
  src/USER-PTM/ptm_constants.h
  src/USER-PTM/ptm_convex_hull_incremental.cpp
  src/USER-PTM/ptm_convex_hull_incremental.h
  src/USER-PTM/ptm_deformation_gradient.cpp
  src/USER-PTM/ptm_deformation_gradient.h
  src/USER-PTM/ptm_functions.h
  src/USER-PTM/ptm_fundamental_mappings.h
  src/USER-PTM/ptm_graph_data.cpp
  src/USER-PTM/ptm_graph_data.h
  src/USER-PTM/ptm_graph_tools.cpp
  src/USER-PTM/ptm_graph_tools.h
  src/USER-PTM/ptm_index.cpp
  src/USER-PTM/ptm_initialize_data.cpp
  src/USER-PTM/ptm_initialize_data.h
  src/USER-PTM/ptm_neighbour_ordering.cpp
  src/USER-PTM/ptm_neighbour_ordering.h
  src/USER-PTM/ptm_normalize_vertices.cpp
  src/USER-PTM/ptm_normalize_vertices.h
  src/USER-PTM/ptm_polar.cpp
  src/USER-PTM/ptm_polar.h
  src/USER-PTM/ptm_quat.cpp
  src/USER-PTM/ptm_quat.h
  src/USER-PTM/ptm_structure_matcher.cpp
  src/USER-PTM/ptm_structure_matcher.h
  src/USER-PTM/ptm_voronoi_cell.cpp
  src/USER-PTM/ptm_voronoi_cell.h
  src/USER-PTM/ptm_voronoi_config.h
Labels: documentation, enhancement, update

#1335 correct fix langevin with tally yes zero yes
  doc/src/Errors_warnings.txt
  doc/src/fix_langevin.txt
  src/fix_langevin.cpp
  src/fix_langevin.h
Labels: enhancement

#1011 KIM v2 update
  cmake/CMakeLists.txt
  cmake/Modules/FindKIM-API-V2.cmake
  cmake/Modules/FindKIM.cmake
  doc/src/Build_extras.txt
  doc/src/Errors_messages.txt
  doc/src/Packages_details.txt
  doc/src/fix_adapt.txt
  doc/src/pair_kim.txt
  doc/utils/sphinx-config/false_positives.txt
  examples/kim/in.kim.lj.lmp.newton-off
  examples/kim/in.kim.lj.lmp.newton-on
  examples/kim/in.kim.lj.newton-off
  examples/kim/in.kim.lj.newton-on
  examples/kim/log.06Feb2019.in.kim.lj.lmp.newton-off.1
  examples/kim/log.06Feb2019.in.kim.lj.lmp.newton-off.4
  examples/kim/log.06Feb2019.in.kim.lj.lmp.newton-on.1
  examples/kim/log.06Feb2019.in.kim.lj.lmp.newton-on.4
  examples/kim/log.06Feb2019.in.kim.lj.newton-off.1
  examples/kim/log.06Feb2019.in.kim.lj.newton-off.4
  examples/kim/log.06Feb2019.in.kim.lj.newton-on.1
  examples/kim/log.06Feb2019.in.kim.lj.newton-on.4
  examples/kim/log.28Jun15.kim.lj.lmp.ubuntu.1
  examples/kim/log.28Jun15.kim.lj.lmp.ubuntu.4
  examples/kim/log.28Jun15.kim.lj.ubuntu.1
  examples/kim/log.28Jun15.kim.lj.ubuntu.4
  lib/kim/.gitignore
  lib/kim/Install.py
  lib/kim/Makefile.lammps
  lib/kim/README
  src/KIM/README
  src/KIM/pair_kim.cpp
  src/KIM/pair_kim.h
Labels: enhancement, kim_package

#1344 Fixed bug in lammps_scatter_atoms_subset...
  src/library.cpp
Labels: bugfix, library_interface

#1348 Optimization for create_atoms with regions (2nd attempt)
  src/create_atoms.cpp
Labels: enhancement

#1315 Fix python install for Mac Os
  python/lammps.py
Labels: bugfix, python_module, work_in_progress

#1340 Bonus data checks and updates
  src/atom.cpp
  src/atom.h
  src/atom_vec_body.cpp
  src/atom_vec_body.h
  src/atom_vec_ellipsoid.cpp
  src/atom_vec_ellipsoid.h
  src/atom_vec_line.cpp
  src/atom_vec_line.h
  src/atom_vec_tri.cpp
  src/atom_vec_tri.h
  src/delete_atoms.cpp
  src/read_data.cpp
  src/set.cpp
  src/write_data.cpp
Labels: bugfix, enhancement

#1347 Collected small fixes for the next patch release
  .github/ISSUE_TEMPLATE/generic.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  doc/src/compute_group_group.txt
  examples/USER/qtb/methane_qbmsst/methane_qtb.mod
  examples/USER/qtb/methane_qtb/methane_qtb.in
  src/atom.cpp
  src/variable.cpp
Labels: bugfix

#1351 Bump KIM API version to 2.0.1
  cmake/CMakeLists.txt
  lib/kim/Install.py
Labels: kim_package, update

#1317 USER-ADIOS package with ADIOS 2.x
  cmake/CMakeLists.txt
  doc/src/Build_extras.txt
  doc/src/Build_package.txt
  doc/src/Commands_all.txt
  doc/src/Packages_details.txt
  doc/src/Packages_user.txt
  doc/src/commands_list.txt
  doc/src/dump.txt
  doc/src/dump_adios.txt
  doc/src/lammps.book
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/adios/adios2_config.xml
  examples/USER/adios/in.adios_balance
  examples/USER/adios/log.balance
  src/Makefile
  src/USER-ADIOS/Install.sh
  src/USER-ADIOS/README
  src/USER-ADIOS/dump_atom_adios.cpp
  src/USER-ADIOS/dump_atom_adios.h
  src/USER-ADIOS/dump_custom_adios.cpp
  src/USER-ADIOS/dump_custom_adios.h
Labels: dump_feature

#1314 Optimized Dynamical Matrix command
  doc/src/Commands_all.txt
  doc/src/Packages_details.txt
  doc/src/commands_list.txt
  doc/src/dynamical_matrix.txt
  doc/src/fix_phonon.txt
  doc/src/lammps.book
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/phonon/dynamical_matrix_command/Silicon/README.md
  examples/USER/phonon/dynamical_matrix_command/Silicon/Si.opt.tersoff
  examples/USER/phonon/dynamical_matrix_command/Silicon/ff-silicon.lmp
  examples/USER/phonon/dynamical_matrix_command/Silicon/in.silicon
  examples/USER/phonon/dynamical_matrix_command/Silicon/lmp_bank/amorphous_silicon.lmp
  examples/USER/phonon/dynamical_matrix_command/Silicon/lmp_bank/silicon_216.lmp
  examples/USER/phonon/dynamical_matrix_command/Silicon/lmp_bank/silicon_512.lmp
  examples/USER/phonon/dynamical_matrix_command/Silicon/lmp_bank/silicon_8.lmp
  examples/USER/phonon/dynamical_matrix_command/Silicon/results/dynmat.dat
  examples/USER/phonon/dynamical_matrix_command/Silicon/results/out.silicon
  examples/USER/phonon/dynamical_matrix_command/Silicon/silicon_input_file.lmp
  src/USER-PHONON/Install.sh
  src/USER-PHONON/README
  src/USER-PHONON/dynamical_matrix.cpp
  src/USER-PHONON/dynamical_matrix.h
Labels: enhancement

#1350 Step version string for next patch release
  doc/src/Manual.txt
  src/version.h
Labels: update
