Repository lammps/lammps, pull requests merged in 2020-01, with the labels that each got.

#1798 Collected MEAM/C additions
  doc/src/pair_meamc.rst
  doc/txt/pair_meamc.txt
  src/USER-MEAMC/meam.h
  src/USER-MEAMC/meam_dens_final.cpp
  src/USER-MEAMC/meam_dens_init.cpp
  src/USER-MEAMC/meam_force.cpp
  src/USER-MEAMC/meam_funcs.cpp
  src/USER-MEAMC/meam_impl.cpp
  src/USER-MEAMC/meam_setup_done.cpp
  src/USER-MEAMC/meam_setup_global.cpp
  src/USER-MEAMC/meam_setup_param.cpp
  src/USER-MEAMC/pair_meamc.cpp
  src/USER-MEAMC/pair_meamc.h
  src/math_special.cpp
Labels: enhancement

#1783 add force modifications in dynamical_matrix.cpp
  src/USER-PHONON/dynamical_matrix.cpp
Labels: enhancement

#1800 Correct typo in pair_granular.rst
  doc/src/pair_granular.rst
Labels: bugfix, documentation

#1819 Find parallel NetCDF with cmake for USER-NETCDF
  cmake/Modules/FindNetCDF.cmake
  cmake/Modules/FindPNetCDF.cmake
  cmake/Modules/Packages/USER-NETCDF.cmake
Labels: cmake

#1824 Updated Makefile.stampede: replacement options icc
  src/MAKE/MACHINES/Makefile.stampede
Labels: build_system

#1801 enable fix rigid commands to add gravity to COM of rigid bodies
  examples/rigid/in.rigid.gravity
  examples/rigid/molecule.data
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid.h
  src/RIGID/fix_rigid_small.cpp
  src/RIGID/fix_rigid_small.h
  src/USER-OMP/fix_rigid_nh_omp.cpp
  src/USER-OMP/fix_rigid_omp.cpp
  src/USER-OMP/fix_rigid_small_omp.cpp
  src/fix_gravity.cpp
  src/fix_gravity.h
Labels: enhancement, rigid_package, user_omp_package

#1776 GPU support for lj/cut/tip4p/long pair style
  doc/src/pair_lj.rst
  examples/TIP4P/gpu_dump/data.spce
  examples/TIP4P/gpu_dump/dump.force_cpu.19Dec19.tip4p.g++.1
  examples/TIP4P/gpu_dump/dump.force_gpu.19Dec19.tip4p.g++.1.gtx1070.dp
  examples/TIP4P/gpu_dump/in.tip4p
  examples/TIP4P/gpu_dump/log.19Dec19.tip4p.g++.1
  examples/TIP4P/gpu_dump/log.19Dec19.tip4p.g++.1.gtx1070.dp
  lib/gpu/Nvidia.makefile
  lib/gpu/Opencl.makefile
  lib/gpu/lal_lj_tip4p_long.cpp
  lib/gpu/lal_lj_tip4p_long.cu
  lib/gpu/lal_lj_tip4p_long.h
  lib/gpu/lal_lj_tip4p_long_ext.cpp
  src/GPU/Install.sh
  src/GPU/pair_lj_cut_tip4p_long_gpu.cpp
  src/GPU/pair_lj_cut_tip4p_long_gpu.h
  src/atom.h
Labels: enhancement, gpu_package

#1752 Fixed bugs with kernel (re)compiling when the global device got clear and reinitialized
  lib/gpu/lal_base_atomic.cpp
  lib/gpu/lal_base_charge.cpp
  lib/gpu/lal_base_dipole.cpp
  lib/gpu/lal_base_dpd.cpp
  lib/gpu/lal_base_ellipsoid.cpp
  lib/gpu/lal_base_three.cpp
Labels: bugfix, gpu_package

#1817 Collected small bugfixes and updates
  .github/CODEOWNERS
  doc/src/fix_ave_atom.rst
  doc/txt/fix_ave_atom.txt
  lib/gpu/geryon/ocl_device.h
  lib/gpu/geryon/ocl_macros.h
  potentials/AlCu.bop.table
  src/CLASS2/pair_lj_class2_coul_long.cpp
  src/GPU/fix_gpu.cpp
  src/USER-INTEL/fix_intel.cpp
  src/USER-INTEL/fix_intel.h
  src/USER-INTEL/nbin_intel.cpp
  src/USER-INTEL/pair_lj_cut_coul_long_intel.cpp
  src/USER-INTEL/pair_lj_cut_intel.cpp
  src/USER-MEAMC/pair_meamc.cpp
  src/USER-OMP/fix_rigid_omp.cpp
  src/USER-OMP/fix_rigid_small_omp.cpp
  src/USER-PHONON/dynamical_matrix.cpp
  src/pair.h
  src/read_dump.cpp
Labels: bugfix, enhancement, gpu_package, kspace_package, user_intel_package

#1825 Step version string for next patch release
  doc/lammps.1
  lib/gpu/lal_lj_tip4p_long.cpp
  lib/gpu/lal_lj_tip4p_long.cu
  lib/gpu/lal_lj_tip4p_long.h
  lib/gpu/lal_lj_tip4p_long_ext.cpp
  src/GPU/pair_lj_cut_tip4p_long_gpu.cpp
  src/fix_gravity.cpp
  src/version.h
Labels: maintenance

#1830 add warning to fix bond/create
  doc/src/Errors_warnings.rst
  doc/txt/Errors_warnings.txt
  src/MC/fix_bond_break.cpp
  src/MC/fix_bond_create.cpp
  src/MC/fix_bond_create.h
Labels: maintenance

#1829 added rerun example dir
  doc/src/Examples.rst
  doc/txt/Examples.txt
  examples/README
  examples/rerun/README
  examples/rerun/in.first
  examples/rerun/in.rdf.first
  examples/rerun/in.rdf.rerun
  examples/rerun/in.read_dump
  examples/rerun/in.rerun
  examples/rerun/log.09Jan20.first.g++.4
  examples/rerun/log.09Jan20.rdf.first.g++.4
  examples/rerun/log.09Jan20.rdf.rerun.g++.4
  examples/rerun/log.09Jan20.read_dump.g++.4
  examples/rerun/log.09Jan20.rerun.g++.4
  examples/rerun/rdf.09Jan20.first.g++.4
  examples/rerun/rdf.09Jan20.rerun.g++.4
Labels: documentation

#1828 minor omissions in recent patch release
  doc/src/Build_extras.rst
  doc/src/Commands_all.rst
  doc/src/Commands_bond.rst
  doc/src/Commands_fix.rst
  doc/src/Commands_kspace.rst
  doc/src/Commands_pair.rst
  doc/src/Packages_details.rst
  doc/src/kspace_style.rst
  doc/src/pair_lj.rst
  doc/src/pair_lj_switch3_coulgauss_long.rst
  doc/src/pair_mm3_switch3_coulgauss_long.rst
  doc/src/pair_style.rst
  doc/txt/fix_nve_dot.txt
  doc/txt/fix_nve_dotc_langevin.txt
  doc/txt/pair_meamc.txt
  doc/txt/pair_mm3_switch3_coulgauss.txt
  doc/txt/pair_oxdna.txt
  doc/txt/pair_oxdna2.txt
  examples/README
Labels: documentation, maintenance

#1834 Small Suffix flag refactoring and disallow per substyle special overrides for USER-INTEL and GPU
  doc/src/pair_modify.rst
  doc/txt/pair_modify.txt
  src/GPU/pair_beck_gpu.cpp
  src/GPU/pair_born_coul_long_cs_gpu.cpp
  src/GPU/pair_born_coul_long_gpu.cpp
  src/GPU/pair_born_coul_wolf_cs_gpu.cpp
  src/GPU/pair_born_coul_wolf_gpu.cpp
  src/GPU/pair_born_gpu.cpp
  src/GPU/pair_buck_coul_cut_gpu.cpp
  src/GPU/pair_buck_coul_long_gpu.cpp
  src/GPU/pair_buck_gpu.cpp
  src/GPU/pair_colloid_gpu.cpp
  src/GPU/pair_coul_cut_gpu.cpp
  src/GPU/pair_coul_debye_gpu.cpp
  src/GPU/pair_coul_dsf_gpu.cpp
  src/GPU/pair_coul_long_cs_gpu.cpp
  src/GPU/pair_coul_long_gpu.cpp
  src/GPU/pair_dpd_gpu.cpp
  src/GPU/pair_dpd_tstat_gpu.cpp
  src/GPU/pair_eam_alloy_gpu.cpp
  src/GPU/pair_eam_fs_gpu.cpp
  src/GPU/pair_eam_gpu.cpp
  src/GPU/pair_gauss_gpu.cpp
  src/GPU/pair_gayberne_gpu.cpp
  src/GPU/pair_lj96_cut_gpu.cpp
  src/GPU/pair_lj_charmm_coul_long_gpu.cpp
  src/GPU/pair_lj_class2_coul_long_gpu.cpp
  src/GPU/pair_lj_class2_gpu.cpp
  src/GPU/pair_lj_cubic_gpu.cpp
  src/GPU/pair_lj_cut_coul_cut_gpu.cpp
  src/GPU/pair_lj_cut_coul_debye_gpu.cpp
  src/GPU/pair_lj_cut_coul_dsf_gpu.cpp
  src/GPU/pair_lj_cut_coul_long_gpu.cpp
  src/GPU/pair_lj_cut_coul_msm_gpu.cpp
  src/GPU/pair_lj_cut_dipole_cut_gpu.cpp
  src/GPU/pair_lj_cut_dipole_long_gpu.cpp
  src/GPU/pair_lj_cut_gpu.cpp
  src/GPU/pair_lj_cut_tip4p_long_gpu.cpp
  src/GPU/pair_lj_expand_coul_long_gpu.cpp
  src/GPU/pair_lj_expand_gpu.cpp
  src/GPU/pair_lj_gromacs_gpu.cpp
  src/GPU/pair_lj_sdk_coul_long_gpu.cpp
  src/GPU/pair_lj_sdk_gpu.cpp
  src/GPU/pair_lj_sf_dipole_sf_gpu.cpp
  src/GPU/pair_mie_cut_gpu.cpp
  src/GPU/pair_morse_gpu.cpp
  src/GPU/pair_resquared_gpu.cpp
  src/GPU/pair_soft_gpu.cpp
  src/GPU/pair_sw_gpu.cpp
  src/GPU/pair_table_gpu.cpp
  src/GPU/pair_tersoff_gpu.cpp
  src/GPU/pair_tersoff_mod_gpu.cpp
  src/GPU/pair_tersoff_zbl_gpu.cpp
  src/GPU/pair_ufm_gpu.cpp
  src/GPU/pair_vashishta_gpu.cpp
  src/GPU/pair_yukawa_colloid_gpu.cpp
  src/GPU/pair_yukawa_gpu.cpp
  src/GPU/pair_zbl_gpu.cpp
  src/pair_hybrid.cpp
  src/suffix.h
Labels: bugfix, enhancement, gpu_package

#1832 Check style command lists against existing styles in sources
  doc/Makefile
  doc/src/Manual_build.rst
  doc/src/bond_style.rst
  doc/src/fix.rst
  doc/src/kspace_style.rst
  doc/src/pair_style.rst
  doc/txt/kspace_style.txt
  doc/txt/pair_style.txt
  doc/utils/check-styles.py
  doc/utils/converters/lammpsdoc/rst_anchor_check.py
  src/MC/fix_bond_break.cpp
  src/MC/fix_bond_create.cpp
Labels: documentation, maintenance

#1685 Added New keywords rotation rx ry rz to fix_deposit
  doc/src/fix_deposit.rst
  doc/txt/Packages_details.txt
  doc/txt/fix.txt
  doc/txt/fix_deposit.txt
  doc/txt/pair_lj_switch3_coulgauss.txt
  doc/utils/sphinx-config/false_positives.txt
  src/MISC/fix_deposit.cpp
  src/MISC/fix_deposit.h
Labels: documentation, enhancement

#1835 Message iterate
  doc/src/Howto_client_server.rst
  doc/src/fix_client_md.rst
  doc/src/message.rst
  doc/src/server.rst
  doc/txt/Howto_client_server.txt
  doc/txt/fix_client_md.txt
  doc/txt/message.txt
  doc/txt/server.txt
  examples/COUPLE/lammps_vasp/in.client.W
  examples/message/in.message.client
  examples/message/in.message.tilt.client
  src/MESSAGE/fix_client_md.cpp
  src/MESSAGE/message.cpp
  src/MESSAGE/message.h
Labels: enhancement

#1838 enhanced stochastic wall example
  examples/README
  examples/wall/in.shearflow
  examples/wall/in.wall.ccl
  examples/wall/in.wall.diffusive
  examples/wall/in.wall.maxwell
  examples/wall/in.wall.specular
  examples/wall/log.9Jan20.wall.ccl.g++.1
  examples/wall/log.9Jan20.wall.ccl.g++.4
  examples/wall/log.9Jan20.wall.diffusive.g++.1
  examples/wall/log.9Jan20.wall.diffusive.g++.4
  examples/wall/log.9Jan20.wall.maxwell.g++.1
  examples/wall/log.9Jan20.wall.maxwell.g++.4
  examples/wall/log.9Jan20.wall.specular.g++.1
  examples/wall/log.9Jan20.wall.specular.g++.4
  src/USER-MISC/fix_wall_reflect_stochastic.cpp
  src/random_mars.cpp
Labels: bugfix, enhancement

#1837 Collected small changes for the next patch release
  .github/CONTRIBUTING.md
  cmake/CMakeLists.txt
  doc/github-development-workflow.md
  doc/src/Howto_library.rst
  doc/src/python.rst
  doc/txt/Errors_messages.txt
  doc/txt/Errors_warnings.txt
  doc/txt/Howto_library.txt
  doc/txt/fix_bond_react.txt
  doc/txt/fix_wall_reflect.txt
  doc/txt/pair_granular.txt
  doc/txt/pair_lj.txt
  doc/txt/python.txt
  potentials/Si.tersoff.modc
  potentials/SiC_Erhart-Albe.tersoff
  potentials/TiO.meam.spline
  src/USER-MEAMC/meam_funcs.cpp
  src/USER-MEAMC/meam_setup_done.cpp
  src/comm.cpp
Labels: documentation, maintenance

#1831 Correct some issues with pair style bop and its potential files
  potentials/AlCu.bop.table
  potentials/AlCuH.bop.table
  potentials/CdTeSe.bop.table
  potentials/CdZnTe_v1.bop.table
  potentials/CdZnTe_v2.bop.table
  src/.gitignore
  src/MANYBODY/pair_bop.cpp
Labels: bugfix, manybody_package

#1843 New ILP paramters
  doc/src/Commands_fix.rst
  doc/src/pair_ilp_graphene_hbn.rst
  doc/src/pair_kolmogorov_crespi_full.rst
  doc/txt/pair_ilp_graphene_hbn.txt
  doc/txt/pair_kolmogorov_crespi_full.txt
  potentials/BNCH-old.ILP
  potentials/BNCH.ILP
  potentials/BNC_MBD_bulk.ILP
  potentials/BNC_TS_bulk.ILP
  src/USER-MISC/pair_ilp_graphene_hbn.cpp
  src/USER-MISC/pair_kolmogorov_crespi_full.cpp
Labels: enhancement, update

#1848 Fix some issues with lj/cut/tip4p/long/gpu
  doc/src/pair_lj.rst
  lib/gpu/lal_lj_tip4p_long.cpp
  lib/gpu/lal_lj_tip4p_long.cu
  lib/gpu/lal_lj_tip4p_long.h
  src/GPU/Install.sh
Labels: bugfix, documentation, enhancement, gpu_package

#1820 Support read_dump with dump style 'adios'
  doc/src/Commands_all.rst
  doc/src/Packages_details.rst
  doc/src/dump.rst
  doc/src/dump_adios.rst
  doc/src/read_dump.rst
  doc/src/rerun.rst
  examples/USER/adios/balance/adios2_config.xml
  examples/USER/adios/balance/in.adios_balance
  examples/USER/adios/balance/in.adios_balance2
  examples/USER/adios/balance/log.balance
  examples/USER/adios/rerun/README
  examples/USER/adios/rerun/adios2_config.xml
  examples/USER/adios/rerun/in.first
  examples/USER/adios/rerun/in.read_dump
  examples/USER/adios/rerun/in.rerun
  examples/USER/adios/rerun/log.20Jan20.first.g++.7.4
  examples/USER/adios/rerun/log.20Jan20.read_dump.g++.7.4
  examples/USER/adios/rerun/log.20Jan20.rerun.g++.7.4
  src/USER-ADIOS/README
  src/USER-ADIOS/dump_atom_adios.cpp
  src/USER-ADIOS/dump_custom_adios.cpp
  src/USER-ADIOS/reader_adios.cpp
  src/USER-ADIOS/reader_adios.h
  src/read_dump.cpp
  src/read_dump.h
Labels: update

#1847 Fix propel/self
  doc/src/Commands_fix.rst
  doc/src/fix.rst
  doc/src/fix_propel_self.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/USER/misc/propel_self/2d_velocity/in.2d_langevin
  examples/USER/misc/propel_self/2d_velocity/in.2d_viscous
  examples/USER/misc/propel_self/3d_quaternion/in.3d_quaternion
  src/MAKE/OPTIONS/Makefile.kokkos_cuda_mpi
  src/USER-MISC/README
  src/USER-MISC/fix_propel_self.cpp
  src/USER-MISC/fix_propel_self.h
Labels: enhancement, user_misc_package

#1845 Collected small changes for next patch release
  doc/src/Commands_all.rst
  doc/src/Commands_bond.rst
  doc/src/Commands_compute.rst
  doc/src/Commands_fix.rst
  doc/src/Commands_kspace.rst
  doc/src/Commands_pair.rst
  doc/src/_ext/table_from_list.py
  doc/src/pair_lj.rst
  doc/src/read_dump.rst
  python/lammps.py
  src/GPU/pair_eam_alloy_gpu.cpp
  src/GPU/pair_eam_fs_gpu.cpp
  src/GPU/pair_eam_gpu.cpp
  src/MANYBODY/pair_eam.cpp
  src/MANYBODY/pair_eam.h
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid_small.cpp
  src/USER-MISC/fix_wall_reflect_stochastic.cpp
  src/USER-MISC/pair_e3b.cpp
  src/USER-MISC/pair_mesocnt.cpp
  src/comm.cpp
  src/create_atoms.cpp
  src/fix_gravity.cpp
  src/fix_wall_reflect.cpp
  src/pair.cpp
Labels: bugfix, documentation, maintenance

#1850 move two_charge_force calc to occur at init, not constructor
  src/KOKKOS/pppm_kokkos.cpp
  src/KSPACE/ewald.cpp
  src/KSPACE/ewald_dipole.cpp
  src/KSPACE/ewald_dipole_spin.cpp
  src/KSPACE/msm.cpp
  src/KSPACE/pppm.cpp
  src/KSPACE/pppm_dipole.cpp
  src/KSPACE/pppm_dipole_spin.cpp
  src/KSPACE/pppm_disp.cpp
  src/USER-MISC/pair_extep.cpp
  src/kspace.cpp
  src/kspace.h
Labels: bugfix, kspace_package, user_misc_package

#603 add exactly N particles to available lattice points
  doc/src/Errors_messages.rst
  doc/src/Errors_warnings.rst
  doc/src/create_atoms.rst
  doc/src/set.rst
  doc/txt/create_atoms.txt
  src/atom_vec.cpp
  src/atom_vec.h
  src/create_atoms.cpp
  src/create_atoms.h
  src/random_mars.cpp
  src/random_mars.h
  src/read_data.cpp
  src/read_restart.cpp
  src/replicate.cpp
  src/set.cpp
  src/set.h
Labels: documentation, enhancement

#1852 Add unit conversion in setup() in fix_langevin.cpp
  src/fix_langevin.cpp
Labels: bugfix

#1853 Collected small changes and bugfixes for the next patch release
  doc/src/Errors_messages.rst
  doc/src/Howto_bash.rst
  doc/src/compute_angle_local.rst
  doc/src/compute_bond_local.rst
  doc/src/compute_chunk_spread_atom.rst
  doc/src/compute_dihedral_local.rst
  doc/src/compute_displace_atom.rst
  doc/src/fix_ave_chunk.rst
  doc/txt/Howto_bash.txt
  doc/txt/compute_angle_local.txt
  doc/txt/compute_bond_local.txt
  doc/txt/compute_chunk_spread_atom.txt
  doc/txt/compute_dihedral_local.txt
  doc/txt/compute_displace_atom.txt
  doc/txt/fix_ave_chunk.txt
  src/KSPACE/ewald_disp.cpp
  src/MAKE/OPTIONS/Makefile.kokkos_cuda_mpi
  src/USER-MISC/fix_bond_react.cpp
  src/USER-MISC/fix_bond_react.h
  src/compute_global_atom.cpp
  src/image.cpp
  src/kspace.cpp
Labels: bugfix, documentation

#1854 Update version string for the next patch release
  doc/lammps.1
  src/version.h
Labels: maintenance

#1859 Update Colvars library to version 2020-01-27
  doc/src/PDF/colvars-refman-lammps.pdf
  lib/colvars/Makefile.common
  lib/colvars/Makefile.deps
  lib/colvars/colvar.cpp
  lib/colvars/colvar.h
  lib/colvars/colvar_UIestimator.h
  lib/colvars/colvar_arithmeticpath.h
  lib/colvars/colvar_geometricpath.h
  lib/colvars/colvaratoms.cpp
  lib/colvars/colvaratoms.h
  lib/colvars/colvarbias.cpp
  lib/colvars/colvarbias.h
  lib/colvars/colvarbias_abf.cpp
  lib/colvars/colvarbias_abf.h
  lib/colvars/colvarbias_alb.cpp
  lib/colvars/colvarbias_alb.h
  lib/colvars/colvarbias_histogram.cpp
  lib/colvars/colvarbias_histogram.h
  lib/colvars/colvarbias_meta.cpp
  lib/colvars/colvarbias_meta.h
  lib/colvars/colvarbias_restraint.cpp
  lib/colvars/colvarbias_restraint.h
  lib/colvars/colvarcomp.cpp
  lib/colvars/colvarcomp.h
  lib/colvars/colvarcomp_angles.cpp
  lib/colvars/colvarcomp_apath.cpp
  lib/colvars/colvarcomp_coordnums.cpp
  lib/colvars/colvarcomp_distances.cpp
  lib/colvars/colvarcomp_gpath.cpp
  lib/colvars/colvarcomp_protein.cpp
  lib/colvars/colvarcomp_rotations.cpp
  lib/colvars/colvardeps.cpp
  lib/colvars/colvardeps.h
  lib/colvars/colvargrid.cpp
  lib/colvars/colvargrid.h
  lib/colvars/colvarmodule.cpp
  lib/colvars/colvarmodule.h
  lib/colvars/colvarparams.cpp
  lib/colvars/colvarparams.h
  lib/colvars/colvarparse.cpp
  lib/colvars/colvarparse.h
  lib/colvars/colvarproxy.cpp
  lib/colvars/colvarproxy.h
  lib/colvars/colvarproxy_replicas.cpp
  lib/colvars/colvars_version.h
  lib/colvars/colvarscript.cpp
  lib/colvars/colvarscript.h
  lib/colvars/colvartypes.cpp
  lib/colvars/colvartypes.h
  lib/colvars/colvarvalue.cpp
  lib/colvars/colvarvalue.h
  src/USER-COLVARS/colvarproxy_lammps.cpp
  src/USER-COLVARS/colvarproxy_lammps.h
  src/USER-COLVARS/colvarproxy_lammps_version.h
  src/USER-COLVARS/fix_colvars.cpp
  src/USER-COLVARS/fix_colvars.h
Labels: bugfix, test-for-regression, user_colvars_package

#1861 Documentation link formatting cleanup and fixup
  doc/src/Intro_features.rst
  doc/src/Packages_details.rst
  doc/src/angle_cosine_buck6d.rst
  doc/src/angle_cosine_shift.rst
  doc/src/angle_cosine_shift_exp.rst
  doc/src/bond_harmonic_shift_cut.rst
  doc/src/compute_fep.rst
  doc/src/compute_hma.rst
  doc/src/dihedral_cosine_shift_exp.rst
  doc/src/fix_adapt_fep.rst
  doc/src/fix_atc.rst
  doc/src/fix_bond_react.rst
  doc/src/fix_nh_uef.rst
  doc/src/fix_precession_spin.rst
  doc/src/fix_wall_gran.rst
  doc/src/fix_wall_gran_region.rst
  doc/src/min_modify.rst
  doc/src/min_spin.rst
  doc/src/neb_spin.rst
  doc/src/pair_class2.rst
  doc/src/pair_coul.rst
  doc/src/pair_fep_soft.rst
  doc/src/pair_lj.rst
  doc/src/pair_lj_long.rst
  doc/src/pair_morse.rst
  doc/src/pair_spin_exchange.rst
  doc/src/pair_spin_magelec.rst
  doc/src/pair_thole.rst
  doc/src/rerun.rst
  doc/src/temper_grem.rst
Labels: documentation

#1857 USER-CGDNA: Increased tolerance for fatal error in FENE bond
  src/USER-CGDNA/bond_oxdna_fene.cpp
Labels: update
