Repository lammps/lammps, pull requests merged in 2022-07, with the labels that each got.

#3327 Collected small fixes
  cmake/Modules/Packages/ML-HDNNP.cmake
  doc/src/Howto_viscosity.rst
  src/ML-SNAP/compute_sna_grid_local.cpp
  src/ML-SNAP/compute_snap.cpp
  src/dump.cpp
  unittest/CMakeLists.txt
Labels: documentation, bugfix, cmake, snap_package, unittest_feature

#3328 Add Kokkos version of pair MEAM
  doc/src/Commands_pair.rst
  doc/src/package.rst
  doc/src/pair_meam.rst
  src/Depend.sh
  src/KOKKOS/Install.sh
  src/KOKKOS/comm_kokkos.cpp
  src/KOKKOS/comm_kokkos.h
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/kokkos_base.h
  src/KOKKOS/math_special_kokkos.cpp
  src/KOKKOS/math_special_kokkos.h
  src/KOKKOS/meam_dens_final_kokkos.h
  src/KOKKOS/meam_dens_init_kokkos.h
  src/KOKKOS/meam_force_kokkos.h
  src/KOKKOS/meam_funcs_kokkos.h
  src/KOKKOS/meam_impl_kokkos.h
  src/KOKKOS/meam_kokkos.h
  src/KOKKOS/meam_setup_done_kokkos.h
  src/KOKKOS/pair_meam_kokkos.cpp
  src/KOKKOS/pair_meam_kokkos.h
  src/MEAM/meam.h
  src/MEAM/meam_impl.cpp
  src/MEAM/pair_meam.cpp
  src/MEAM/pair_meam.h
  src/pair.cpp
  src/pair.h
Labels: enhancement, kokkos_package, ready_for_merge

#3323 Optimizations to input class for reading very long lines
  src/input.cpp
  src/lammps.cpp
Labels: ready_for_merge, optimization

#3298 Reaxff species 'delete' keyword
  doc/src/fix_reaxff_species.rst
  src/REAXFF/fix_reaxff_species.cpp
  src/REAXFF/fix_reaxff_species.h
Labels: user_reaxc_package

#3340 Correct excluded force and energy term for pair style coul/slater/long
  src/EXTRA-PAIR/pair_coul_slater_long.cpp
  unittest/force-styles/tests/mol-pair-coul_slater_long.yaml
Labels: bugfix

#3342 Extract bispectrum gradients in compute_snap without summing over neighbors.
  doc/src/compute_sna_atom.rst
  examples/snap/README.md
  examples/snap/compute_snap_dgrad.py
  src/ML-SNAP/compute_snap.cpp
  src/ML-SNAP/compute_snap.h
  src/ML-SNAP/sna.cpp
Labels: snap_package

#3344 Add option to read_dump that prevents resetting the timestep
  doc/src/dump.rst
  doc/src/read_dump.rst
  src/read_dump.cpp
  src/read_dump.h
Labels: enhancement

#3341 Add pair_modify option to allow separate cutoffs for each neigh list …
  doc/src/neighbor.rst
  doc/src/pair_modify.rst
  doc/utils/sphinx-config/false_positives.txt
  src/Depend.sh
  src/INTEL/npair_halffull_newtoff_trim_intel.h
  src/INTEL/npair_halffull_newton_trim_intel.cpp
  src/INTEL/npair_halffull_newton_trim_intel.h
  src/INTEL/npair_trim_intel.cpp
  src/INTEL/npair_trim_intel.h
  src/KOKKOS/Install.sh
  src/KOKKOS/npair_halffull_kokkos.cpp
  src/KOKKOS/npair_halffull_kokkos.h
  src/KOKKOS/npair_trim_kokkos.cpp
  src/KOKKOS/npair_trim_kokkos.h
  src/OPENMP/npair_halffull_newtoff_trim_omp.cpp
  src/OPENMP/npair_halffull_newtoff_trim_omp.h
  src/OPENMP/npair_halffull_newton_trim_omp.cpp
  src/OPENMP/npair_halffull_newton_trim_omp.h
  src/OPENMP/npair_trim_omp.cpp
  src/OPENMP/npair_trim_omp.h
  src/neigh_list.cpp
  src/neigh_list.h
  src/neigh_request.cpp
  src/neigh_request.h
  src/neighbor.cpp
  src/neighbor.h
  src/npair_halffull_newtoff_trim.cpp
  src/npair_halffull_newtoff_trim.h
  src/npair_halffull_newton_trim.cpp
  src/npair_halffull_newton_trim.h
  src/npair_trim.cpp
  src/npair_trim.h
  src/pair.cpp
  src/pair.h
  src/pair_hybrid.cpp
  src/pair_hybrid.h
  src/pair_hybrid_scaled.cpp
Labels: neighborlist_feature

#3346 Fix bug in vtk dump
  src/VTK/dump_vtk.cpp
Labels: bugfix

#3339 Redoing groups in compute contact/atom
  doc/src/compute_contact_atom.rst
  src/GRANULAR/compute_contact_atom.cpp
  src/GRANULAR/compute_contact_atom.h
Labels: enhancement, bugfix

#3331 Bond/react bugfixes
  doc/src/Errors_messages.rst
  doc/src/Errors_warnings.rst
  src/REACTION/fix_bond_react.cpp
Labels: bugfix, user_reaction_package

#3337 Adding pair style srp/react
  doc/src/Commands_pair.rst
  doc/src/pair_srp.rst
  doc/src/pair_style.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/PACKAGES/srp_react/README
  examples/PACKAGES/srp_react/gel_equil.dat
  examples/PACKAGES/srp_react/in.srp_react
  src/.gitignore
  src/MC/fix_bond_break.h
  src/MC/fix_bond_create.h
  src/MISC/fix_srp.cpp
  src/MISC/fix_srp.h
  src/MISC/fix_srp_react.cpp
  src/MISC/fix_srp_react.h
  src/MISC/pair_srp.cpp
  src/MISC/pair_srp.h
  src/MISC/pair_srp_react.cpp
  src/MISC/pair_srp_react.h
Labels: enhancement

#3350 add a table with list of dump styles
  doc/src/Commands.rst
  doc/src/Commands_all.rst
  doc/src/Commands_bond.rst
  doc/src/Commands_compute.rst
  doc/src/Commands_dump.rst
  doc/src/Commands_fix.rst
  doc/src/Commands_kspace.rst
  doc/src/Commands_pair.rst
  doc/src/Manual.rst
  doc/src/dump.rst
  doc/src/dump_image.rst
  doc/src/dump_netcdf.rst
  doc/src/dumps.rst
  doc/utils/check-styles.py
Labels: documentation

#3349 Collected small changes
  doc/src/variable.rst
  doc/utils/sphinx-config/false_positives.txt
  lib/kokkos/bin/nvcc_wrapper
  src/GPU/fix_gpu.cpp
  src/GPU/fix_nh_gpu.cpp
  src/ML-SNAP/compute_grid.cpp
  src/ML-SNAP/compute_grid_local.cpp
  src/ML-SNAP/compute_sna_grid.cpp
  src/dump.cpp
  src/dump_local.cpp
  src/dump_local.h
  src/fix_store.cpp
  src/pair_hybrid.cpp
  src/variable.cpp
  unittest/formats/test_dump_local.cpp
Labels: enhancement, bugfix

#3359 Add package dependency handling for pair style srp/react
  cmake/CMakeLists.txt
  cmake/Modules/Packages/MISC.cmake
  src/Depend.sh
  src/MISC/Install.sh
Labels: build_system, cmake

#3358 Add a section to manual with info on updating old source code for current LAMMPS versions
  doc/src/Developer.rst
  doc/src/Developer_updating.rst
  doc/utils/sphinx-config/false_positives.txt
Labels: documentation

#3364 Add citation information to GitHub
  .gitattributes
  CITATION.cff
Labels: maintenance

#3365 Add CMake support for HIP via CHIP-SPV
  cmake/Modules/Packages/GPU.cmake
  doc/src/Build_extras.rst
  lib/gpu/Makefile.hip
  lib/gpu/lal_pre_cuda_hip.h
Labels: gpu_package

#3372 Removes `easy_install` deprecation warnings in doc build
  doc/Makefile
Labels: documentation
