Repository lammps/lammps, pull requests merged in 2023-11, with the labels that each got.

#3964 Fix bug with compute cluster/atom and aggregate/atom when used with fix deform
  src/compute_aggregate_atom.cpp
  src/compute_cluster_atom.cpp
Labels: bugfix

#3960 New pair_style nb3b/screened
  .github/CODEOWNERS
  doc/src/Commands_pair.rst
  doc/src/pair_nb3b_harmonic.rst
  doc/src/pair_style.rst
  examples/nb3b/PSiO.nb3b.screened
  examples/nb3b/README.nb3b.screened
  examples/nb3b/Table_NP.dat
  examples/nb3b/data.NaPO3
  examples/nb3b/in.nb3b.screened
  examples/nb3b/log.30Oct23.nb3b.screened.g++.1
  examples/nb3b/log.30Oct23.nb3b.screened.g++.4
  src/.gitignore
  src/MANYBODY/pair_nb3b_harmonic.cpp
  src/MANYBODY/pair_nb3b_harmonic.h
  src/MANYBODY/pair_nb3b_screened.cpp
  src/MANYBODY/pair_nb3b_screened.h
Labels: enhancement, manybody_package

#3828 Dynamic check for CUDA and ROCm-aware OpenMPI support in KOKKOS package
  src/KOKKOS/kokkos.cpp
Labels: kokkos_package

#3968 Bugfix: Correctly build argv with nullptr at the end
  python/lammps/core.py
  src/angle_write.cpp
  src/dihedral_write.cpp
  src/lammps.cpp
  src/lammps.h
  unittest/c-library/test_library_commands.cpp
  unittest/c-library/test_library_config.cpp
  unittest/c-library/test_library_external.cpp
  unittest/c-library/test_library_mpi.cpp
  unittest/c-library/test_library_open.cpp
  unittest/c-library/test_library_properties.cpp
  unittest/c-library/test_library_scatter_gather.cpp
  unittest/commands/test_mpi_load_balancing.cpp
  unittest/cplusplus/test_input_class.cpp
  unittest/cplusplus/test_lammps_class.cpp
  unittest/force-styles/test_angle_style.cpp
  unittest/force-styles/test_bond_style.cpp
  unittest/force-styles/test_dihedral_style.cpp
  unittest/force-styles/test_fix_timestep.cpp
  unittest/force-styles/test_improper_style.cpp
  unittest/force-styles/test_pair_style.cpp
  unittest/fortran/wrap_extract_variable.cpp
  unittest/testing/core.h
Labels: bugfix

#3966 [BUGFIX] Update pair_pace_extrapolation.cpp
  src/ML-PACE/pair_pace_extrapolation.cpp
Labels: bugfix, pace_package

#3958 Fix deposit var keyword
  doc/src/fix_deposit.rst
  src/fix_deposit.cpp
  src/fix_deposit.h
Labels: enhancement

#3724 Enable fix rigid to support 2d enforcement internally
  src/KOKKOS/fix_enforce2d_kokkos.cpp
  src/OPENMP/fix_rigid_nh_omp.cpp
  src/OPENMP/fix_rigid_nh_omp.h
  src/OPENMP/fix_rigid_omp.cpp
  src/OPENMP/fix_rigid_omp.h
  src/OPENMP/fix_rigid_small_omp.cpp
  src/OPENMP/fix_rigid_small_omp.h
  src/RIGID/fix_rigid.cpp
  src/RIGID/fix_rigid.h
  src/RIGID/fix_rigid_nh.cpp
  src/RIGID/fix_rigid_nh.h
  src/RIGID/fix_rigid_nh_small.cpp
  src/RIGID/fix_rigid_nh_small.h
  src/RIGID/fix_rigid_small.cpp
  src/RIGID/fix_rigid_small.h
  src/fix.cpp
  src/fix.h
  src/fix_enforce2d.cpp
  src/fix_enforce2d.h
Labels: rigid_package, bugfix

#3971 Collected small fixes and updates
  doc/src/fix_deposit.rst
  src/BOCS/fix_bocs.cpp
  src/BOCS/fix_bocs.h
  src/DRUDE/fix_tgnh_drude.cpp
  src/DRUDE/fix_tgnh_drude.h
  src/EXTRA-FIX/fix_npt_cauchy.cpp
  src/EXTRA-FIX/fix_npt_cauchy.h
  src/EXTRA-FIX/fix_pafi.cpp
  src/EXTRA-FIX/fix_temp_csld.cpp
  src/EXTRA-FIX/fix_temp_csvr.cpp
  src/PLUMED/fix_plumed.cpp
  src/QTB/fix_qbmsst.cpp
  src/QTB/fix_qbmsst.h
  src/QTB/fix_qtb.cpp
  src/REPLICA/fix_pimd_langevin.cpp
  src/SHOCK/fix_msst.cpp
  src/SHOCK/fix_msst.h
  src/SHOCK/fix_nphug.cpp
  src/UEF/fix_nh_uef.cpp
  src/fix_press_berendsen.cpp
  src/fix_press_berendsen.h
  src/fix_press_langevin.cpp
  src/fix_press_langevin.h
  src/info.cpp
  src/replicate.cpp
  src/variable.cpp
Labels: documentation, refactor

#3975 correct typo and link in body particles doc
  doc/src/Howto_body.rst
  doc/src/pair_body_rounded_polyhedron.rst
Labels: documentation

#3979 Workaround for bug in C++17 support in Intel Classic compilers with fmtlib
  cmake/CMakeLists.txt
  cmake/Modules/LAMMPSUtils.cmake
  src/.gitignore
  src/INTEL/Install.sh
  src/MAKE/OPTIONS/Makefile.intel_coprocessor
  src/MAKE/OPTIONS/Makefile.intel_cpu_intelmpi
  src/MAKE/OPTIONS/Makefile.intel_cpu_mpich
  src/MAKE/OPTIONS/Makefile.intel_cpu_openmpi
  src/MAKE/OPTIONS/Makefile.kokkos_cuda_mpi
  src/MAKE/OPTIONS/Makefile.kokkos_mpi_only
  src/MAKE/OPTIONS/Makefile.kokkos_omp
  src/MAKE/OPTIONS/Makefile.kokkos_phi
  src/Makefile
  src/Purge.list
  src/fmt/compile.h
Labels: bugfix, cmake

#3981 Update CODEOWNERS, part 2
  .github/CODEOWNERS
  cmake/CMakeLists.txt
Labels: documentation, maintenance

#3978 Update version strings for 21 Nov 2023 feature release
  doc/lammps.1
  doc/src/Commands_removed.rst
  doc/src/compute_composition_atom.rst
  doc/src/compute_property_grid.rst
  doc/src/compute_reduce.rst
  doc/src/compute_voronoi_atom.rst
  doc/src/dump.rst
  doc/src/dump_image.rst
  doc/src/fix_deposit.rst
  doc/src/fix_pimd.rst
  src/library.cpp
  src/version.h
Labels: maintenance

#3992 Update internal linear algebra library to LAPACK 3.12
  lib/linalg/README
  lib/linalg/dbdsqr.cpp
  lib/linalg/dgecon.cpp
  lib/linalg/dgelsd.cpp
  lib/linalg/dgelss.cpp
  lib/linalg/dlabad.cpp
  lib/linalg/dlaed2.cpp
  lib/linalg/dlaed3.cpp
  lib/linalg/dlaed8.cpp
  lib/linalg/dlaed9.cpp
  lib/linalg/dlasd8.cpp
  lib/linalg/dlatrs.cpp
  lib/linalg/drscl.cpp
  lib/linalg/ilaenv.cpp
  lib/linalg/zlaed8.cpp
Labels: maintenance, update

#3987 Add a ternary math function to equal- and vector- and atom-style variables
  doc/src/variable.rst
  src/variable.cpp
  unittest/commands/test_variables.cpp
Labels: enhancement

#3988 Collected small changes and fixes
  .github/workflows/coverity.yml
  cmake/presets/kokkos-cuda.cmake
  doc/src/Developer_unittest.rst
  doc/src/Fortran.rst
  doc/src/Library.rst
  doc/src/Python_error.rst
  doc/src/Python_install.rst
  doc/src/fix_adapt_fep.rst
  doc/src/fix_atom_swap.rst
  doc/src/variable.rst
  src/DPD-MESO/fix_mvv_dpd.cpp
  src/DPD-MESO/fix_mvv_edpd.cpp
  src/DPD-MESO/fix_mvv_tdpd.cpp
  src/FEP/fix_adapt_fep.cpp
  src/KOKKOS/kokkos.cpp
  src/LEPTON/angle_lepton.cpp
  src/LEPTON/bond_lepton.cpp
  src/LEPTON/pair_lepton.cpp
  src/LEPTON/pair_lepton_coul.cpp
  src/LEPTON/pair_lepton_sphere.cpp
  src/MC/fix_atom_swap.cpp
  src/ML-POD/fitpod_command.cpp
  src/ML-POD/mlpod.cpp
  src/OPENMP/reaxff_forces_omp.cpp
  src/compute_reduce.cpp
  src/dump_image.cpp
  src/fix_adapt.cpp
  src/info.cpp
  src/library.cpp
  src/platform.cpp
  src/variable.cpp
Labels: enhancement

#3997 adding the scale feature of quip calculator, allows fix adapt functio…
  doc/src/fix_adapt.rst
  src/ML-QUIP/pair_quip.cpp
  src/ML-QUIP/pair_quip.h
Labels: enhancement
