Repository lammps/lammps, pull requests merged in 2023-12, with the labels that each got.

#3998 Adding copy of label maps while using replicate command
  src/replicate.cpp
Labels: bugfix

#4002 Add moltemplate tutorial to HowTo section
  doc/src/Howto.rst
  doc/src/Howto_moltemplate.rst
  doc/src/JPG/PolyNIPAM.jpg
  doc/src/JPG/sample01.png
  doc/src/JPG/solv_01.png
  doc/utils/sphinx-config/false_positives.txt
  tools/moltemplate/README.txt
  tools/moltemplate/tutorial-files/PolyNIPAM.lt
  tools/moltemplate/tutorial-files/formamide.lt
  tools/moltemplate/tutorial-files/formamide.xyz
  tools/moltemplate/tutorial-files/model.pdb
  tools/moltemplate/tutorial-files/model.psf
  tools/moltemplate/tutorial-files/sample01.lt
  tools/moltemplate/tutorial-files/solv_01.lt
Labels: documentation

#3962 AMOEBA/HIPPO RMS force accuracy estimate
  examples/amoeba/amoeba_ubiquitin.key
  src/AMOEBA/amoeba_multipole.cpp
  src/AMOEBA/pair_amoeba.cpp
  src/AMOEBA/pair_amoeba.h
Labels: amoeba_package

#4005 Add doc to partially or undocumented features
  doc/src/Howto_body.rst
  doc/src/fix_rigid.rst
  doc/src/molecule.rst
Labels: documentation

#3869 Compute pace update
  doc/src/Commands_compute.rst
  doc/src/compute.rst
  doc/src/compute_pace.rst
  examples/PACKAGES/pace/README.md
  examples/PACKAGES/pace/compute/coupling_coefficients.yace
  examples/PACKAGES/pace/compute/in.compute
  examples/PACKAGES/pace/compute/latte_cell_0.data
  examples/PACKAGES/pace/compute/latte_cell_0.xyz
  examples/PACKAGES/pace/compute/log.5Dec23.compute.g++.1
  examples/PACKAGES/pace/compute/log.5Dec23.compute.g++.4
  src/.gitignore
  src/ML-PACE/compute_pace.cpp
  src/ML-PACE/compute_pace.h
Labels: pace_package

#4006 Fixing typos in fix_nh_uef.rst
  doc/src/fix_nh_uef.rst
Labels: documentation

#3963 Heffte integration
  cmake/CMakeLists.txt
  cmake/Modules/Packages/KSPACE.cmake
  doc/src/Build_settings.rst
  src/KSPACE/fft3d_wrap.cpp
  src/KSPACE/fft3d_wrap.h
Labels: kspace_package

#4011 Use PyConfig to initialize Python
  src/PYTHON/python_impl.cpp
Labels: maintenance

#3996 Compute sna/atom on fixed number of neighbors and compute slcsa/atom (Supervised Learning Crystal Structure Analysis tool)
  doc/src/Bibliography.rst
  doc/src/Commands_compute.rst
  doc/src/compute.rst
  doc/src/compute_slcsa_atom.rst
  doc/src/compute_sna_atom.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/PACKAGES/sna_nnn_slcsa/Zr_mm.eam.fs
  examples/PACKAGES/sna_nnn_slcsa/data.zr_cell
  examples/PACKAGES/sna_nnn_slcsa/dir.slcsa/lda_scalings.dat
  examples/PACKAGES/sna_nnn_slcsa/dir.slcsa/lr_bias.dat
  examples/PACKAGES/sna_nnn_slcsa/dir.slcsa/lr_decision.dat
  examples/PACKAGES/sna_nnn_slcsa/dir.slcsa/mahalanobis_file.dat
  examples/PACKAGES/sna_nnn_slcsa/dir.slcsa/mean_descriptor.dat
  examples/PACKAGES/sna_nnn_slcsa/in.slcsa
  examples/PACKAGES/sna_nnn_slcsa/log.12Dec23.slcsa.g++.1
  examples/PACKAGES/sna_nnn_slcsa/log.12Dec23.slcsa.g++.4
  src/.gitignore
  src/EXTRA-COMPUTE/compute_slcsa_atom.cpp
  src/EXTRA-COMPUTE/compute_slcsa_atom.h
  src/ML-SNAP/compute_sna_atom.cpp
  src/ML-SNAP/compute_sna_atom.h
Labels: snap_package

#4004 Collected small changes and updates
  .github/workflows/codeql-analysis.yml
  .github/workflows/compile-msvc.yml
  doc/src/Build_development.rst
  doc/src/Build_settings.rst
  doc/src/Developer_unittest.rst
  doc/src/Howto_tip4p.rst
  doc/src/Howto_tip5p.rst
  doc/src/Packages_details.rst
  doc/src/Python_error.rst
  doc/src/Run_output.rst
  doc/src/compute_pace.rst
  doc/src/compute_rattlers_atom.rst
  doc/src/compute_saed.rst
  doc/src/compute_stress_atom.rst
  doc/src/fix_adapt.rst
  doc/src/fix_adapt_fep.rst
  doc/src/fix_phonon.rst
  doc/src/img/saed_mesh.jpg
  doc/src/img/saed_mesh.png
  doc/src/molecule.rst
  doc/utils/sphinx-config/false_positives.txt
  lib/pace/Makefile
  lib/pace/Makefile.lammps
  potentials/PSiO.nb3b.screened
  src/FEP/fix_adapt_fep.cpp
  src/MC/fix_gcmc.cpp
  src/MC/fix_widom.cpp
  src/MDI/fix_mdi_qm.cpp
  src/MDI/fix_mdi_qmmm.cpp
  src/MDI/mdi_plugin.cpp
  src/Makefile
  src/PYTHON/python_impl.cpp
  src/utils.cpp
  src/version.h
  tools/msi2lmp/src/SearchAndFill.c
  tools/valgrind/MPICH.supp
  tools/valgrind/README
  unittest/formats/test_input_convert.cpp
Labels: documentation, bugfix

#3833 Implementation of analytical expressions for Born matrix of some potentials & inclusion of angle contribution to stress/mop/profile
  doc/src/compute_stress_mop.rst
  src/EXTRA-COMPUTE/compute_stress_mop.cpp
  src/EXTRA-COMPUTE/compute_stress_mop.h
  src/EXTRA-COMPUTE/compute_stress_mop_profile.cpp
  src/EXTRA-COMPUTE/compute_stress_mop_profile.h
  src/EXTRA-MOLECULE/angle_cosine_periodic.cpp
  src/EXTRA-MOLECULE/angle_cosine_periodic.h
  src/EXTRA-MOLECULE/angle_fourier.cpp
  src/EXTRA-MOLECULE/angle_quartic.cpp
  src/EXTRA-MOLECULE/angle_quartic.h
  src/EXTRA-MOLECULE/bond_gaussian.cpp
  src/EXTRA-MOLECULE/bond_gaussian.h
  src/EXTRA-MOLECULE/bond_harmonic_shift_cut.cpp
  src/EXTRA-MOLECULE/bond_harmonic_shift_cut.h
  src/EXTRA-MOLECULE/dihedral_helix.cpp
  src/EXTRA-MOLECULE/dihedral_helix.h
  src/EXTRA-MOLECULE/dihedral_quadratic.cpp
  src/EXTRA-MOLECULE/dihedral_quadratic.h
  src/YAFF/angle_mm3.cpp
  src/YAFF/angle_mm3.h
  src/YAFF/bond_mm3.cpp
  src/YAFF/bond_mm3.h
Labels: enhancement

#3938 new compute: reaxff/atom
  doc/src/Commands_compute.rst
  doc/src/compute.rst
  doc/src/compute_reaxff_atom.rst
  doc/src/pair_reaxff.rst
  examples/reaxff/in.reaxff.tatb
  src/.gitignore
  src/KOKKOS/Install.sh
  src/KOKKOS/compute_reaxff_atom_kokkos.cpp
  src/KOKKOS/compute_reaxff_atom_kokkos.h
  src/KOKKOS/pair_reaxff_kokkos.cpp
  src/KOKKOS/pair_reaxff_kokkos.h
  src/PYTHON/python_impl.cpp
  src/REAXFF/compute_reaxff_atom.cpp
  src/REAXFF/compute_reaxff_atom.h
Labels: user_reaxc_package

#4022 Corrections for fix cmap to be compatible with CMAP files created by CHARMM-GUI
  src/MOLECULE/fix_cmap.cpp
  src/MOLECULE/fix_cmap.h
  src/potential_file_reader.cpp
  src/text_file_reader.cpp
Labels: bugfix

#4023 Updated the Developer unittest section for debugging failed unit tests individually
  doc/src/Build_development.rst
  doc/src/Developer_unittest.rst
Labels: documentation

#4025 Add a new potential file for ilp/tmd
  doc/src/pair_ilp_tmd.rst
  examples/PACKAGES/interlayer/ilp_tmds/MoS2.ILP
  examples/PACKAGES/interlayer/ilp_tmds/TMD.ILP
  examples/PACKAGES/interlayer/ilp_tmds/in.mos2
  potentials/TMD.ILP
  src/INTERLAYER/pair_ilp_tmd.cpp
  src/INTERLAYER/pair_kolmogorov_crespi_full.cpp
Labels: enhancement, bugfix
