Repository lammps/lammps, pull requests merged in 2023-03, with the labels that each got.

#3657 Add fix wall/table and fix wall/lepton for customizable wall fixes
  doc/Makefile
  doc/src/Commands_fix.rst
  doc/src/Tools.rst
  doc/src/fix.rst
  doc/src/fix_wall.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/wall/in.wall.lepton
  examples/wall/in.wall.table
  examples/wall/log.23Feb23.wall.lepton.g++.1
  examples/wall/log.23Feb23.wall.lepton.g++.4
  examples/wall/log.23Feb23.wall.table.g++.1
  examples/wall/log.23Feb23.wall.table.g++.4
  examples/wall/wall.inc
  examples/wall/walltab.dat
  src/.gitignore
  src/COLLOID/fix_wall_colloid.cpp
  src/EXTRA-FIX/fix_wall_ees.cpp
  src/EXTRA-FIX/fix_wall_reflect_stochastic.cpp
  src/GRANULAR/fix_wall_gran_region.cpp
  src/KOKKOS/fix_wall_lj93_kokkos.cpp
  src/KOKKOS/fix_wall_reflect_kokkos.cpp
  src/LEPTON/fix_wall_lepton.cpp
  src/LEPTON/fix_wall_lepton.h
  src/SHOCK/fix_wall_piston.cpp
  src/SRD/fix_wall_srd.cpp
  src/fix_wall.cpp
  src/fix_wall.h
  src/fix_wall_harmonic.cpp
  src/fix_wall_lj126.cpp
  src/fix_wall_lj93.cpp
  src/fix_wall_morse.cpp
  src/fix_wall_table.cpp
  src/fix_wall_table.h
  tools/tabulate/README.md
  tools/tabulate/tabulate.py
  tools/tabulate/wall_harmonic_tabulate.py
  tools/tabulate/wall_multi_tabulate.py
  unittest/force-styles/tests/fix-timestep-wall_lepton_const.yaml
  unittest/force-styles/tests/fix-timestep-wall_morse_const.yaml
  unittest/force-styles/tests/fix-timestep-wall_table_linear.yaml
  unittest/force-styles/tests/fix-timestep-wall_table_spline.yaml
  unittest/force-styles/tests/wall.table
Labels: enhancement

#3661 Hippy fixes
  src/KOKKOS/mliap_unified_couple_kokkos.pyx
  src/KOKKOS/mliap_unified_kokkos.cpp
  src/KOKKOS/pair_mliap_kokkos.cpp
  src/PYTHON/python_impl.cpp
Labels: bugfix, kokkos_package, mliap_package

#3648 Bond/react updates
  examples/PACKAGES/reaction/create_atoms_polystyrene/in.grow_styrene
  examples/PACKAGES/reaction/nylon,6-6_melt/in.large_nylon_melt
  examples/PACKAGES/reaction/tiny_epoxy/in.tiny_epoxy.stabilized
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.stabilized
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.stabilized_variable_probability
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.unstabilized
  examples/PACKAGES/reaction/tiny_polystyrene/in.tiny_polystyrene.stabilized
  src/REACTION/fix_bond_react.cpp
  src/REACTION/fix_bond_react.h
Labels: bugfix

#3666 Fixed GPU library builds with CUDA MPS
  cmake/Modules/Packages/GPU.cmake
  lib/gpu/Makefile.cuda
  lib/gpu/Makefile.cuda_mps
  lib/gpu/Makefile.oneapi
  lib/gpu/README
  lib/gpu/lal_device.cpp
Labels: gpu_package, bugfix

#3659 Allow `fix deform/kk` to use rigid bodies, fix logic issues with Kokkos neigh list
  src/KOKKOS/fix_deform_kokkos.cpp
  src/KOKKOS/npair_kokkos.cpp
  src/KOKKOS/npair_kokkos.h
Labels: enhancement, bugfix, kokkos_package

#3669 Adding boltzmann inversion like pair tabulation to tools/tabulate
  tools/tabulate/README.md
  tools/tabulate/pair_bi_tabulate.py
Labels: tools

#3676 Updated fix_deposit documentation
  doc/src/fix_deposit.rst
Labels: documentation

#3677 Sort option for load balancing commands
  doc/src/balance.rst
  doc/src/fix_balance.rst
  src/balance.cpp
  src/balance.h
  src/fix_balance.cpp
  src/fix_balance.h
Labels: communication_feature, ready_for_merge

#3674 GPU package bugfix / cmake improvement
  cmake/Modules/Packages/GPU.cmake
  lib/gpu/lal_atom.cpp
Labels: gpu_package, bugfix, cmake, ready_for_merge

#3680 Address double linking issue with Kokkos libraries
  cmake/CMakeLists.txt
  cmake/Modules/Packages/KOKKOS.cmake
  src/main.cpp
Labels: kokkos_package, cmake

#3668 Implementation of analytical expressions for Born matrix
  doc/src/bond_fene.rst
  src/CLASS2/pair_lj_class2_coul_cut.cpp
  src/CLASS2/pair_lj_class2_coul_cut.h
  src/EXTRA-MOLECULE/bond_fene_nm.cpp
  src/EXTRA-MOLECULE/bond_fene_nm.h
  src/EXTRA-MOLECULE/bond_nonlinear.cpp
  src/EXTRA-MOLECULE/bond_nonlinear.h
  src/EXTRA-PAIR/pair_nm_cut.cpp
  src/EXTRA-PAIR/pair_nm_cut.h
  src/EXTRA-PAIR/pair_nm_cut_coul_cut.cpp
  src/EXTRA-PAIR/pair_nm_cut_coul_cut.h
  src/MOLECULE/angle_harmonic.cpp
  src/MOLECULE/angle_harmonic.h
  src/MOLECULE/bond_fene.cpp
  src/MOLECULE/bond_fene.h
  src/MOLECULE/bond_morse.cpp
  src/MOLECULE/bond_morse.h
  src/MOLECULE/dihedral_multi_harmonic.cpp
  src/MOLECULE/dihedral_multi_harmonic.h
  src/MOLECULE/dihedral_opls.cpp
  src/MOLECULE/dihedral_opls.h
  src/pair_buck_coul_cut.cpp
  src/pair_buck_coul_cut.h
  src/pair_coul_cut.cpp
  src/pair_coul_cut.h
  src/pair_coul_debye.cpp
  src/pair_coul_debye.h
  src/pair_lj_cut_coul_cut.cpp
  src/pair_lj_cut_coul_cut.h
Labels: enhancement, ready_for_merge

#3679 Dielectric package doc update and bugfix
  doc/src/fix_polarize.rst
  examples/PACKAGES/dielectric/data.sphere
  examples/PACKAGES/dielectric/in.confined
  examples/PACKAGES/dielectric/in.nopbc
  examples/PACKAGES/dielectric/log.07Mar23.confined.dof.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.confined.dof.g++.4
  examples/PACKAGES/dielectric/log.07Mar23.confined.gmres.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.confined.gmres.g++.4
  examples/PACKAGES/dielectric/log.07Mar23.confined.icc.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.confined.icc.g++.4
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.dof.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.dof.g++.4
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.gmres.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.gmres.g++.4
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.icc.g++.1
  examples/PACKAGES/dielectric/log.07Mar23.nopbc.icc.g++.4
  src/DIELECTRIC/fix_polarize_bem_gmres.cpp
  src/DIELECTRIC/fix_polarize_bem_icc.cpp
  src/DIELECTRIC/fix_polarize_functional.cpp
Labels: documentation, bugfix, ready_for_merge, dielectric_package

#3671 Add new bond style harmonic/restrain
  doc/src/Commands_bond.rst
  doc/src/Developer_notes.rst
  doc/src/Developer_updating.rst
  doc/src/bond_harmonic_restrain.rst
  doc/src/bond_style.rst
  doc/utils/sphinx-config/false_positives.txt
  src/.gitignore
  src/AMOEBA/amoeba_induce.cpp
  src/AMOEBA/amoeba_utils.cpp
  src/AMOEBA/pair_amoeba.cpp
  src/AMOEBA/pair_amoeba.h
  src/CORESHELL/compute_temp_cs.cpp
  src/CORESHELL/compute_temp_cs.h
  src/EXTRA-COMPUTE/compute_hma.cpp
  src/EXTRA-COMPUTE/compute_hma.h
  src/EXTRA-COMPUTE/compute_msd_nongauss.cpp
  src/EXTRA-MOLECULE/bond_harmonic_restrain.cpp
  src/EXTRA-MOLECULE/bond_harmonic_restrain.h
  src/FEP/fix_adapt_fep.cpp
  src/FEP/fix_adapt_fep.h
  src/GPU/pair_amoeba_gpu.cpp
  src/GPU/pair_hippo_gpu.cpp
  src/REPLICA/tad.cpp
  src/REPLICA/tad.h
  src/VTK/dump_vtk.cpp
  src/balance.cpp
  src/balance.h
  src/compute_chunk_atom.cpp
  src/compute_chunk_atom.h
  src/compute_displace_atom.cpp
  src/compute_displace_atom.h
  src/compute_msd.cpp
  src/compute_msd.h
  src/compute_vacf.cpp
  src/compute_vacf.h
  src/dump_custom.cpp
  src/dump_custom.h
  src/fix_adapt.cpp
  src/fix_adapt.h
  src/fix_balance.cpp
  src/fix_store_atom.cpp
  src/fix_store_atom.h
  src/fix_store_global.cpp
  src/variable.cpp
  src/variable.h
  unittest/force-styles/test_angle_style.cpp
  unittest/force-styles/test_bond_style.cpp
  unittest/force-styles/tests/bond-harmonic_restrain.yaml
Labels: enhancement

#3689 cmake: remove pip install from install target
  cmake/CMakeLists.txt
  doc/src/Python_install.rst
Labels: python_module, cmake

#3684 Encode improper symmetries
  src/AMOEBA/improper_amoeba.cpp
  src/CLASS2/improper_class2.cpp
  src/EXTRA-MOLECULE/improper_cossq.cpp
  src/EXTRA-MOLECULE/improper_distance.cpp
  src/EXTRA-MOLECULE/improper_fourier.cpp
  src/EXTRA-MOLECULE/improper_ring.cpp
  src/MOFFF/improper_inversion_harmonic.cpp
  src/MOLECULE/improper_cvff.cpp
  src/MOLECULE/improper_harmonic.cpp
  src/MOLECULE/improper_umbrella.cpp
  src/YAFF/improper_distharm.cpp
  src/YAFF/improper_sqdistharm.cpp
  src/improper.cpp
  src/improper.h
Labels: enhancement

#3685 Add TIP4P versions for compute dipole, compute dipole/chunk and fix efield
  doc/src/Commands_compute.rst
  doc/src/Commands_fix.rst
  doc/src/compute.rst
  doc/src/compute_dipole.rst
  doc/src/compute_dipole_chunk.rst
  doc/src/fix.rst
  doc/src/fix_efield.rst
  src/.gitignore
  src/EXTRA-COMPUTE/compute_dipole_tip4p.cpp
  src/EXTRA-COMPUTE/compute_dipole_tip4p.h
  src/EXTRA-COMPUTE/compute_dipole_tip4p_chunk.cpp
  src/EXTRA-COMPUTE/compute_dipole_tip4p_chunk.h
  src/EXTRA-FIX/fix_efield_tip4p.cpp
  src/EXTRA-FIX/fix_efield_tip4p.h
  src/MOLECULE/pair_lj_cut_tip4p_cut.cpp
  src/MOLECULE/pair_tip4p_cut.cpp
  src/MOLECULE/pair_tip4p_cut.h
  src/fix_efield.cpp
  src/fix_efield.h
  unittest/force-styles/tests/fix-timestep-efield_tip4p_const.yaml
  unittest/force-styles/tests/fix-timestep-efield_tip4p_variable.yaml
  unittest/force-styles/tests/mol-pair-lj_cut_tip4p_cut.yaml
  unittest/force-styles/tests/mol-pair-lj_cut_tip4p_long.yaml
  unittest/force-styles/tests/mol-pair-lj_cut_tip4p_long_soft.yaml
  unittest/force-styles/tests/mol-pair-lj_cut_tip4p_table.yaml
  unittest/force-styles/tests/mol-pair-lj_long_cut_tip4p_long.yaml
  unittest/force-styles/tests/mol-pair-lj_long_tip4p_long.yaml
  unittest/force-styles/tests/mol-pair-lj_table_tip4p_long.yaml
  unittest/force-styles/tests/mol-pair-lj_table_tip4p_table.yaml
  unittest/force-styles/tests/mol-pair-tip4p_cut.yaml
  unittest/force-styles/tests/mol-pair-tip4p_long.yaml
  unittest/force-styles/tests/mol-pair-tip4p_long_soft.yaml
  unittest/force-styles/tests/mol-pair-tip4p_table.yaml
Labels: enhancement

#3696 Minor updates/patches for BPM, rigid, and multi
  doc/src/Modify_gran_sub_mod.rst
  doc/src/bond_bpm_rotational.rst
  doc/src/bond_bpm_spring.rst
  doc/src/comm_modify.rst
  doc/src/neighbor.rst
  src/BPM/bond_bpm.cpp
  src/BPM/bond_bpm.h
  src/RIGID/fix_rigid.cpp
  src/fix_update_special_bonds.cpp
  src/neighbor.cpp
Labels: bugfix, bpm_package

#3699 fix ids once bug in compute chunk/atom
  src/compute_chunk_atom.cpp
Labels: chunk_feature, bugfix

#3693 Collected small changes and fixes
  cmake/Modules/Packages/KIM.cmake
  src/.gitignore
  src/KIM/fix_store_kim.cpp
  src/KIM/kim_command.cpp
  src/KIM/kim_init.cpp
  src/KIM/kim_interactions.cpp
  src/KIM/kim_param.cpp
  src/KIM/kim_param.h
  src/KIM/kim_property.cpp
  src/KIM/kim_query.cpp
  src/KIM/kim_units.cpp
  src/KIM/kim_units.h
  src/KIM/pair_kim.cpp
  src/KOKKOS/fix_property_atom_kokkos.cpp
  src/KOKKOS/fix_rx_kokkos.cpp
  src/MANYBODY/pair_eam.cpp
  src/fix_adapt.cpp
  src/fix_property_atom.cpp
  src/fix_property_atom.h
  tools/fep/fdti.py
  tools/fep/fep.py
  tools/fep/nti.py
  tools/python/pizza/dump.py
  unittest/commands/test_kim_commands.cpp
Labels: bug, tools, kim_package, maintenance

#3702 bug fix for compute voronoi with triclinic simulation boxes
  src/VORONOI/compute_voronoi_atom.cpp
Labels: bugfix

#3703 bug fix for fix rigid nh/npt small error in MPI message sizes
  src/DRUDE/fix_drude_transform.cpp
  src/RIGID/fix_rigid_nh_small.cpp
  src/VORONOI/compute_voronoi_atom.cpp
Labels: rigid_package, bugfix

#3652 Moved region check from constructor to init()
  examples/mc/log.23Mar23.gcmc.lj.g++.1
  examples/mc/log.23Mar23.gcmc.lj.g++.4
  src/MC/fix_gcmc.cpp
Labels: mc_package

#3701 Remove deprecated Kokkos code
  src/KOKKOS/compute_temp_deform_kokkos.h
  src/KOKKOS/compute_temp_kokkos.h
  src/KOKKOS/dihedral_charmm_kokkos.h
  src/KOKKOS/domain_kokkos.cpp
  src/KOKKOS/fix_freeze_kokkos.h
  src/KOKKOS/fix_langevin_kokkos.h
  src/KOKKOS/fix_rx_kokkos.h
  src/KOKKOS/fix_setforce_kokkos.h
  src/KOKKOS/kokkos_few.h
  src/KOKKOS/kokkos_type.h
  src/KOKKOS/min_linesearch_kokkos.h
  src/KOKKOS/nbin_ssa_kokkos.h
  src/KOKKOS/pair_reaxff_kokkos.h
Labels: kokkos_package

#3709 Minor fixes that might be of interest...
  doc/src/fix_ave_correlate_long.rst
  doc/src/fix_press_berendsen.rst
  src/EXTRA-FIX/fix_ave_correlate_long.cpp
Labels: documentation, bugfix

#3712 Remove duplicated code in Kokkos PPPM
  src/KOKKOS/pppm_kokkos.cpp
  src/KOKKOS/pppm_kokkos.h
  src/KSPACE/pppm.h
Labels: bugfix, kokkos_package

#3698 use of type labels in set commands
  doc/src/set.rst
  src/atom.cpp
  src/set.cpp
  unittest/commands/test_set_property.cpp
Labels: enhancement

#3667 Add detailed developer information about adding pair styles and use new born/gauss style as example
  doc/src/Build_development.rst
  doc/src/Commands_pair.rst
  doc/src/Developer_notes.rst
  doc/src/Developer_write.rst
  doc/src/Developer_write_fix.rst
  doc/src/Developer_write_pair.rst
  doc/src/Modify_pair.rst
  doc/src/fix_adapt.rst
  doc/src/improper_amoeba.rst
  doc/src/pair_born_gauss.rst
  doc/src/pair_lj.rst
  doc/src/pair_style.rst
  doc/src/set.rst
  doc/utils/sphinx-config/false_positives.txt
  src/.gitignore
  src/EXTRA-PAIR/pair_born_gauss.cpp
  src/EXTRA-PAIR/pair_born_gauss.h
  src/GRANULAR/pair_gran_hooke.cpp
  src/atom_map.cpp
  unittest/force-styles/tests/atomic-pair-born_gauss.yaml
  unittest/python/python-numpy.py
Labels: enhancement, documentation

#3713 Bugfix amoeba doc header
  doc/src/improper_amoeba.rst
Labels: documentation

#3706 Update version strings for upcoming feature release
  doc/lammps.1
  doc/src/Developer_updating.rst
  doc/src/bond_bpm_rotational.rst
  doc/src/bond_bpm_spring.rst
  doc/src/bond_harmonic_restrain.rst
  doc/src/compute_dipole.rst
  doc/src/compute_dipole_chunk.rst
  doc/src/compute_pressure_alchemy.rst
  doc/src/fix_alchemy.rst
  doc/src/fix_efield.rst
  doc/src/fix_mdi_qmmm.rst
  doc/src/fix_pimd.rst
  doc/src/fix_wall.rst
  doc/src/pair_gauss.rst
  src/version.h
Labels: maintenance

#3715 Small update for the 28 March 2023 release to recover Sphinx formatting of the Documentation website
  doc/utils/requirements.txt
  src/version.h
Labels: documentation

#3716 Remove fix latte and LATTE package and examples and lib
  cmake/CMakeLists.txt
  cmake/Modules/Packages/LATTE.cmake
  cmake/presets/all_off.cmake
  cmake/presets/all_on.cmake
  cmake/presets/download.cmake
  cmake/presets/mingw-cross.cmake
  cmake/presets/nolib.cmake
  doc/src/Build_basics.rst
  doc/src/Build_extras.rst
  doc/src/Build_package.rst
  doc/src/Commands_fix.rst
  doc/src/Commands_removed.rst
  doc/src/Examples.rst
  doc/src/Howto_couple.rst
  doc/src/Install_mac.rst
  doc/src/Intro_features.rst
  doc/src/Packages_details.rst
  doc/src/Packages_list.rst
  doc/src/fix.rst
  doc/src/fix_latte.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/README
  examples/latte/TBparam/bondints.nonortho
  examples/latte/TBparam/electrons.dat
  examples/latte/TBparam/ppots.nonortho
  examples/latte/data.ch4
  examples/latte/data.graphene
  examples/latte/data.sucrose
  examples/latte/data.water
  examples/latte/in.latte.graphene.boxrelax
  examples/latte/in.latte.multiple
  examples/latte/in.latte.sucrose.md
  examples/latte/in.latte.water.md
  examples/latte/in.latte.water.min
  examples/latte/latte.in
  examples/latte/log.13Sep22.latte.graphene.boxrelax.g++.1
  examples/latte/log.13Sep22.latte.multiple.g++.1
  examples/latte/log.13Sep22.latte.sucrose.md.g++.1
  examples/latte/log.13Sep22.latte.water.md.g++.1
  examples/latte/log.13Sep22.latte.water.min.g++.1
  examples/latte/log.21Jun18.latte.multiple.g++.1
  lib/.gitignore
  lib/latte/.gitignore
  lib/latte/Install.py
  lib/latte/Makefile.lammps.gfortran
  lib/latte/Makefile.lammps.ifort
  lib/latte/Makefile.lammps.linalg
  lib/latte/Makefile.lammps.mpi
  lib/latte/Makefile.lammps.serial
  lib/latte/README
  src/.gitignore
  src/LATTE/Install.sh
  src/LATTE/README
  src/LATTE/fix_latte.cpp
  src/LATTE/fix_latte.h
  src/Makefile
  src/Purge.list
Labels: maintenance

#3719 Refactor fix shake to use `closest_image` instead of `minimum_image_once`
  src/KOKKOS/fix_shake_kokkos.cpp
  src/KOKKOS/fix_shake_kokkos.h
  src/RIGID/fix_shake.cpp
  src/RIGID/fix_shake.h
Labels: rigid_package, kokkos_package, refactor
