Repository lammps/lammps, pull requests merged in 2024-08, with the labels that each got.

#4259 Type label support for dump image, movie
  doc/src/dump_image.rst
  src/dump_image.cpp
Labels: refactor

#4255 Collected small changes and fixes
  doc/src/Build_development.rst
  doc/src/Howto_lammps_gui.rst
  doc/src/JPG/lammps-gui-image.png
  doc/src/JPG/lammps-gui-prefs-accel.png
  doc/src/JPG/lammps-gui-prefs-editor.png
  doc/src/JPG/lammps-gui-prefs-general.png
  doc/src/JPG/lammps-gui-prefs-image.png
  doc/src/Tools.rst
  doc/utils/sphinx-config/false_positives.txt
  python/lammps/core.py
  src/GRANULAR/fix_add_heat.cpp
  src/KSPACE/pppm_dipole.cpp
  src/ML-POD/fitpod_command.cpp
  src/ML-POD/pair_pod.cpp
  src/MOLECULE/fix_cmap.cpp
  src/MOLECULE/pair_lj_cut_tip4p_cut.cpp
  src/QEQ/fix_qeq.cpp
  src/QEQ/fix_qeq_point.cpp
  src/QEQ/fix_qeq_shielded.cpp
  src/bond.cpp
  src/library.cpp
  src/pair.cpp
  src/update.cpp
  src/write_dump.cpp
  tools/lammps-gui/CMakeLists.txt
  tools/lammps-gui/TODO.md
  tools/lammps-gui/codeeditor.cpp
  tools/lammps-gui/codeeditor.h
  tools/lammps-gui/fileviewer.cpp
  tools/lammps-gui/help_index.table
  tools/lammps-gui/icons/image-shiny.png
  tools/lammps-gui/imageviewer.cpp
  tools/lammps-gui/imageviewer.h
  tools/lammps-gui/lammps-gui.appdata.xml
  tools/lammps-gui/lammpsgui.cpp
  tools/lammps-gui/lammpsgui.h
  tools/lammps-gui/lammpsgui.qrc
  tools/lammps-gui/org.lammps.lammps-gui.yml
  tools/lammps-gui/preferences.cpp
  tools/valgrind/MPICH.supp
  tools/valgrind/OpenMP.supp
  unittest/CMakeLists.txt
  unittest/c-library/test_library_properties.cpp
  unittest/testing/core.h
Labels: enhancement, bugfix

#4266 New geturl command to download files for LAMMPS inputs on demand
  cmake/CMakeLists.txt
  doc/src/Build_settings.rst
  doc/src/Commands_all.rst
  doc/src/commands_list.rst
  doc/src/geturl.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/COUPLE/plugin/liblammpsplugin.c
  examples/COUPLE/plugin/liblammpsplugin.h
  fortran/lammps.f90
  python/lammps/core.py
  src/.gitignore
  src/EXTRA-COMMAND/geturl.cpp
  src/EXTRA-COMMAND/geturl.h
  src/MAKE/Makefile.mpi
  src/MAKE/Makefile.serial
  src/info.cpp
  src/info.h
  src/lammps.cpp
  src/library.cpp
  src/library.h
  tools/lammps-gui/highlighter.cpp
  tools/swig/lammps.i
  unittest/commands/test_simple_commands.cpp
Labels: enhancement

#4270 Fix a bug when restarting with stored data in fix STORE/GLOBAL for global vectors or arrays
  src/fix_store_global.cpp
Labels: bugfix

#4276 Various corrections to documentation
  doc/src/Developer_atom.rst
  doc/src/Developer_code_design.rst
  doc/src/Developer_flow.rst
  doc/src/Developer_notes.rst
  doc/src/Developer_par_comm.rst
  doc/src/Developer_par_long.rst
  doc/src/Developer_par_neigh.rst
  doc/src/Developer_par_openmp.rst
  doc/src/Developer_plugins.rst
  doc/src/Developer_unittest.rst
  doc/src/Developer_updating.rst
  doc/src/Developer_utils.rst
  doc/src/Developer_write_fix.rst
  doc/src/Developer_write_pair.rst
  doc/src/Howto_rheo.rst
  doc/src/Modify_atom.rst
  doc/src/Modify_contribute.rst
  doc/src/Modify_gran_sub_mod.rst
  doc/src/Modify_overview.rst
  doc/src/Modify_requirements.rst
  doc/src/Modify_thermo.rst
  doc/src/Python_error.rst
  doc/src/Python_neighbor.rst
  doc/src/Python_scatter.rst
  doc/src/create_atoms.rst
  doc/src/create_box.rst
  doc/src/fix_rheo.rst
  doc/src/fix_rheo_viscosity.rst
  python/lammps/core.py
  python/lammps/numpy_wrapper.py
  python/lammps/pylammps.py
  src/atom.cpp
  src/input.cpp
  src/lammps.cpp
  src/my_page.cpp
  src/my_page.h
  src/my_pool_chunk.cpp
  src/platform.h
  src/potential_file_reader.cpp
  src/text_file_reader.cpp
  src/utils.h
Labels: documentation

#4279 Edits/corrections to doc pages 2315-2589
  doc/src/pair_cosine_squared.rst
  doc/src/pair_coul_diel.rst
  doc/src/pair_coul_slater.rst
  doc/src/pair_dipole.rst
  doc/src/pair_dpd.rst
  doc/src/pair_eff.rst
  doc/src/pair_extep.rst
  doc/src/pair_gran.rst
  doc/src/pair_granular.rst
  doc/src/pair_lj_cut_coul.rst
  doc/src/pair_pedone.rst
Labels: documentation

#4283 Edits/corrections to doc pages 949-1220
  doc/src/Developer_grid.rst
  doc/src/atom_style.rst
  doc/src/bond_style.rst
  doc/src/bond_write.rst
  doc/src/clear.rst
  doc/src/comm_style.rst
  doc/src/compute.rst
  doc/src/delete_atoms.rst
  doc/src/dump_image.rst
  doc/src/if.rst
  doc/src/improper_style.rst
  doc/src/include.rst
  doc/src/info.rst
  doc/src/kim_commands.rst
  doc/src/kspace_modify.rst
  doc/src/log.rst
Labels: documentation

#4285 Edits for docs
  doc/src/fix_ave_atom.rst
  doc/src/fix_ave_chunk.rst
  doc/src/fix_ave_grid.rst
  doc/src/fix_ave_time.rst
Labels: documentation

#4256 docs: expand author list
  doc/src/Intro_authors.rst
Labels: documentation

#4228 Adding support for doing regression tests
  doc/src/Tools.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/bpm/impact/log.17Feb2022.bpm.impact.spring.g++.4
  examples/bpm/impact/log.4May2022.impact.rotational.g++.4
  examples/bpm/pour/log.4May2022.bpm.pour.g++.4
  tools/README
  tools/regression-tests/README
  tools/regression-tests/config.yaml
  tools/regression-tests/config_gpu.yaml
  tools/regression-tests/config_kokkos.yaml
  tools/regression-tests/config_valgrind.yaml
  tools/regression-tests/in.lj
  tools/regression-tests/run_tests.py
  tools/regression-tests/thermo.in.lj.yaml
Labels: tools

#4273 Few small patches to BPM, RHEO, and GRANULAR packages
  doc/src/Howto_bpm.rst
  doc/src/Howto_rheo.rst
  doc/src/Packages_details.rst
  doc/src/fix_add_heat.rst
  examples/rheo/oxidation/in.rheo.oxidation
  examples/rheo/oxidation/log.17Apr2024.oxidation.g++.4
  examples/rheo/oxidation/log.27Jun2024.oxidation.g++.4
  src/BPM/bond_bpm_rotational.cpp
  src/BPM/fix_update_special_bonds.cpp
  src/BPM/fix_update_special_bonds.h
  src/GRANULAR/fix_add_heat.cpp
  src/fix_neigh_history.h
Labels: bugfix, granular_package, bpm_package

#4289 Fix 2 bugs with distributed grids
  examples/grid/in.sph
  src/compute_property_grid.cpp
  src/fix_ave_grid.cpp
  src/fix_ave_grid.h
  src/grid2d.cpp
  src/grid2d.h
  src/grid3d.cpp
  src/grid3d.h
Labels: bugfix

#4287 Collected small fixes and updates for LAMMPS and LAMMPS-GUI
  doc/src/Intro_opensource.rst
  doc/src/Manual.rst
  doc/src/neigh_modify.rst
  doc/utils/sphinx-config/conf.py.in
  src/FEP/pair_morse_soft.cpp
  src/FEP/pair_morse_soft.h
  src/group.cpp
  src/molecule.cpp
  src/neighbor.cpp
  src/output.cpp
  src/pair_hybrid_scaled.cpp
  src/text_file_reader.cpp
  tools/lammps-gui/chartviewer.cpp
  tools/lammps-gui/chartviewer.h
  tools/lammps-gui/imageviewer.cpp
  tools/lammps-gui/imageviewer.h
  tools/lammps-gui/lammpsgui.cpp
  unittest/c-library/test_library_open.cpp
  unittest/commands/test_groups.cpp
  unittest/formats/test_file_operations.cpp
  unittest/formats/test_text_file_reader.cpp
  unittest/fortran/wrap_get_thermo.cpp
Labels: documentation, bugfix

#4291 Add error checks to verlet/split for unsupported KSpace methods
  doc/src/run_style.rst
  src/REPLICA/verlet_split.cpp
  src/REPLICA/verlet_split.h
  src/atom.cpp
Labels: documentation, bugfix

#4292 Collected small fixes and changes
  .github/CODEOWNERS
  cmake/presets/clang.cmake
  doc/src/Howto_lammps_gui.rst
  doc/src/Intro_authors.rst
  doc/src/JPG/lammps-gui-chart.png
  doc/src/JPG/lammps-gui-prefs-accel.png
  doc/src/JPG/lammps-gui-prefs-editor.png
  doc/src/JPG/lammps-gui-prefs-general.png
  doc/src/JPG/lammps-gui-prefs-image.png
  doc/utils/sphinx-config/_static/lammps-logo-large.jpg
  doc/utils/sphinx-config/_static/lammps-logo-large.png
  doc/utils/sphinx-config/conf.py.in
  doc/utils/sphinx-config/false_positives.txt
  src/INTEL/intel_intrinsics.h
  src/INTEL/intel_intrinsics_airebo.h
  src/LATBOLTZ/fix_lb_fluid.cpp
  src/MDI/fix_mdi_qm.cpp
  src/MDI/fix_mdi_qmmm.cpp
  src/OPENMP/pair_lj_cut_tip4p_cut_omp.cpp
  src/OPENMP/pair_lj_cut_tip4p_long_omp.cpp
  src/OPENMP/pair_lj_cut_tip4p_long_soft_omp.cpp
  src/OPENMP/pair_lj_long_tip4p_long_omp.cpp
  src/OPENMP/pair_tip4p_cut_omp.cpp
  src/OPENMP/pair_tip4p_long_omp.cpp
  src/OPENMP/pair_tip4p_long_soft_omp.cpp
  src/OPT/pair_lj_cut_tip4p_long_opt.cpp
  src/REPLICA/verlet_split.cpp
  src/REPLICA/verlet_split.h
  src/fix_ave_grid.cpp
  src/reader_native.cpp
  src/reader_xyz.cpp
  src/region_cylinder.cpp
  src/utils.cpp
  tools/lammps-gui/CMakeLists.txt
  tools/lammps-gui/TODO.md
  tools/lammps-gui/chartviewer.cpp
  tools/lammps-gui/imageviewer.cpp
  tools/lammps-gui/lammps-gui.appdata.xml
  tools/lammps-gui/lammpsgui.cpp
  tools/lammps-gui/main.cpp
  tools/lammps-gui/preferences.cpp
  unittest/force-styles/test_angle_style.cpp
  unittest/force-styles/test_bond_style.cpp
  unittest/force-styles/test_dihedral_style.cpp
  unittest/force-styles/test_improper_style.cpp
Labels: bugfix, maintenance

#4293 Bond/react: fixes and error checking
  doc/src/fix_bond_react.rst
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.stabilized
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.stabilized_variable_probability
  examples/PACKAGES/reaction/tiny_nylon/in.tiny_nylon.unstabilized
  examples/PACKAGES/reaction/tiny_nylon/rxn1_stp1_reacted.molecule_template
  examples/PACKAGES/reaction/tiny_nylon/rxn1_stp2_reacted.molecule_template
  examples/PACKAGES/reaction/tiny_nylon/tiny_nylon.data
  src/REACTION/fix_bond_react.cpp
  src/REACTION/fix_bond_react.h
Labels: user_reaction_package

#4298 Collected small fixes for LAMMPS and LAMMPS-GUI for the stable release
  doc/src/Tools.rst
  examples/COUPLE/plugin/liblammpsplugin.c
  src/CLASS2/angle_class2.cpp
  src/KOKKOS/pair_uf3_kokkos.cpp
  src/REACTION/fix_bond_react.cpp
  tools/lammps-gui/lammpsgui.cpp
  tools/lammps-gui/lammpsgui.h
  tools/lammps-gui/lammpswrapper.cpp
  tools/lammps-gui/main.cpp
Labels: bugfix

#4301 Gracefully error out if integer overflow in ReaxFF or QEq
  src/KOKKOS/fix_qeq_reaxff_kokkos.cpp
  src/KOKKOS/fix_qeq_reaxff_kokkos.h
  src/KOKKOS/kokkos.cpp
  src/KOKKOS/kokkos.h
  src/KOKKOS/pair_reaxff_kokkos.cpp
  src/QEQ/fix_qeq.cpp
  src/REAXFF/fix_qeq_reaxff.cpp
  src/REAXFF/reaxff_allocate.cpp
Labels: bugfix

#4297 Update version strings for release
  doc/lammps.1
  doc/src/Build_settings.rst
  doc/src/Commands_removed.rst
  doc/src/Packages_details.rst
  doc/src/Run_options.rst
  doc/src/bond_rheo_shell.rst
  doc/src/compute_rheo_property_atom.rst
  doc/src/fix_meso_move.rst
  doc/src/fix_mvv_dpd.rst
  doc/src/fix_rheo.rst
  doc/src/fix_rheo_oxidation.rst
  doc/src/fix_rheo_pressure.rst
  doc/src/fix_rheo_thermal.rst
  doc/src/fix_rheo_viscosity.rst
  doc/src/fix_rigid_meso.rst
  doc/src/fix_shake.rst
  doc/src/fix_smd_integrate_tlsph.rst
  doc/src/fix_smd_integrate_ulsph.rst
  doc/src/geturl.rst
  doc/src/neigh_modify.rst
  doc/src/pair_rheo.rst
  doc/src/pair_rheo_solid.rst
  doc/src/variable.rst
  python/lammps/core.py
  src/library.cpp
  src/version.h
  tools/lammps-gui/lammps-gui.appdata.xml
  tools/lammps-gui/org.lammps.lammps-gui.yml
Labels: maintenance
