Repository lammps/lammps, pull requests merged in 2025-06, with the labels that each got.

#4597 Small CMake updates
  cmake/CMakeLists.txt
  cmake/Modules/LAMMPSInterfacePlugin.cmake
  cmake/Modules/LAMMPSUtils.cmake
  cmake/Modules/MPI4WIN.cmake
  cmake/Modules/Packages/COLVARS.cmake
  cmake/Modules/Packages/GPU.cmake
  cmake/Modules/Testing.cmake
  cmake/presets/hip_amd.cmake
  cmake/presets/kokkos-hip.cmake
  examples/COUPLE/plugin/CMakeLists.txt
  examples/COUPLE/simple/CMakeLists.txt
  examples/plugins/LAMMPSInterfaceCXX.cmake
  unittest/c-library/CMakeLists.txt
Labels: cmake

#4567 New fix set command
  doc/src/Commands_fix.rst
  doc/src/fix.rst
  doc/src/fix_set.rst
  doc/src/run.rst
  doc/src/set.rst
  doc/utils/sphinx-config/false_positives.txt
  src/fix_set.cpp
  src/fix_set.h
  src/set.cpp
  src/set.h
  unittest/commands/test_set_property.cpp
Labels: enhancement

#4616 bond/react: another reaction-count bug fix
  src/REACTION/fix_bond_react.cpp
Labels: bugfix

#4581 Enable equal- and atom-style variables to invoke Python functions more directly with args
  doc/src/Python_call.rst
  doc/src/compute_angle_local.rst
  doc/src/compute_bond_local.rst
  doc/src/compute_dihedral_local.rst
  doc/src/create_atoms.rst
  doc/src/fix_controller.rst
  doc/src/fix_deposit.rst
  doc/src/python.rst
  doc/src/variable.rst
  doc/utils/sphinx-config/false_positives.txt
  examples/python/dump.1May25.python.wrap.g++.1
  examples/python/dump.1May25.python.wrap.g++.4
  examples/python/in.python.wrap
  examples/python/log.1May25.python.wrap.g++.1
  examples/python/log.1May25.python.wrap.g++.4
  src/PYTHON/python_impl.cpp
  src/PYTHON/python_impl.h
  src/compute_angle_local.cpp
  src/compute_bond_local.cpp
  src/compute_dihedral_local.cpp
  src/create_atoms.cpp
  src/fix_deposit.cpp
  src/lmppython.cpp
  src/lmppython.h
  src/variable.cpp
  src/variable.h
  src/write_dump.cpp
Labels: enhancement

#4624 Fix GPU architecture in CUDA preset for Kokkos
  cmake/presets/kokkos-cuda.cmake
Labels: enhancement

#4621 Add support for run and minimize style plugins and refactor plugin handling to become global
  doc/src/Commands_kspace.rst
  doc/src/Developer_plugins.rst
  doc/src/Fortran.rst
  doc/src/Library_create.rst
  doc/src/kspace_style.rst
  doc/src/plugin.rst
  examples/COUPLE/plugin/liblammpsplugin.c
  examples/COUPLE/plugin/liblammpsplugin.h
  examples/plugins/CMakeLists.txt
  examples/plugins/kspace_zero2.cpp
  examples/plugins/kspace_zero2.h
  examples/plugins/kspaceplugin.cpp
  examples/plugins/min_cg2.cpp
  examples/plugins/min_cg2.h
  examples/plugins/runminplugin.cpp
  examples/plugins/verlet2.cpp
  examples/plugins/verlet2.h
  fortran/lammps.f90
  python/lammps/core.py
  src/PLUGIN/plugin.cpp
  src/PLUGIN/plugin.h
  src/kspace.cpp
  src/kspace_zero.cpp
  src/kspace_zero.h
  src/lammps.cpp
  src/library.cpp
  src/library.h
  src/main.cpp
  src/update.cpp
  tools/swig/lammps.i
Labels: documentation, refactor, plugin

#4613 Set version date for next feature release
  doc/lammps.1
  doc/src/Commands_removed.rst
  doc/src/Developer_updating.rst
  doc/src/compute_bond_local.rst
  doc/src/compute_pair_local.rst
  doc/src/create_atoms.rst
  doc/src/fix_adapt.rst
  doc/src/fix_ave_moments.rst
  doc/src/fix_gjf.rst
  doc/src/fix_set.rst
  doc/src/molecule.rst
  doc/src/pair_lj_pirani.rst
  src/library.cpp
  src/version.h
Labels: maintenance

#4627 Fix segfault when masses are missing in post-reaction template in per-atom systems
  src/REACTION/fix_bond_react.cpp
Labels: bugfix

#4628 Collected small changes and fixes
  .github/release_steps.md
  .github/workflows/check-cpp23.yml
  cmake/Modules/Packages/ML-PACE.cmake
  doc/src/Fortran.rst
  doc/src/Library_scatter.rst
  doc/utils/requirements.txt
  doc/utils/sphinx-config/conf.py.in
  examples/COUPLE/plugin/liblammpsplugin.c
  examples/COUPLE/plugin/liblammpsplugin.h
  fortran/lammps.f90
  python/lammps/core.py
  src/.gitignore
  src/GRANULAR/fix_pour.cpp
  src/GRANULAR/pair_granular.cpp
  src/PYTHON/python_impl.cpp
  src/REPLICA/fix_pimd_nvt.cpp
  src/RIGID/fix_rigid_nh.cpp
  src/compute_angle_local.cpp
  src/compute_bond_local.cpp
  src/compute_dihedral_local.cpp
  src/create_atoms.cpp
  src/error.cpp
  src/error.h
  src/fix_deposit.cpp
  src/library.cpp
  src/library.h
  src/molecule.cpp
  src/pair.cpp
  src/set.cpp
  src/variable.cpp
  src/variable.h
  src/version.h
  tools/json/reformat-json.cpp
  tools/lammps-gui/chartviewer.cpp
  tools/lammps-gui/fileviewer.cpp
  tools/lammps-gui/findandreplace.cpp
  tools/lammps-gui/flagwarnings.cpp
  tools/lammps-gui/flagwarnings.h
  tools/lammps-gui/helpers.cpp
  tools/lammps-gui/helpers.h
  tools/lammps-gui/imageviewer.cpp
  tools/lammps-gui/lammps-gui.appdata.xml
  tools/lammps-gui/lammpsgui.cpp
  tools/lammps-gui/logwindow.cpp
  tools/lammps-gui/preferences.cpp
  tools/lammps-gui/slideshow.cpp
  tools/swig/lammps.i
  unittest/formats/test_molecule_file.cpp
Labels: cmake, maintenance, refactor

#4633 Fixes to RHEO package
  doc/src/fix_deform.rst
  src/RHEO/bond_rheo_shell.cpp
  src/RHEO/compute_rheo_kernel.cpp
  src/RHEO/compute_rheo_vshift.cpp
  src/RHEO/fix_rheo.cpp
  src/RHEO/fix_rheo_thermal.cpp
  src/RHEO/pair_rheo.cpp
  src/set.cpp
  src/set.h
Labels: rheo_package

#4580 Update Kokkos library in LAMMPS to v4.6.1
  cmake/Modules/Packages/KOKKOS.cmake
  doc/src/Build_extras.rst
  lib/kokkos/CHANGELOG.md
  lib/kokkos/CMakeLists.txt
  lib/kokkos/Makefile.kokkos
  lib/kokkos/Makefile.targets
  lib/kokkos/README.md
  lib/kokkos/cmake/KokkosCore_config.h.in
  lib/kokkos/cmake/build_env_info.cmake
  lib/kokkos/cmake/compile_tests/cuda_compute_capability.cc
  lib/kokkos/cmake/kokkos_arch.cmake
  lib/kokkos/core/src/Cuda/Kokkos_Cuda_BlockSize_Deduction.hpp
  lib/kokkos/core/src/Kokkos_Clamp.hpp
  lib/kokkos/core/src/Kokkos_Core_fwd.hpp
  lib/kokkos/core/src/Kokkos_MinMax.hpp
  lib/kokkos/core/src/impl/Kokkos_Core.cpp
  lib/kokkos/core/src/impl/Kokkos_NvidiaGpuArchitectures.hpp
  lib/kokkos/core/unit_test/TestTeamTeamSize.hpp
  lib/kokkos/master_history.txt
Labels: kokkos_package, update, ready

#4636 Add support for inter-/intra-molecular bonding to fix bond/create
  doc/src/fix_bond_create.rst
  src/MC/fix_bond_create.cpp
  src/MC/fix_bond_create.h
Labels: enhancement, refactor
